### ISSUE TITLE
Object not found for update _Installation

### ISSUE THREAD

**Issue by vocsygautam** [parse-community/Parse-SDK-Flutter#1007]
parse_server_sdk_flutter: ^8.0.0
FLUTTER RELEASE SDK :- 3.19.5

this is my code:
`Future<void> initInstallation(String userId) async {
  final String? token = await setupToken();
  final ParseInstallation currentInstallation = await ParseInstallation.currentInstallation();
  print("Installation Entry get objectId: ${currentInstallation.objectId} userId: ${currentInstallation['UserId']} $currentInstallation");
  if (currentInstallation.objectId == null) {
    await currentInstallation.subscribeToChannel('push');
    currentInstallation.deviceToken = token;
    currentInstallation.set('UserId', userId);
    final ParseResponse pr = await currentInstallation.save();
    print("Installation Entry Case 1 create result: ${pr.result} error: ${pr.error}");
  } else {
    final ParseObject installation = ParseObject('_Installation');
    installation.objectId = currentInstallation.objectId;
    installation.set('deviceToken', token);
    installation.set('UserId', userId);
    final ParseResponse pr = await installation.save();
    print("Installation Entry Case 2 update result: ${pr.result} error: ${pr.error}");
  }
}
`

when else code run object delete from database and show error: 

`----
 ParseException (Type: ObjectNotFound) :
 Code: 101
Message: Object not found for update.----`

**Comment by mtrezza** [comment]
Closing this issue since it is not a clear description of the issue. Please use the issue template and paste the code in a readable format with line breaks.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [dart-v9.4.1](https://github.com/parse-community/Parse-SDK-Flutter/releases/tag/dart-9.4.1)
