### ISSUE TITLE
Release fails

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Flutter#1028]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description

Release fails with error:

> The current Dart SDK version is 3.0.7.
> Because parse_server_sdk requires SDK version >=3.2.6 <4.0.0, version solving failed.

### Steps to reproduce

See https://github.com/parse-community/Parse-SDK-Flutter/actions/runs/11389226076/job/31688020783

**Comment by mtrezza** [comment]
@mbfakourii could you please take a look? I noticed that the last 2 releases did not publish.

**Comment by mbfakourii** [comment]
> @mbfakourii could you please take a look? I noticed that the last 2 releases did not publish.

It seems there is a problem with the CLI.
The [release-automated](https://github.com/parse-community/Parse-SDK-Flutter/blob/a3449f4a1c4060f6afea71f50b204cb5e5a37bd2/.github/workflows/release-automated.yml) cli works based on the latest version of Flutter, but it should work on the lowest version supported by us.

**Comment by mbfakourii** [comment]
Our version support rules do not apply to this cli.
