### ISSUE TITLE
Does LDS is implemented in sdk?

### ISSUE THREAD

**Issue by monajafi** [parse-community/Parse-SDK-Flutter#197]
It's mentioned that local persistence is implemented, is it like LDS in android and iOS original sdk?
The original LDS has a performance issue for a table with rows say more than 500 rows

**Comment by phillwiggins** [comment]
Hey Mousa

Strange is implemented. It comes in form on Sembast or Shared Preferences.
Shared preferences is how the ParseSdk on Android works. Sembast is a NoSQL
DB wrote for Flutter.

I'm not sure what LDS is, and in all honest, have not used this SDK in
anger to understand it's limitations.

**Comment by monajafi** [comment]
I couldn't find in docs how to use local data storage. in android and iOS sdk there is a query.fromLocalDatastore and query.fromNetwork to choose a local and network query also there is a parseObject.pinInBackground for local storage also we should enable local data store in parse initialisation. How is in flutter sdk

**Comment by rodrigosmarques** [comment]
This lib does not yet have these features.

**Comment by phillwiggins** [comment]
Hey Mousa

We do have a similar feature called CoreStote. Either choosing
CoreStoreSembast or CoreStorePrefs.

You can pin objects as local storage too.

**Comment by monajafi** [comment]
please update the Docs how to use CoreStoreSembast or pin and query objects locally.

**Comment by phillwiggins** [comment]
There is a small section on saving objects using pin. If it's not clear,
please add any suggestions. There's also mention of secure storage but that
hasn't got a lot of information yet as it's not quite released.

**Comment by phillwiggins** [comment]
There's not been much movement on this recently. Are we safe to close?

**Comment by fischerscode** [comment]
I am now closing this. Feel free to reopen if there is still a problem.
