### ISSUE TITLE
Does the SDK support OR query?

### ISSUE THREAD

**Issue by thphuc** [parse-community/Parse-SDK-Flutter#213]

**Comment by rodrigosmarques** [comment]
does not support.  I even started to implement, but I did not finish

**Comment by thphuc** [comment]
Hi @rodrigosmarques 
Hope you are doing well.
How is it going?
I may have some time to help on this, please let me know. Thanks!

**Comment by WahdanZ** [comment]
@rodrigosmarques  it there any update regarding this one I can do some help also

**Comment by rodrigosmarques** [comment]
Hi @WahdanZ .
I didn't have time to go back in this feature.
If you have conditions, you can build

**Comment by maaeps** [comment]
Hi,
I am currently working on such an OR Query.
In the Android SDK, they throw an error, if one of the subquerys uses "selectKeys"/"dontSelectKeys".

Does anyone know, if the Parse-Server does not support this or if it's just missing feature in the android implementation?

**Comment by maaeps** [comment]
This feature got added in #317 without caring about "selectKeys"/"dontSelectKeys".

**Comment by Loudsa** [comment]
`
     QueryBuilder query = QueryBuilder.or(ParseObject("Test"), [
        QueryBuilder(ParseObject("Test"))..whereStartsWith("order", 1),
        QueryBuilder(ParseObject("Test"))..whereStartsWith("number", 'test-1'),
      ]);
`
I think you should say this
