### ISSUE TITLE
Relations in query

### ISSUE THREAD

**Issue by michaldev** [parse-community/Parse-SDK-Flutter#229]
I have class "Product" with category (relational) field. I added product and category by Parse dashboard.

but I have problem:
`"category":{"__type":"Relation","className":null,"objects":null}}
`
I search item by query:
```
var queryProduct = QueryBuilder(ParseObject('Product'))
      ..whereContains('name', text);
```

**Comment by rodrigosmarques** [comment]
Hi @michaldev 

What version are you using?

**Comment by vonbarnekowa** [comment]
Hey!

I have the same issue. I'm running on 1.0.22.

**Comment by rodrigosmarques** [comment]
I didn't do tests with relational.
I'll do some tests and return to you

**Comment by vonbarnekowa** [comment]
Thank you.

**Comment by rodrigosmarques** [comment]
Hi guys.
Reading the Parse documentation what I understand is that ParseRelation does not return results in the query.
I also checked the documentation for Android and Java Script.
For Flutter, You need to fetch the relationship objects using
```dart
final relation = user.getRelation ('dietPlans');
`` `
I did a test and it seems this didn't work in lib.
I will debug and then return the result.

**Comment by WahdanZ** [comment]
@rodrigosmarques 
in query builder, you should use this 
queryBuilder.includeObject(["category"]);

**Comment by rodrigosmarques** [comment]
@WahdanZ 
include doesn't work with Relations, only with Pointers

![](https://user-images.githubusercontent.com/17687286/62419394-6ab17180-b655-11e9-9e6c-9531fb75350b.jpeg)

![](https://user-images.githubusercontent.com/17687286/62419394-6ab17180-b655-11e9-9e6c-9531fb75350b.jpeg)

parse-community/parse-server#4138
parse-community/parse-server#2850
https://stackoverflow.com/questions/45645985/parse-sdk-android-query-with-relation-using-include-is-not-working

@michaldev and @vonbarnekowa 
use __whereRelatedTo__ to retrieve objects in relation, in separated Query.

**Comment by vonbarnekowa** [comment]
I found another issue. I don't know if they are related to each other. But if you have a relation that contains more than one item, the result will be null. With one or zero items it works.

**Comment by tvajjhala** [comment]
Any update on this? I'm struggling with getting relation data for an Object.

**Comment by ZeroNilZero** [comment]
@vonbarnekowa how do you fix that?

> I found another issue. I don't know if they are related to each other. But if you have a relation that contains more than one item, the result will be null. With one or zero items it works.

**Comment by FNPCMDs** [comment]
Hey, I have same problem:
`"messages":{"__type":"Relation","className":null,"objects":null}`

Did anyone fix that?

**Comment by ZeroNilZero** [comment]
[this](https://github.com/parse-community/Parse-SDK-Flutter/issues/399#issuecomment-664686299) may help #399

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
