### ISSUE TITLE
ParseACL: setRole methods missing

### ISSUE THREAD

**Issue by rostopira** [parse-community/Parse-SDK-Flutter#247]

**Comment by gorillatapstudio** [comment]
It's still missing

**Comment by gorillatapstudio** [comment]
@maaeps  @phillwiggins  can you guys check if it is still missing?

**Comment by SuperKMan** [comment]
How I can set Role ACL to object? I never saw setRoleWriteAccess and setRoleReadAccess in SDK.

**Comment by teddysbeach** [comment]
I also need it.. 
the alternative solution is to use "Cloud code" temporarily.

**Comment by dogusdicle** [comment]
parseACL.setReadAccess(userId:  "role:Admin", allowed: true);
parseACL.setWriteAccess(userId: "role:Admin", allowed: true);

its working
