### ISSUE TITLE
Cannot update custom value in User class

### ISSUE THREAD

**Issue by Tridie2000** [parse-community/Parse-SDK-Flutter#256]
My User class has a custom property (points). I'm trying to update this property. According to a print statement I added to the code it seems to work except I don't see any change on the server side. 

```
ParseUser user = await ParseUser.currentUser() as ParseUser;
if (user != null) {
   ParseUser incrementUser = ParseUser.forQuery()..getObject(user.objectId);
   incrementUser.set('points', (user.get('points') + 1));
   await incrementUser.save();
   print('save: $incrementUser');
}

**Comment by Tridie2000** [comment]
I also tried this piece of code and the response is successful but the data doesn't update on the server. What is going on here?

```
ParseUser user = await ParseUser.currentUser() as ParseUser;
    if (user != null) {
      user.set('points', user.get('points') + 1);
      ParseResponse response = await user.save();
      if (response.success) {
        print('ok');
      } else {
        print(response.error);
      }
      print('save: $user');
    }

**Comment by danibjor** [comment]
Check user.objectId. Is that set? Or is it null?

**Comment by Tridie2000** [comment]
The user objectId is not null.

**Comment by mdc555** [comment]
Any update on this??
Same here. I've tried several ways but it's not updating. But curiously, it was working fine and I didn't any change to my code....

**Comment by mdc555** [comment]
The User doesn't get updated when it's logged in....

**Comment by jbcaveman** [comment]
Did you check the logs for any permission errors? Most likely you need to specify using the master key for updating User object because Parse automatically generates tight ACLs for that class. Try:
`incrementUser.save(null, { useMasterKey: true });`

**Comment by mdc555** [comment]
I've finally managed to get this working. I had to move that logic to a Cloud Code passing `masterKey: true` and everything is fine but I couldn't get it working straight from my app. I didn't get any error on my logs. Supposedly everything was OK but the user never updated.
I tried to logout and login back the user and at that point it worked but whenever I started my app that update never happened. A bit strange but now solved using Cloud Code.

**Comment by jbcaveman** [comment]
Parse always generates tight ACLs on the User class, so you cannot modify a user in the client SDK unless that user is the authenticated currentUser. That said, you should always increment values on the server side rather than client side to avoid stale data issues and other conflicts. To save objects with tight ACLs server-side, you need to be sure to specify using the master key, like: 
`incrementUser.save(null, { useMasterKey: true });`

**Comment by jbcaveman** [comment]
If you haven't yet, this is a must-read for anyone using Parse Server: https://docs.parseplatform.org/js/guide/#security

**Comment by mdc555** [comment]
I have ACLs on my User class. The user I was trying to update was the currentUser already authenticated. As I said, I didn't get any error. It just didn't update the currentUser.
It only worked when the user have just logged in but it didn't worked when the user opens the app and have an "active session"

**Comment by maaeps** [comment]
Is this still a problem?

**Comment by kristiehuang** [comment]
Not sure if this was resolved, but getting same exact problem

> I have ACLs on my User class. The user I was trying to update was the currentUser already authenticated. As I said, I didn't get any error. It just didn't update the currentUser.
> It only worked when the user have just logged in but it didn't worked when the user opens the app and have an "active session"

**Comment by maaeps** [comment]
@kristiehuang 
Some changes have been made in 1.0.27 and I think this has been solved.
Are you using version 1.0.27 (not yet released to pub.dev) or an older version?
