### ISSUE TITLE
Cloud Request Not  Recognising User

### ISSUE THREAD

**Issue by pastordee** [parse-community/Parse-SDK-Flutter#266]
Hi guys is anyone experiencing this, since version 1.0.22  cloud request does not  recognise request.user, every time I try it, it says user not defined and is the same in 1.0.24 
I am running the latest parse server which is 3.8.0.

I get this error: Failed running cloud function (my function) for user undefined with:

**Comment by matskosan** [comment]
You need to set _autoSendSessionId: true_ in the ParseCloudFunction constructor.

**Comment by WahdanZ** [comment]
and also you don’t have to use master key you should use clientkey

**Comment by negiot** [comment]
Hi guys i have the same problem on back4app. I set both the autoSendSessionId and the clientkey .... any ideas? Thanks for your help.
