### ISSUE TITLE
Copy an existing ParseObject

### ISSUE THREAD

**Issue by aBuder** [parse-community/Parse-SDK-Flutter#267]
Hi,

what is the best way to copy an existing ParseObject? In my example I have template object with child object. If  user will create a new object from template, I have to copy object from template object and append user relation. The new copy object should be saved later and have an new objectId

**Comment by phillwiggins** [comment]
Hey @aBuder 

As there is no reflection in Dart, we have to create slightly hacky version. Try something like this:-

`User clonedUser = user.clone(user.toJson(full: true, forApiRQ: false));`
