### ISSUE TITLE
Does Parse sdk support to do forgot password?

### ISSUE THREAD

**Issue by hautran90** [parse-community/Parse-SDK-Flutter#269]
Hi @Channel. Does Parse sdk support to do forgot password? I only find it supported requestPasswordRese. Thanks all!

**Comment by phillwiggins** [comment]
Hey

What's the difference?

**Comment by Atteprojects** [comment]
I have this issue as well.
the requestPasswordRese sends a reset email instruction to a user that is already logged in and it does not take any arguments.
How do I let the user reset their forgotten password if they are not logged in?

**Comment by RodrigoSMarques** [comment]
@Atteprojects 
See my code sample.

```dart
  Future<ApiResponse> recoveryPassword(String email) async {
    final ParseUser user = ParseUser(email.toLowerCase(), '', email);
    final ParseResponse parseResponse = await user.requestPasswordReset();
    if (parseResponse.success) {
      return ApiResponse.success();
    } else {
      return ApiResponse.error(
          error: ApiError(
              code: parseResponse.error.code,
              message: ParseErrors.getDescription(parseResponse.error.code)));
    }
  }
```

**Comment by Atteprojects** [comment]
This is very helpful. Thank you very much!

**Comment by fischerscode** [comment]
Not tried this, but this should do the trick as well:
```
Future<ParseResponse> response = ParseUser(null, null, "email@example.com").requestPasswordReset();
```
