### ISSUE TITLE
ACL's getWriteAccess returns READ permission

### ISSUE THREAD

**Issue by qwertyway** [parse-community/Parse-SDK-Flutter#275]
in source code of parse_acl.dart the function below returns read permission, which is incorrect

` 
 bool getWriteAccess({@required String userId}) {
     if (userId == null) {
         throw 'cannot getWriteAccess for null userId';
     }
     final _ACLPermissions _permissions = _permissionsById[userId];
     return _permissions != null && _permissions.getReadPermission();
 }
`

lib version 1.0.24

**Comment by davimacedo** [comment]
closed by https://github.com/parse-community/Parse-SDK-Flutter/pull/277
