### ISSUE TITLE
Full Text Search?

### ISSUE THREAD

**Issue by buckettt** [parse-community/Parse-SDK-Flutter#284]
Is full text search supported? I can't find any evidence of it...

Here is the javascript version:
https://docs.parseplatform.org/js/guide/#full-text-search

If not I presume a cloud code function that handles the query may be required.

**Comment by rodrigosmarques** [comment]
Hi. 

Yes.  Supports full text search.  I am using in an application.  I can send you an example later.

**Comment by buckettt** [comment]
@rodrigosmarques excellent - thanks very much!

**Comment by rodrigosmarques** [comment]
Hi @buckettt 
Example
///dart
    QueryBuilder queryBuilder =
        QueryBuilder<ParseObject>(ParseObject(keyAdTable));
    queryBuilder.whereContains(keyAdTitle, _filter.search, caseSensitive: false);
    }
///
