### ISSUE TITLE
Please fix your example of using Sembast v2

### ISSUE THREAD

**Issue by igkvl** [parse-community/Parse-SDK-Flutter#285]
Store and Record are deprecated in sembast v2, 
thank you!

**Comment by TomWFox** [comment]
Could you provide a pr with the suggested changes?

**Comment by jwfing** [comment]
please refer to https://github.com/parse-community/Parse-SDK-Flutter/pull/290

**Comment by phillwiggins** [comment]
Hey

Please can you point the merge request to the branch labelled
'release/1.0.25'.

Ill look at this today and have it merged as soon as.

Thank you!

**Comment by mregandla** [comment]
This fixes the broken example app: https://github.com/parse-community/Parse-SDK-Flutter/pull/294
