### ISSUE TITLE
How can I use it in Web application?

### ISSUE THREAD

**Issue by jaweii** [parse-community/Parse-SDK-Flutter#286]
Can you give me a example?

**Comment by JoaoArmando** [comment]
Hey, did you figure out how to use it?

**Comment by jaweii** [comment]
Now I'm not use the repository, I use the   JS package   and   link parse.min.js in my index.html.
But I think my solution is not good, I need to write different code in different platform.

**Comment by JoaoArmando** [comment]
Oh, i think i'll use the rest api. The parse server never initialize in my case.

**Comment by jaweii** [comment]
I'll give you my code to reference later.

**Comment by jaweii** [comment]
My solution

pubspec.yaml:
`   js: ^0.6.0`

Add parse js sdk to index.html like this:
```
<body>
  <script src="https://npmcdn.com/parse@2.9.0/dist/parse.min.js"></script>
  <script src="main.dart.js" type="application/javascript"></script>
  <script>
    Parse.serverURL = 'https://server-weiyan.buzhundong.com/parse'
    Parse.initialize('APP_ID', 'CLIENT_SECRET')
    Parse.Config.get().then(_ => console.log('Parse Server: Connected'))
  </script>
</body>
```
I write the following code in `lib/js/parse.dart` ( I'm not implemen all features):
```
@JS('Parse')
library parse;

import 'package:js/js.dart';
import 'dart:html';
import 'dart:async';

@JS('Query')
class ParseQuery {
  ParseQuery(this.className);
  final String className;

  external ParseQuery include(List<String> list);
  external ParseQuery equalTo(String key, dynamic value);
  external Promise<List<ParseObject>> find();
  external Promise<ParseObject> first();
  external ParseQuery limit(num limit);
  external ParseQuery descending(String key);
  external ParseQuery ascending(String key);
  external ParseQuery select(List<String> keys);
}

@anonymous
@JS('wind
```ow.Promise')
class Promise<T> {
  Promise();
  external Promise then(void function(T res));
}

@JS('Object')
class ParseObject {
  ParseObject(this.className);
  final String className;
  external String get id;
  external dynamic set(String key, dynamic value);
  external dynamic get(String key);
}

@JS('File')
class ParseFile {
  external String url();
}

Now I can user some Parse-JS-SDK methods through the `parse.dart`:

`models/home.dart`:
```
import 'package:PROJECT_NAME/js/parse.dart';
  ... ...
  Future<dynamic> fetchAlbums() async {
    loadingAlbums = true;
    notifyListeners();
    final query = ParseQuery('Albums');
    query.include(['hero']);
    Completer completer = Completer();
    query.find().then(completer.complete);
    final List<ParseObject> res =
        (await completer.future).cast<ParseObject>().toList();
    loadingAlbums = false;
    albums = res ?? [];
    notifyListeners();
    return albums;
  }
```

That's all.

**Comment by maxiundtesa** [comment]
**I found a much better solution.**
The good thing about this plugin is that it is completely written in dart and barely uses any platform channels.
Therefore basically the whole codebase already supports flutter web.
The only problems are the coreStore and a database that is used in the example.
The coreStore problem is fixable with a new version of the shared_preferences plugin which supports web.
The database problem is not so easy to fix, because it currently depends on the path_provider plugin, which doesn't support web yet. But I for example dont need this functionality.

I already did this in my [branch](https://github.com/maxiundtesa/Parse-SDK-Flutter/tree/flutter_web_fix), or just fork this repository and change it in the pubspec.yaml to `^0.5.6`

I also had to enable cors on my parse server, otherwise I just got XMLRequest errors.
But enabling cors was very easy, just follow the [instructions](https://expressjs.com/en/resources/middleware/cors.html)

Now the plugin is working absolutely fine in my flutter app and thats a much better solution than using the javascript library

**Comment by mregandla** [comment]
@maxiundtesa https://github.com/hivedb/hive implementation of coreStore may help. It supports cross-platform which includes web.

**Comment by jackhax** [comment]
> **I found a much better solution.**
> The good thing about this plugin is that it is completely written in dart and barely uses any platform channels.
> Therefore basically the whole codebase already supports flutter web.
> The only problems are the coreStore and a database that is used in the example.
> The coreStore problem is fixable with a new version of the shared_preferences plugin which supports web.
> The database problem is not so easy to fix, because it currently depends on the path_provider plugin, which doesn't support web yet. But I for example dont need this functionality.
> 
> I already did this in my [branch](https://github.com/maxiundtesa/Parse-SDK-Flutter/tree/flutter_web_fix), or just fork this repository and change it in the pubspec.yaml to `^0.5.6`
> 
> I also had to enable cors on my parse server, otherwise I just got XMLRequest errors.
> But enabling cors was very easy, just follow the [instructions](https://expressjs.com/en/resources/middleware/cors.html)
> 
> Now the plugin is working absolutely fine in my flutter app and thats a much better solution than using the javascript library

How to enable CORS for my parse server?

**Comment by jackhax** [comment]
How to download ParseFile on flutter web???

**Comment by gorillatapstudio** [comment]
> **I found a much better solution.**
> The good thing about this plugin is that it is completely written in dart and barely uses any platform channels.
> Therefore basically the whole codebase already supports flutter web.
> The only problems are the coreStore and a database that is used in the example.
> The coreStore problem is fixable with a new version of the shared_preferences plugin which supports web.
> The database problem is not so easy to fix, because it currently depends on the path_provider plugin, which doesn't support web yet. But I for example dont need this functionality.
> 
> I already did this in my [branch](https://github.com/maxiundtesa/Parse-SDK-Flutter/tree/flutter_web_fix), or just fork this repository and change it in the pubspec.yaml to `^0.5.6`
> 
> I also had to enable cors on my parse server, otherwise I just got XMLRequest errors.
> But enabling cors was very easy, just follow the [instructions](https://expressjs.com/en/resources/middleware/cors.html)
> 
> Now the plugin is working absolutely fine in my flutter app and thats a much better solution than using the javascript library

How's the web implementation now? Are all the issues you pointed out solved already? I'd like to give it a try.

**Comment by fischerscode** [comment]
2.0.0 should fully support web, even through pub.dev does not label it like this.
For more information, see the [2.0.0 migration guide](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/docs/migrate-2-0-0.md).
