### ISSUE TITLE
Unable to login with clientKey instead  masterKey. 

### ISSUE THREAD

**Issue by rameshkec85** [parse-community/Parse-SDK-Flutter#288]
I have run the local parse server, and tried to run in the iOS simulator of the example app provided in this repo. I have removed masterKey while initialising  Parse sdk and instead provided clientKey, I am unable to login or sign up.

* **Note**: I don't want to expose the **masterKey** to Client apps.

**Comment by WahdanZ** [comment]
it's work with me fine I used client key
