### ISSUE TITLE
Calling ParseUser user = await ParseUser.currentUser(); results in error

### ISSUE THREAD

**Issue by elpitaj** [parse-community/Parse-SDK-Flutter#291]
Im not sure why Im seeing this error.  Any help would be appreciated

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'getString' was called on null.
Receiver: null
Tried calling: getString("flutter_parse_sdk_user")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ParseUser._getUserFromLocalStore (package:parse_server_sdk/src/objects/parse_user.dart:333:45)
<asynchronous suspension>
#2      ParseUser.currentUser (package:parse_server_sdk/src/objects/parse_user.dart:119:20)
<asynchronous suspension>
#3      UserRepository.getUser (package:la_c/models/user_repository.dart:34:27)
<asynchronous suspension>
#4      new UserRepository (package:la_c/models/user_repository.dart:27:5)
#5      MyApp.build (package:la_c/main.dart:83:45)
#6      StatelessElement.build (package:flutter/src/widgets/framework.dart:4009:28)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#9      Compo<…>

**Comment by aBuder** [comment]
Can you post content of `flutter doctor` your `pubspec.yml` and also the function where you call `ParseUser.currentUser()`

**Comment by israelmarmar** [comment]
I have the same problem.

**Comment by RodrigoSMarques** [comment]
No problem here.  Can you post the startup code of Parse and the call where the error occurs?

**Comment by israelmarmar** [comment]
E/flutter (26268): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'getString' was called on null.
Syncing files to device...                                                                               
E/flutter (26268): Receiver: null                               
Syncing files to device...                                                                               
E/flutter (26268): Tried calling: getString("flutter_parse_sdk_user")

**Comment by israelmarmar** [comment]
Here
var user = await ParseUser.currentUser() as ParseUser;

E/flutter (26268): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'getString' was called on null.
Syncing files to device                                                                             
E/flutter (26268): Receiver: null                               
Syncing files to device                                                                               
E/flutter (26268): Tried calling: getString("flutter_parse_sdk_user")

**Comment by mregandla** [comment]
I am not facing any issues. 

`coreStore` is null in your case. Looks like `Parse().initialize()` not done properly. Can you please cross-check?

**Comment by phillwiggins** [comment]
Can this be closed?
