### ISSUE TITLE
How to download ParseFile in flutter web?

### ISSUE THREAD

**Issue by jackhax** [parse-community/Parse-SDK-Flutter#297]
When i try to download a ParseFile using parseFile.download(), it gives the following error:

> Overflow on channel: plugins.flutter.io/path_provider.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
error @ html_dart2js.dart:38332
_printDebugString @ natives.dart:21
_printDebug @ natives.dart:13
push @ channel_buffers.dart:143
handlePlatformMessage @ plugin_registry.dart:84
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
handlePlatformMessage @ plugin_registry.dart:76
sendPlatformMessage @ window.dart:186
[_sendPlatformMessage] @ binding.dart:175
send @ binding.dart:224
invokeMethod @ platform_channel.dart:314
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
invokeMethod @ platform_channel.dart:312
getTemporaryDirectory @ path_provider.dart:37
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
getTemporaryDirectory @ path_provider.dart:35
download @ parse_file.dart:77
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
download @ parse_file.dart:72
getFile @ home.dart:51
onValue @ async_patch.dart:47
runUnary @ zone.dart:1381
handleValue @ future_impl.dart:139
handleValueCallback @ future_impl.dart:680
_propagateToListeners @ future_impl.dart:709
[_completeWithValue] @ future_impl.dart:524
(anonymous) @ future_impl.dart:554
_microtaskLoop @ schedule_microtask.dart:43
_startMicrotaskLoop @ schedule_microtask.dart:52
(anonymous) @ async_patch.dart:168
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:166
_scheduleImmediate @ async_patch.dart:138
_scheduleAsyncCallback @ schedule_microtask.dart:73
_rootScheduleMicrotask @ zone.dart:1187
scheduleMicrotask @ zone.dart:1401
[_asyncComplete] @ future_impl.dart:553
complete @ future_impl.dart:42
(anonymous) @ browser_client.dart:63
runUnary @ zone.dart:1381
handleValue @ future_impl.dart:139
handleValueCallback @ future_impl.dart:680
_propagateToListeners @ future_impl.dart:709
[_complete] @ future_impl.dart:514
_cancelAndValue @ stream_pipe.dart:65
(anonymous) @ stream.dart:1253
_checkAndCall @ operations.dart:326
dcall @ operations.dart:331
(anonymous) @ html_dart2js.dart:35661
load (async)
[_addEventListener] @ html_dart2js.dart:15095
[dartx.addEventListener] @ html_dart2js.dart:15083
[_tryResume] @ html_dart2js.dart:35713
_EventStreamSubscription.new @ html_dart2js.dart:35662
listen @ html_dart2js.dart:35562
get first @ stream.dart:1251
(anonymous) @ browser_client.dart:61
runUnary @ zone.dart:1381
handleValue @ future_impl.dart:139
handleValueCallback @ future_impl.dart:680
_propagateToListeners @ future_impl.dart:709
[_complete] @ future_impl.dart:514
_cancelAndValue @ stream_pipe.dart:65
(anonymous) @ stream.dart:1253
_checkAndCall @ operations.dart:326
dcall @ operations.dart:331
(anonymous) @ html_dart2js.dart:35661
load (async)
[_addEventListener] @ html_dart2js.dart:15095
[dartx.addEventListener] @ html_dart2js.dart:15083
[_tryResume] @ html_dart2js.dart:35713
_EventStreamSubscription.new @ html_dart2js.dart:35662
listen @ html_dart2js.dart:35562
get first @ stream.dart:1251
send @ browser_client.dart:55
onValue @ async_patch.dart:47
runUnary @ zone.dart:1381
handleValue @ future_impl.dart:139
handleValueCallback @ future_impl.dart:680
_propagateToListeners @ future_impl.dart:709
[_completeWithValue] @ future_impl.dart:524
(anonymous) @ future_impl.dart:554
_microtaskLoop @ schedule_microtask.dart:43
_startMicrotaskLoop @ schedule_microtask.dart:52
(anonymous) @ async_patch.dart:168
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:166
_scheduleImmediate @ async_patch.dart:138
_scheduleAsyncCallback @ schedule_microtask.dart:73
_rootScheduleMicrotask @ zone.dart:1187
scheduleMicrotask @ zone.dart:1401
[_asyncComplete] @ future_impl.dart:553
complete @ future_impl.dart:42
(anonymous) @ browser_client.dart:63
runUnary @ zone.dart:1381
handleValue @ future_impl.dart:139
handleValueCallback @ future_impl.dart:680
_propagateToListeners @ future_impl.dart:709
[_complete] @ future_impl.dart:514
_cancelAndValue @ stream_pipe.dart:65
(anonymous) @ stream.dart:1253
_checkAndCall @ operations.dart:326
dcall @ operations.dart:331
(anonymous) @ html_dart2js.dart:35661
load (async)
[_addEventListener] @ html_dart2js.dart:15095
[dartx.addEventListener] @ html_dart2js.dart:15083
[_tryResume] @ html_dart2js.dart:35713
_EventStreamSubscription.new @ html_dart2js.dart:35662
listen @ html_dart2js.dart:35562
get first @ stream.dart:1251
(anonymous) @ browser_client.dart:61
runUnary @ zone.dart:1381
handleValue @ future_impl.dart:139
handleValueCallback @ future_impl.dart:680
_propagateToListeners @ future_impl.dart:709
[_complete] @ future_impl.dart:514
_cancelAndValue @ stream_pipe.dart:65
(anonymous) @ stream.dart:1253
_checkAndCall @ operations.dart:326
dcall @ operations.dart:331
(anonymous) @ html_dart2js.dart:35661
load (async)
[_addEventListener] @ html_dart2js.dart:15095
[dartx.addEventListener] @ html_dart2js.dart:15083
[_tryResume] @ html_dart2js.dart:35713
_EventStreamSubscription.new @ html_dart2js.dart:35662
listen @ html_dart2js.dart:35562
get first @ stream.dart:1251
send @ browser_client.dart:55
onValue @ async_patch.dart:47
runUnary @ zone.dart:1381
handleValue @ future_impl.dart:139
handleValueCallback @ future_impl.dart:680
_propagateToListeners @ future_impl.dart:709
[_completeWithValue] @ future_impl.dart:524
(anonymous) @ future_impl.dart:554
_microtaskLoop @ schedule_microtask.dart:43
_startMicrotaskLoop @ schedule_microtask.dart:52
(anonymous) @ async_patch.dart:168
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:166
_scheduleImmediate @ async_patch.dart:138
_scheduleAsyncCallback @ schedule_microtask.dart:73
_rootScheduleMicrotask @ zone.dart:1187
scheduleMicrotask @ zone.dart:1401
[_asyncComplete] @ future_impl.dart:553
complete @ future_impl.dart:42
(anonymous) @ browser_client.dart:63
runUnary @ zone.dart:1381
handleValue @ future_impl.dart:139
handleValueCallback @ future_impl.dart:680
_propagateToListeners @ future_impl.dart:709
[_complete] @ future_impl.dart:514
_cancelAndValue @ stream_pipe.dart:65
(anonymous) @ stream.dart:1253
_checkAndCall @ operations.dart:326
dcall @ operations.dart:331
(anonymous) @ html_dart2js.dart:35661
load (async)
[_addEventListener] @ html_dart2js.dart:15095
[dartx.addEventListener] @ html_dart2js.dart:15083
[_tryResume] @ html_dart2js.dart:35713
_EventStreamSubscription.new @ html_dart2js.dart:35662
listen @ html_dart2js.dart:35562
get first @ stream.dart:1251
(anonymous) @ browser_client.dart:61
runUnary @ zone.dart:1381
handleValue @ future_impl.dart:139
handleValueCallback @ future_impl.dart:680
_propagateToListeners @ future_impl.dart:709
[_complete] @ future_impl.dart:514
_cancelAndValue @ stream_pipe.dart:65
(anonymous) @ stream.dart:1253
_checkAndCall @ operations.dart:326
dcall @ operations.dart:331
(anonymous) @ html_dart2js.dart:35661
load (async)
[_addEventListener] @ html_dart2js.dart:15095
[dartx.addEventListener] @ html_dart2js.dart:15083
[_tryResume] @ html_dart2js.dart:35713
_EventStreamSubscription.new @ html_dart2js.dart:35662
listen @ html_dart2js.dart:35562
get first @ stream.dart:1251
send @ browser_client.dart:55
onValue @ async_patch.dart:47
runUnary @ zone.dart:1381
handleValue @ future_impl.dart:139
handleValueCallback @ future_impl.dart:680
_propagateToListeners @ future_impl.dart:709
[_completeWithValue] @ future_impl.dart:524
(anonymous) @ future_impl.dart:554
_microtaskLoop @ schedule_microtask.dart:43
_startMicrotaskLoop @ schedule_microtask.dart:52
(anonymous) @ async_patch.dart:168
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:166
_scheduleImmediate @ async_patch.dart:138
_scheduleAsyncCallback @ schedule_microtask.dart:73
_rootScheduleMicrotask @ zone.dart:1187
scheduleMicrotask @ zone.dart:1401
[_asyncComplete] @ future_impl.dart:553
complete @ future_impl.dart:42
[_complete] @ ticker.dart:380
ticker$.TickerFuture.complete @ ticker.dart:370
[_animateToInternal] @ animation_controller.dart:586
reverse @ animation_controller.dart:491
deactivate @ ink_highlight.dart:93
updateHighlight @ ink_well.dart:587
[_handleTap] @ ink_well.dart:702
(anonymous) @ ink_well.dart:789
invokeCallback @ recognizer.dart:182
handleTapUp @ tap.dart:486
[_checkUp] @ tap.dart:264
handlePrimaryPointer @ tap.dart:199
handleEvent @ recognizer.dart:467
[_dispatch] @ pointer_router.dart:76
(anonymous) @ pointer_router.dart:117
forEach @ linked_hash_map.dart:23
[_dispatchEventToRoutes] @ pointer_router.dart:115
route @ pointer_router.dart:101
handleEvent @ binding.dart:218
dispatchEvent @ binding.dart:198
[_handlePointerEvent] @ binding.dart:156
[_flushPointerEventQueue] @ binding.dart:102
[_handlePointerDataPacket] @ binding.dart:86
[_onPointerData] @ pointer_binding.dart:83
(anonymous) @ pointer_binding.dart:334
(anonymous) @ pointer_binding.dart:183
Show 37 more frames
errors.dart:147 Uncaught (in promise) Error: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
    at Object.throw_ [as throw] (errors.dart:196)
    at MethodChannel.invokeMethod (platform_channel.dart:319)
    at invokeMethod.next (<anonymous>)
    at onValue (async_patch.dart:47)
    at _RootZone.runUnary (zone.dart:1381)
    at _FutureListener.thenAwait.handleValue (future_impl.dart:139)
    at handleValueCallback (future_impl.dart:680)
    at Function._propagateToListeners (future_impl.dart:709)
    at _Future.new.[_completeWithValue] (future_impl.dart:524)
    at async._AsyncCallbackEntry.new.callback (future_impl.dart:554)
    at Object._microtaskLoop (schedule_microtask.dart:43)
    at _startMicrotaskLoop (schedule_microtask.dart:52)
    at async_patch.dart:168

How to download ParseFile in flutter web?

**Comment by maaeps** [comment]
This has been added in #409.

**Comment by fischerscode** [comment]
I am now closing this. Feel free to reopen if there is still a problem.
