### ISSUE TITLE
installationId every time will change

### ISSUE THREAD

**Issue by KurdAppDev** [parse-community/Parse-SDK-Flutter#299]
Future<void> initData() async {
  await Parse().initialize(
      "appId", "serverUrl",
      debug: true, coreStore: await CoreStoreSharedPrefsImp.getInstance());

  final ParseResponse response = await Parse().healthCheck();

  if (response.success) {
    print("initData:success");
  } else {
    print("initData:fiald");
  }

  ParseInstallation.currentInstallation().then((onValue){
    print("installationId:"+onValue.installationId);

  });
}

**Comment by adrianaxente** [comment]
I confirm the same issue.

**Comment by shemhazai** [comment]
Hi @KurdAppDev, just a side note, today I was playing a bit with installations API and I would say that installationId was rather stable across app launches, etc. Of course it's generated upon first use so it didn't survive app reinstalls. The issue is getting quite old already, so I guess there was an update in between that could fix it. I suggest that you retest.

**Comment by Danaru87** [comment]
What version of parse-sdk-flutter are you using ?

I made a PR about similar problem about installationId: https://github.com/parse-community/Parse-SDK-Flutter/issues/373

Try with release/1.0.27 from github repo ;)

```yaml
 parse_server_sdk:
    git:
      url: https://github.com/parse-community/Parse-SDK-Flutter.git
      ref: release/1.0.27`

**Comment by fischerscode** [comment]
Can this be closed?

**Comment by tehsunnliu** [comment]
Hi, I'm having the same issue, I'm using ` parse_server_sdk: ^2.0.1`
Every time I call ParseInstallation.currentInstallation(), it returns a new installation.
I've initialized parse by calling 
`await Parse().initialize(appId, serverUrl);`

**Comment by tehsunnliu** [comment]
Okay, I just read the documentation again, and it says Parse by default uses "Non-persistent mode" and "Sdk will store everything in memory instead of using Sembast as an internal DB." 
So, I tried to use CoreStoreSembastImp.getInstance("/data"), however this throws Cannot create file exception.

**Comment by tehsunnliu** [comment]
For anybody else who is facing the same problem. 
I was able to fix it by using `path_provider` package.

```
Directory appDocDir = await getApplicationDocumentsDirectory();
      await Parse().initialize('appId',
          'serverUrl',
          coreStore:
              await CoreStoreSembastImp.getInstance(appDocDir.path + "/data"));
```

I think this should be updated in [https://pub.dev/packages/parse_server_sdk](here) as well.

Also in Android app/build.gradle
Add
```
dependencies {
   ...

    implementation 'androidx.multidex:multidex:2.0.1'
}
```
And 
```
    defaultConfig {
        ...

        multiDexEnabled true
    }
```

**Comment by fischerscode** [comment]
@tehsunnliu 
We are sorry for the breaking change.

> I'm using parse_server_sdk: ^2.0.1

The `parse_server_sdk` package is now a dart package. I would recommend you to use the [parse_server_sdk_flutter](https://pub.dev/packages/parse_server_sdk_flutter). The migration process is described [here](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/docs/migrate-2-0-0.md).

> I think this should be updated in https://pub.dev/packages/parse_server_sdk as well.

The `path_provider` is a pure flutter package. As a result of that, we have not been able to use it in the dart package. It is used in the [parse_server_sdk_flutter](https://pub.dev/packages/parse_server_sdk_flutter) package.

**Comment by tehsunnliu** [comment]
Oh, Thank you for your response. I just noticed in [https://pub.dev/packages/parse_server_sdk_flutter](parse_server_sdk_flutter) Readme->Get started section to add  `parse_server_sdk: ^2.0.1`, my bad I didn't see the installation section which says to install  `parse_server_sdk_flutter: ^2.0.1`.

**Comment by fischerscode** [comment]
Thanks for the 'Documentation-Bug-Report'.
I'll fix this.
