### ISSUE TITLE
parse_server_sdk >=1.0.25 is forbidden

### ISSUE THREAD

**Issue by usman18** [parse-community/Parse-SDK-Flutter#303]
This is what error I get after placing the parse_server_sdk  dependency in pubspec.yaml and giving a run:

```
The current Flutter SDK version is 1.9.1+hotfix.4.

Because parse_server_sdk >=1.0.25 depends on package_info >=0.4.0+13 which requires Flutter SDK version >=1.10.0 <2.0.0, parse_server_sdk >=1.0.25 is forbidden.
So, because voting_app_ui depends on parse_server_sdk ^1.0.25, version solving failed.


```

**Comment by maaeps** [comment]
@usman18 
I think you already solved it, but for others:

As written in the error, `The current Flutter SDK version is 1.9.1+hotfix.4.`.
And `parse_server_sdk [...] requires Flutter SDK version >=1.10.0`.

That means you have to upgrade your flutter sdk with:
`flutter upgrade`
