### ISSUE TITLE
No results from query when using only ClientKey

### ISSUE THREAD

**Issue by paulhulatt** [parse-community/Parse-SDK-Flutter#304]
Hi

I am rebuilding an existing app in Flutter which uses Parse on Back4App and have come up against an issue.

My existing native apps, initialise Parse with just the ClientKey and then any subsequent Parse operations respect the ACL.  However, whilst I can signup/login, if I have only specified the ClientKey I get no results for my queries.  Specifying MasterKey results in me receiving ALL records back regardless of the ACL.

The former is the expected result, and recommended practice for Parse so any reason why this is not working?

Help and advice greatly appreciated.

Kind Regards

Paul

**Comment by nicoco2** [comment]
I have also the problem that every request has an undefinded user, although im logged in and have an active session. This results in denied permissions for my ACL's.

**Comment by nicoco2** [comment]
Maybe you have to set in `Parse().initialize()` the value `autoSendSessionId: true`. This fixed my problem.

**Comment by fischerscode** [comment]
I am now closing this. Feel free to reopen if there is still a problem.
