### ISSUE TITLE
Copy an object

### ISSUE THREAD

**Issue by maaeps** [parse-community/Parse-SDK-Flutter#325]
As described on #267, I am trying to copy an ordinary ParseObject.
`object?.clone(object?.toJson(full: true));`

This throws an error for me:
`Unhandled Exception: type 'ParseACL' is not a subtype of type 'Map<String, dynamic>'`

This makes sens, as `_getObjectData()[keyVarAcl] = ParseACL().fromJson(value);` is called in parse_base.dart (line 139). With value being a ParseACL and fromJson taking a Map.

Am I just stupid or is there something wrong?

**Comment by maaeps** [comment]
@phillwiggins 
This is needed for the improvement mentioned in https://github.com/parse-community/Parse-SDK-Flutter/pull/324#issuecomment-596952160.

**Comment by maaeps** [comment]
Adding
`  if (value is ParseACL) {
    return value.toJson();
  }`
into `dynamic parseEncode(dynamic value, {bool full})` (parse_encoder.dart) fixes this.

I think this should break nothing.

**Comment by phillwiggins** [comment]
I think that sounds like a good idea.

Shall we add it and test?

**Comment by maaeps** [comment]
Sure, with the current livelist example, this change works fine.
And copying ParseObjects seems to work correct as well.

**Comment by maaeps** [comment]
Should be fixed with #326
