### ISSUE TITLE
ParseBase don't extend Equatable

### ISSUE THREAD

**Issue by Danaru87** [parse-community/Parse-SDK-Flutter#337]
Using parse_sdk with Bloc Pattern, i think ParseBase need to extends Equatable.

Without this, when yielding new states, in many situations new state is not yield because equality between currentState and newState is always true.

**Comment by maaeps** [comment]
Have you tried if extending Equatable results in issues?

As a dirty workaround you could always create a copy of your ParseObject.

**Comment by Danaru87** [comment]
> Have you tried if extending Equatable results in issues?
> 
Work in progress ;)

**Comment by phillwiggins** [comment]
I'm fairly against adding and libraries to a library as it means there's external dependencies to manage and in all honesty, I think this library is just a boiler player reducer. I currently use BLoC in my own projects but I've wrote my own version of this pattern so I don't require the above. However, I don't think it would be a breaking change to check equality between an object's properties rather than mem ref... Would.something like this suffice in Parse object?

 `@override
 bool operator ==(Object other) =>
  identical(this, other) ||
  other is ParseObject &&
  runtimeType == other.runtimeType &&
  *ITERATE THROUGH PARSE OBJECT JSON PROPERTIES HERE*;`

**Comment by Danaru87** [comment]
Sorry, I didn't have time to look into it.
I will try your solution, it seems sufficient for my need.

Thank you

**Comment by Danaru87** [comment]
I thinks using mixin EquatableMixin from Equatable will resolve my problem.

Thanks for your help

**Comment by Litesoulo** [comment]
Any updates on this issue? [phillwiggins](https://github.com/phillwiggins)

Missing a corresponding override of 'hashCode'.
Try overriding 'hashCode' or removing '=='.dart[hash_and_equals](https://dart.dev/diagnostics/hash_and_equals)

if I create hashCode method:
```dart
  @override
  int get hashCode => Object.hash(
        parseClassName,
        objectId,
        date,
        status,
      );
  ```

everythin works just fine!

```dart 
import 'package:parse_server_sdk/parse_server_sdk.dart';

void main() async {
  await Parse().initialize(
    "myAppId",
    "https://parseapi.back4app.com/",
    masterKey: "myMasterKey",
    debug: true,
  );

  final objectList = [
    Day()
      ..objectId = 'asdf1'
      ..date = DateTime(0),
    Day()..objectId = 'asdf2',
  ];

  print(objectList.contains(Day()
    ..objectId = 'asdf1'
    ..date = DateTime(0)));
}

class Day extends ParseObject implements ParseCloneable {
  Day() : super(_keyTableName);

  Day.clone() : this();

  @override
  Day clone(Map<String, dynamic> map) => Day.clone()..fromJson(map);

  static const String _keyTableName = 'FoodDiary_Day';
  static const String keyDate = 'Date';
  static const String keyOwner = 'Owner';
  static const String keyStatus = 'Status';

  DateTime? get date => get<DateTime>(keyDate);
  set date(DateTime? date) => set<DateTime>(keyDate, date!);

  int get status => get<int>(keyStatus) ?? 0;
  set status(int status) => set<int>(keyStatus, status);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Day &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          objectId == other.objectId &&
          status == other.status;

  @override
  int get hashCode => Object.hash(
        parseClassName,
        objectId,
        date,
        status,
      );
}
```

just leaving this example here for others who might look at this issue, thank you!

**Comment by mtrezza** [comment]
Is this an open issue? The state is currently closed, but otherwise we'll re-open.
