### ISSUE TITLE
Relational Query Question

### ISSUE THREAD

**Issue by xabre** [parse-community/Parse-SDK-Flutter#338]
I have just started working on a side project using flutter and parse. I'm really enjoying the development experience until now. 
I have unfortunately run in a bit of a bump on the road when creating relational queries.

Let's take the example from the documentation that has a series of Posts and Comments. Each comment has a pointer to its parent post. Each comment has a pointer to a ParseUser (the author of the comment).

I would like to find all posts where User 'X' did **not** comment at all.

Is there a way of expressing this query with the current sdk?

Edit: looking at other parse sdks something like **doesNotMatchKeyInQuery** would solve this query.

**Comment by maaeps** [comment]
@xabre 
I have not used them jet, but have you tried this functions?
```
whereMatchesQuery
whereDoesNotMatchQuery
```

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
