### ISSUE TITLE
Exception: FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by hamidabdulmalik** [parse-community/Parse-SDK-Flutter#344]
Any help please? 
![ERROR](https://user-images.githubusercontent.com/340532/77864382-80992580-7228-11ea-8a4e-6ba895badd75.png)

**Comment by hamidabdulmalik** [comment]
I figured it out, my bad.

**Comment by thphuc** [comment]
@hamidabdulmalik Can you share how you fixed it?

**Comment by maaeps** [comment]
@thphuc I had such an error as well. For me it has been a miss-configuration/bug at my reverse proxy.
You may want to use the REST API in order to find a server side problem.
