### ISSUE TITLE
Geting user data from pointer .

### ISSUE THREAD

**Issue by srkraut** [parse-community/Parse-SDK-Flutter#345]
hello , i am using ParseLiveListWidget in list view and it is working good . i am listing out posts in list , i want to view username and email in post using the user pointer i am receiving in the snapshot . 

but i am unable to receive it , 
pointer i am receiving is 

` snapshot.loadedData.get<ParseUser>('poster'),`

how to retrive name , email and other data of user in livelist . any solution ?

**Comment by maaeps** [comment]
@srkraut 
Have you tried to add `.includeObject('poster')` to your QueryBuilder?

**Comment by srkraut** [comment]
@maaeps this worked thanks a lot .

**Comment by maaeps** [comment]
@srkraut 
Glad to hear that.

(If everything is clear, please close the issue. 😃 )

**Comment by srkraut** [comment]
Thanks .
