### ISSUE TITLE
Using Include in live list breaks 

### ISSUE THREAD

**Issue by srkraut** [parse-community/Parse-SDK-Flutter#347]
Hello i am using query builder and live list to show data 

`_queryBuilder = QueryBuilder<ParseObject>(ParseObject('post'))
 ..includeObject(["poster"])
 ..orderByDescending('createdAt');`

it woks fine at start but when new data is added and the data used from 'poster' pointer can't be shown and throws null exception . i am trying to show user name .

`snapshot.loadedData
 .get('poster')
 .get('full_name')`

**Comment by maaeps** [comment]
I  think this problem occurs as LiveList is build on top of LiveQuery and LiveQuery does not 
handle included objects (as far as I know).

As a quick work around you could re-fetch the included object manually.

I agree that such a workaround is not ideal and  as this feature would come handy in more complex apps, I will have a lock, if implementing an automated process is possible.

**Comment by srkraut** [comment]
Can you pass me an example . How can i refetch the included object inside livelist ?

Or refresh the livelist manually running full query again 

Currently i am refreshing whole page , disable the live query and using livelist just for showing list . 

Any optimization and code suggestions are welcome.

**Comment by maaeps** [comment]
You could wrap the widget, that uses the poster object inside a FutureBuilder using this future:
`snapshot.loadedData
                        .get<ParseObject>('poster')
                        .update()`

**Comment by srkraut** [comment]
but its kind of slow and when scrolling vales goes and comes .

**Comment by maaeps** [comment]
@srkraut 
I implemented a possible solution in https://github.com/parse-community/Parse-SDK-Flutter/pull/348/commits/dd837d190ad4b880ca9317eea480d0f1ba39a917 and https://github.com/parse-community/Parse-SDK-Flutter/pull/348/commits/8d4a4aff902401a044219a72438f051ec838aa3b.

More improvements can be made, but this should fix your including problem.
For further information have a lock at #348.

**Comment by srkraut** [comment]
great it works , i am having problem to use livelist inside scroll view or customscrollview widget , i want to make full page scrollable which contains many widgets along with this list

**Comment by MungaraJay** [comment]
Hello @srkraut @maaeps @phillwiggins 

I am facing similar kind of error for livequeries with includeObject not working.

So can you check the following issue and let me know how can i use livequeries with includeobject.
https://github.com/parse-community/Parse-SDK-Flutter/issues/424
