### ISSUE TITLE
Replace isTypeOfException with actual Exception

### ISSUE THREAD

**Issue by BaranMichal25** [parse-community/Parse-SDK-Flutter#351]
Currently there is no way to tell whether there was a connection problem during call to Parse - whether `SocketException` or other exception was thrown, because this information is scraped [here](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/lib/src/objects/response/parse_exception_response.dart#L7), replaced with `isTypeOfException` and then mapped to `-1: 'UnknownError'`.

I would like to propose replacing `isTypeOfException` with the `Exception` itself, because it will be optionally providing more information than it is right now.

This is a small, but somewhat breaking change, so I wanted to open issue first and get your approval. 
If you're happy with the change, I will open the MR :)

I actually did it some time ago on my fork of the project (please ignore removal of `toString()`), so you can see how the change would look:
https://github.com/BaranMichal25/Parse-SDK-Flutter/commit/01cba669925da613507eb6983679dc9a0e303b5f
We would prefer to use original library instead of my "private" fork, because it's a project for client, hence my proposal.

**Comment by phillwiggins** [comment]
Hey Baran

I actually like the idea and completely agree with it. Are you able to create a merge request with that branch, into branch labelled 'release/1.0.27' of this repository?

**Comment by BaranMichal25** [comment]
Thanks, done here: https://github.com/parse-community/Parse-SDK-Flutter/pull/355
