### ISSUE TITLE
About image upload

### ISSUE THREAD

**Issue by Loudsa** [parse-community/Parse-SDK-Flutter#354]
When I upload pictures, if I upload a .jpg file, I can upload it successfully. But if you upload a .png format file, the upload will fail

### **The error reported by uploading png is as follows：**

`11:37:51.292 2 info flutter.tools I/flutter ( 4198): curl -X POST -H 'content-type: application/octet-stream' -H 'user-agent: Flutter Parse SDK 1.0.24' -H 'X-Parse-Application-Id: kahoShiftDuty' -H 'X-Parse-Client-Key: 73500f45dac7179cc0f977e17d48e82b' -d 'PNG
11:37:51.292 3 info flutter.tools I/flutter ( 4198): 
11:37:51.292 4 info flutter.tools I/flutter ( 4198): ╰--
11:37:51.340 5 info flutter.tools I/flutter ( 4198): ╭-- Parse Response
11:37:51.340 6 info flutter.tools I/flutter ( 4198): Class: null
11:37:51.340 7 info flutter.tools I/flutter ( 4198): Function: ParseApiRQ.upload
11:37:51.340 8 info flutter.tools I/flutter ( 4198): Status Code: 122
11:37:51.340 9 info flutter.tools I/flutter ( 4198): Type: InvalidFileName
11:37:51.340 10 info flutter.tools I/flutter ( 4198): Error: Filename contains invalid characters.
11:37:51.341 11 info flutter.tools I/flutter ( 4198): ╰-- 
11:37:51.341 12 info flutter.tools I/flutter ( 4198):  
11:37:51.341 13 info flutter.tools I/flutter ( 4198): Uploaded failed:  
11:37:51.341 14 info flutter.tools I/flutter ( 4198): ----
11:37:51.341 15 info flutter.tools I/flutter ( 4198): ParseException (Type: InvalidFileName) :
11:37:51.341 16 info flutter.tools I/flutter ( 4198): Code: 122
11:37:51.341 17 info flutter.tools I/flutter ( 4198): Message: Filename contains invalid characters.----
`

### **If you use jpg：**

`11:40:20.593 2 info flutter.tools I/flutter ( 4198): curl -X POST -H 'content-type: application/octet-stream' -H 'user-agent: Flutter Parse SDK 1.0.24' -H 'X-Parse-Application-Id: kahoShiftDuty' -H 'X-Parse-Client-Key: 73500f45dac7179cc0f977e17d48e82b' -d 'ÿØÿà
11:40:20.593 3 info flutter.tools I/flutter ( 4198): ╰--
11:40:20.684 4 info flutter.tools I/flutter ( 4198): ╭-- Parse Response
11:40:20.684 5 info flutter.tools I/flutter ( 4198): Class: null
11:40:20.684 6 info flutter.tools I/flutter ( 4198): Function: ParseApiRQ.upload
11:40:20.684 7 info flutter.tools I/flutter ( 4198): Status Code: 201
11:40:20.684 8 info flutter.tools I/flutter ( 4198): Reponse: OK
11:40:20.684 9 info flutter.tools I/flutter ( 4198): ╰-- 
11:40:20.684 10 info flutter.tools I/flutter ( 4198):  
11:40:20.684 11 info flutter.tools I/flutter ( 4198): https://kahoshiftduty.uat.macau520.com:8443/api/classes/TestObjectFile
11:40:20.689 12 info flutter.tools I/flutter ( 4198): ╭-- 解析請求
11:40:20.689 13 info flutter.tools I/flutter ( 4198): curl -X POST -H 'content-type: text/plain; charset=utf-8' -H 'user-agent: Flutter Parse SDK 1.0.24' -H 'X-Parse-Application-Id: kahoShiftDuty' -H 'X-Parse-Client-Key: 73500f45dac7179cc0f977e17d48e82b' -d '{"fileImage":[{"url":{"__type":"File","name":"66d11b48cd11acd82ae04dc6bb8026ef_Screenshot_20200413-093531.jpg","url":""}}]}' 
11:40:20.689 14 info flutter.tools I/flutter ( 4198): 
11:40:20.689 15 info flutter.tools I/flutter ( 4198):  
11:40:20.690 16 info flutter.tools I/flutter ( 4198): ╰--
11:40:20.730 17 info flutter.tools I/flutter ( 4198): ╭-- Parse Response
11:40:20.730 18 info flutter.tools I/flutter ( 4198): Class: TestObjectFile
11:40:20.730 19 info flutter.tools I/flutter ( 4198): Function: ParseApiRQ.create
11:40:20.730 20 info flutter.tools I/flutter ( 4198): Status Code: 201
11:40:20.730 21 info flutter.tools I/flutter ( 4198): Payload: {"className":"TestObjectFile","objectId":"VVeCbUj95Q","createdAt":"2020-04-13T03:40:20.704Z","fileImage":[{"url":{"__type":"File","name":"66d11b48cd11acd82ae04dc6bb8026ef_Screenshot_20200413-093531.jpg","url":""}}]}
11:40:20.730 22 info flutter.tools I/flutter ( 4198): ╰-- 
11:40:20.730 23 info flutter.tools I/flutter ( 4198):  
11:40:20.730 24 info flutter.tools I/flutter ( 4198): Uploaded successfully
`

### **My code is like this**

Future<void> uploadImg()async{
    File image = await ImagePicker.pickImage(source: ImageSource.gallery);
    ParseFile parseFile = ParseFile(image, name: "image.png", debug: true);

    var parseObject = ParseObject("TestObjectFile", debug: true);
    parseObject.set("fileImage",[{"url":parseFile}] );
    var apiResponse = await parseObject.save();

    if (apiResponse.success) {
      print('Uploaded successfully');
    } else {
      print("Uploaded failed: " + apiResponse.error.toString());
    }
  }

Sorry, I have re-edited this code several times, and some of them are outside

**Comment by GursheeshSingh** [comment]
You can try assigning a custom random name (Can use UUID Package for that).

**Comment by Loudsa** [comment]
> 您可以嘗試分配自定義隨機名稱（可以使用UUID軟件包）。

Thank you for your answer, but it seems that my problem has been solved by myself, I will use png upload later and found that it will not report an error

**Comment by Loudsa** [comment]
> You can try assigning a custom random name (Can use UUID Package for that).

Thank you for your answer, but it seems that my problem has been solved by myself, I will use png upload later and found that it will not report an error
