### ISSUE TITLE
Hi guys i have a question，Can you help me answer

### ISSUE THREAD

**Issue by InTheClodus** [parse-community/Parse-SDK-Flutter#358]
I now have three tables, one user, one student, one member,

user has a Pointer object pointing to student, and student also has a pointer to member ’s Pointer,
So how can I includeObject studen while querying the user table and also include the member in Object student

**Comment by MungaraJay** [comment]
Hello @InTheClodus 

Did you able to manage this incluede query.

Is this feature supported?

Just let me know.

Thanks.

**Comment by InTheClodus** [comment]
> Hello @InTheClodus
> 
> Did you able to manage this incluede query.
> 
> Is this feature supported?
> 
> Just let me know.
> 
> Thanks.

```dart
queryBuilder.includeObject("user,user.student")
```
Sorry, just saw
