### ISSUE TITLE
when it available parse's original push notification?.

### ISSUE THREAD

**Issue by akhilprogrammer** [parse-community/Parse-SDK-Flutter#360]
i saw someone said using firebase push notification.why we cant include parse own push notification serviece?????. i am new to parse platform, advance sorry if i have lack of knwoledege!!!.
if parse have its own push notification serviece then when it available in flutter sdk. Also thank you for all programmers who work hard to  make parse platform easy in flutter

**Comment by pastordee** [comment]
> i saw someone said using firebase push notification.why we cant include parse own push notification serviece?????. i am new to parse platform, advance sorry if i have lack of knwoledege!!!.
> if parse have its own push notification serviece then when it available in flutter sdk. Also thank you for all programmers who work hard to make parse platform easy in flutter

The thank you part.

**Comment by GursheeshSingh** [comment]
Parse notification uses Firebase Messaging.

**Comment by MungaraJay** [comment]
Hello @phillwiggins @GursheeshSingh 

Is there any updates related to push notifications with parse sdk in flutter?

Can we implement push notifications using parse server sdk for flutter as well?

Waiting for reply.

Thanks.

**Comment by phillwiggins** [comment]
Sorry, I've not looked into this as of yet.

**Comment by GursheeshSingh** [comment]
I made an app which uses Push Notifications

You can directly use Firebase for that

Your login for sending notifications should be on a server, use can use CloudFunctions, Lambda or make your own server.

All you need to do on your app is to handle the push notifications clicks.

**Comment by RodrigoSMarques** [comment]
@MungaraJay 
To use the native functionality it is necessary to use Platform Channel and I do not see the need.
Use Firebase Cloud Messaging that has the plugin ready and does the same.
Retrieve the Token from the device with FCM, save the token in Class Installation on Parse.
Send Push Notification through Parse and receive it on the device through FCM.

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.

**Comment by pitanni** [comment]
> @MungaraJay
> To use the native functionality it is necessary to use Platform Channel and I do not see the need.
> Use Firebase Cloud Messaging that has the plugin ready and does the same.
> Retrieve the Token from the device with FCM, save the token in Class Installation on Parse.
> Send Push Notification through Parse and receive it on the device through FCM.

Hi @RodrigoSMarques,
is there an example of something already implemented? I can send notifications directly from FCM, but not from the Parse Dashboard. I can successfully create the Installation class and see the installations from the Dashboard.

Thank you

**Comment by RodrigoSMarques** [comment]
@pitanni 
I have a project. I will try to prepare an example just demonstrating the notification.

I'll comment here again later.

**Comment by pitanni** [comment]
@RodrigoSMarques 
is there any update?
Thanks
