### ISSUE TITLE
Double as int from cloud code

### ISSUE THREAD

**Issue by alexnaldo** [parse-community/Parse-SDK-Flutter#361]
Guys,

I have a cloud code that returns data from a table, very simple. The table have 1 field of type "number".

1) If the field value is 123, the client get<T> of ParseObject returns as int
2) If the field value is 123.45, the client get<T> of ParseObject returns as double

My class model is:
  double get salary =>  parseObject.get<double>('salary');

Problem: When the field value is 123 (int) show exception.

Any idea to solve it?

**Comment by RodrigoSMarques** [comment]
Hi @alexnaldo 

Try:

```dart
double get salary => parseObject.get('salary').toDouble();
```

**Comment by alexnaldo** [comment]
worked! easy and good....thanks!
