### ISSUE TITLE
Parse user updated on server but not locally

### ISSUE THREAD

**Issue by GursheeshSingh** [parse-community/Parse-SDK-Flutter#364]
I think this a strange behaviour in ParseUser

```
ParseUser currentUser = await ParseUser.currentUser();
currentUser.set("turnOnNotifications", newValue);
var response = await currentUser.update();
if (response.success) {
    ParseUser currentUser = await ParseUser.currentUser();
    currentUser.get("turnOnNotifications");
    return;
}
```

Here when I change the value of current user and update it. It successfully updates the value to the sever and the response also gives the updated value

But when I access it again, it is still unchanged, I think the update only happens on the server and not locally.

This is quite frustrating as it causes a lot of bugs and does not help in the program flow.

**Comment by maaeps** [comment]
Seems like this is related to #256

**Comment by GursheeshSingh** [comment]
Yes I think so.

The user is logged in already and it successfully gets updated on the server. But not locally, it seems like a SDK issue.

**Comment by maaeps** [comment]
I've done some testing, too.
Before copying your sample code, I used `.save()` to save the, everything worked as expected.
Then I changed `.save()` to `.update()`, this resulted in the same problems as described you.
By logging out and back in the user object  was updated.

I think by calling update, the SDK saves changes successfully but does not write the UserObject to the CoreStore properly.

I will try to fix this tomorrow.

**Comment by GursheeshSingh** [comment]
Does the .save() work for you?

.save() and .update() don't update the local storage for me.

**Comment by maaeps** [comment]
For me `.save()`works just fine.
Which corestore are you using?

**Comment by GursheeshSingh** [comment]
Seems like its working with save() and not update().
I am using Shared Preferences

Can we use Flutter Secure storage?

**Comment by GursheeshSingh** [comment]
Does save() work the same if I make some changes and save it?

**Comment by maaeps** [comment]
I am actually not quite sure what `.update()` does.
`.save()` should just save your changes to the server.
Have you tried the changes merged with #368?

**Comment by GursheeshSingh** [comment]
I will try them out and let you know.

**Comment by GursheeshSingh** [comment]
How do I specifically use this version pull request in pubspec.yaml?

**Comment by phillwiggins** [comment]
Something like this do you mean?

`parse_server_sdk:
    git:
      url: git://github.com/phillwiggins/flutter_parse_sdk.git
      ref: release/1.0.26`

**Comment by GursheeshSingh** [comment]
Thank you.
```

  parse_server_sdk:
    git:
      url: git://github.com/parse-community/Parse-SDK-Flutter.git
      ref: release/1.0.27
```

I check the update() function and it works now.

I think that if we have some tests, we could have avoid suck a bug.

I can definitely contribute some tests.

**Comment by phillwiggins** [comment]
I would 💯 appreciate a few tests! We should have done TDD but it only
started as a 'play project'. I've not had time to wrap it in tests myself.

**Comment by GursheeshSingh** [comment]
I will be working with tests in my flutter applications and will add some tests as I get more familiar with them.

**Comment by Faisalbutt555** [comment]
> ParseUser currentUser = await ParseUser.currentUser();
> currentUser.set("turnOnNotifications", newValue);
> var response = await currentUser.update();
> if (response.success) {
>     ParseUser currentUser = await ParseUser.currentUser();
>     currentUser.get("turnOnNotifications");
>     return;
> }

it hep for me thanks
