### ISSUE TITLE
Relational Query Include Objects

### ISSUE THREAD

**Issue by ChineOnw** [parse-community/Parse-SDK-Flutter#365]
Hey everybody,

when will it be available to include related objects within one query. As it is metioned on the REST documentation here: [REST-API](https://docs.parseplatform.org/rest/guide/#relational-queries)

> In some situations, you want to return multiple types of related objects in one query. You can do this by passing the field to include in the include parameter. For example, let’s say you are retrieving the last ten comments, and you want to retrieve their related posts at the same time:

**Comment by RodrigoSMarques** [comment]
Hi @ChineOnw 

I verified that it is not in the documentation, but the option exists.
Use the * includeObject * operator

```dart
      final QueryBuilder queryBuilder =
          QueryBuilder<ParseObject>(ParseObject('product'))
            ..orderByAscending('name');
      queryBuilder.includeObject(['category']);
```
