### ISSUE TITLE
If the network request response is slow, the parse client will cause the app to get stuck.

### ISSUE THREAD

**Issue by zakiso** [parse-community/Parse-SDK-Flutter#369]
If the network request response is slow, the parse client will cause the app to get stuck.

Although our method is async, as long as the network request response time is slightly longer, it will cause the entire app to get stuck.
Can I use a separate isolate when sending HTTP requests?

**Comment by phillwiggins** [comment]
How do you mean isloate? We did allow injections of the HTTP Client, that
would allow custom time-outs if that's what your looking for?

**Comment by zakiso** [comment]
I analyzed the problem that is not our flutter parse sdk. It's a problem with dart's http library.

https://github.com/dart-lang/sdk/issues/41519

**Comment by phillwiggins** [comment]
Shall we mark this as closed in that case? Seems like a Flutter issue Vs
Parse Flutter SDK issue?
