### ISSUE TITLE
Does it support Flutter Web?

### ISSUE THREAD

**Issue by d-apps** [parse-community/Parse-SDK-Flutter#370]
Does it support Flutter Web? I couldn't see "WEB" compatibility in pub.dev.

**Comment by maaeps** [comment]
I am able to run my application on web.
Just make sure you are using `CoreStoreSharedPrefsImp` and not `CoreStoreSembastImp`. As `CoreStoreSembastImp` does not support web, as far as I know.

If your app won't connect to the server, you have probably a 'CORS' problem.

**Comment by gorillatapstudio** [comment]
@maaeps  do you have the error of "boolean expression must not be null" in the latest sdk version when calling user.signup()?

**Comment by maaeps** [comment]
@gorillatapstudio 
I am not using user.singUp() and I am using the not released version 1.27.
Is this related to #271?

**Comment by gorillatapstudio** [comment]
yes it is. thanks!

**Comment by maaeps** [comment]
It seems like the SDK supports web only partially.
The issue for implementing full web support is #385.

**Comment by fischerscode** [comment]
I am closing this now, as with the release of 1.0.28, web should be fully supported.
