### ISSUE TITLE
Chat screen package for Flutter

### ISSUE THREAD

**Issue by GursheeshSingh** [parse-community/Parse-SDK-Flutter#372]
Hey!

So this is not an issue.
Actually I have been working on a chat application and I have added it as a package and in just 5 - 6 lines. 

You can add a simple chat application.

https://pub.dev/packages/chatscreen

It has some basic features.
If you have some ideas, you can contribute.
I will updating it soon.

**Comment by maaeps** [comment]
Great job!
For a quick Chat App project, this might come very handy.

Three ideas:
1. add an end-to-end encryption
   Especially if you use firestore this might be an interesting feature.
2. change the message boarders
    This is objective but I would prefer chat bubbles like [this](https://pub.dev/packages/bubble).
3. add an example app

**Comment by GursheeshSingh** [comment]
Thank you for the suggestions, I try them out.

**Comment by GursheeshSingh** [comment]
Can we add it to README.md?
