### ISSUE TITLE
using OR operator in a query 

### ISSUE THREAD

**Issue by alparslantopbas** [parse-community/Parse-SDK-Flutter#374]
Is there an example for '..whereEquals clause' in a query? I want to use two attributes in a query and want to use 'OR' operator. How can I use this kind of query?

**Comment by maaeps** [comment]
You can use `QueryBuilder.or()` to combine two queries with an OR.

**Comment by alparslantopbas** [comment]
Thank you for your answer, but is there any examples, I haven't found it yet.

**Comment by maaeps** [comment]
I think there is no example in the Readme.
You can use the OR constructor like this:
```
    ParseObject parseObject = ParseObject("testClass");
    QueryBuilder<ParseObject> queryBuilder1 =
        QueryBuilder<ParseObject>(parseObject)..whereEqualTo("column1", 1);
    QueryBuilder<ParseObject> queryBuilder2 =
        QueryBuilder<ParseObject>(parseObject)..whereEqualTo("column2", 1);
    QueryBuilder<ParseObject> queryBuilder3 =
        QueryBuilder<ParseObject>(parseObject)
          ..whereEqualTo("column3", 1)
          ..whereEqualTo("column3_2", 2);
    QueryBuilder<ParseObject> orQuery = QueryBuilder.or(
      parseObject,
      [queryBuilder1, queryBuilder2, queryBuilder3],
    );
```

`orQuery` should return all objects where `column1 == 1 OR column2 == 1 OR (column3 == 1 AND column3_2 == 2)`

This `orQuery` should behave like a normal queryBuilder.

Let me know if you have any more questions.

**Comment by alparslantopbas** [comment]
a very descriptive answer, thank you very much.
