### ISSUE TITLE
How to cast html.File to File in Flutter and Parse integration

### ISSUE THREAD

**Issue by kethees** [parse-community/Parse-SDK-Flutter#377]
Please guide me to cast html.File which from `import 'dart:html' as html;` to File which is from `import 'dart:io';`

Following is the code that I have rewritten to upload image to parse server and I am getting following error.
`errors.dart:167 Uncaught (in promise) Error: Expected a value of type 'File', but got one of type 'File$'`

```
Future<void>uploodProfileImage() async {
    html.File imageFile = await ImagePickerWeb.getImage(outputType: ImageType.file);

    if (imageFile != null) {
      debugPrint(imageFile.name.toString());
      File file = imageFile as File;
      ParseFile parseFile = ParseFile(file, name: imageFile.name.toString(), debug: true);
      var response = await parseFile.save();
      if (response.success) {
        parseFile = response.result as ParseFile;
        print(parseFile.toString());
        print("success");
      } else {
        print("Error");
        return;
      }
    }
  }
```

**Comment by fischerscode** [comment]
We introduced `ParseWebFile` to handle files on web. [This](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/flutter#file) might help you.

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
