### ISSUE TITLE
addAscendingOrder and addDescendingOrder are missing in the SDK

### ISSUE THREAD

**Issue by gorillatapstudio** [parse-community/Parse-SDK-Flutter#378]
My query very much depends on several sorting keys. Are they really missing in SDK or are they implemented in some other way?

**Comment by maaeps** [comment]
I think you are searching `orderByAscending()` and `orderByDescending()`.

**Comment by gorillatapstudio** [comment]
Thanks for reply!
OrderByAscending is in the SDK, but you want to first sort by username and then sort by createdAt, you will need to use addAscendingOrder together with orderByAscending. It's available in parse sdk for ios and android but seemed to missing here.

**Comment by maaeps** [comment]
I have not tested this, but think you can chain `orderByAscending()` and `orderByDescending()`.
```
queryBuilder.orderByAscending("username");
queryBuilder.orderByAscending("createdAt");
```
As far as I know, `orderByAscending()` adds an ascending order. The name is just different.

**Comment by gorillatapstudio** [comment]
oh yes, that totally works. thanks!
