### ISSUE TITLE
 Add a global custom header to http request.

### ISSUE THREAD

**Issue by zakiso** [parse-community/Parse-SDK-Flutter#380]
I saw that parseHttpClient code. 
If I want to add custom header, I must extend ParseHttpClient. So I must pass a custom client to every parse object. I want add a global scope header. Can we add a header store in ParseCoreData？

![image](https://user-images.githubusercontent.com/5389326/82360624-3c621e80-9a3c-11ea-93d5-a09597758d97.png)

```
  additionalHeaders = parseCoreData.additionalHeaders
   if (additionalHeaders != null && additionalHeaders.isNotEmpty) {
      additionalHeaders
          .forEach((String key, String value) => request.headers[key] = value);
    }
```

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
