### ISSUE TITLE
Delete object :  XMLHttpRequest error

### ISSUE THREAD

**Issue by jeansebastienZ** [parse-community/Parse-SDK-Flutter#383]
Hello, i'm using 

> parse_server_sdk:  1.0.26

When i try to delete an object i get this message : 

> Class: Categories
> Function: ParseApiRQ.delete
> Status Code: -1
> Type: UnknownError
> Exception: XMLHttpRequest error.

All other request work normally , do someone can tell me if he get an idea where the problem come from ?
I tried a request of deleting via postman it worked well .

**Comment by fischerscode** [comment]
@jeansebastienZ 
Have you solved the issue? Are we safe to close?

**Comment by jeansebastienZ** [comment]
Hello , yes  we can close. It was from back4app server side . Thanks you
