### ISSUE TITLE
ParseRelation 

### ISSUE THREAD

**Issue by LavTeamProject** [parse-community/Parse-SDK-Flutter#399]
version: "1.0.26"

1. I added a column "Rela" (Relations to table Test1)
<img width="785" alt="Снимок экрана 2020-07-04 в 23 08 38" src="https://user-images.githubusercontent.com/41138925/86520361-03df9e00-be4c-11ea-9525-1a616ceb1338.png">

2. dietPlan.addRelation('rela', [ParseObject("Test1")..set("objectId", "BHfYX9IibU")]);

<img width="997" alt="Снимок экрана 2020-07-04 в 23 08 52" src="https://user-images.githubusercontent.com/41138925/86520391-50c37480-be4c-11ea-8809-789f0e6593bf.png">

3. Now I want to get this object:
                  final ParseRelation<ParseObject> rela = dietPlan.rela;
                  var test = rela.getQuery();
                  var apiResponse = test.query().then((value) {
                    print(value.result);
                    //console log:
                    //[{"className":"Test1","objectId":"BHfYX9IibU","createdAt":"2020-06-27T08:05:28.397Z","updatedAt":"2020-07-04T19:40:25.045Z","title":"test1","testPF":{"__type":"Pointer","className":"Test2","objectId":"r5iLCHPMiS"},"title2":"123","title3":"123","testRL":{"__type":"Relation","className":null,"objects":null}}, {"className":"Test1","objectId":"3nIgR8jZsB","createdAt":"2020-06-27T08:56:40.729Z","updatedAt":"2020-06-27T09:29:50.750Z","title":"test2","testPF":{"__type":"Pointer","className":"Test2","objectId":"0RhHh8OXFB"},"title2":"4","title3":"1","testRL":{"__type":"Relation","className":null,"objects":null}}, {"className":"Test1","objectId":"Lu0sO0hwoO","createdAt":"2020-06-27T09:30:23.293Z","updatedAt":"2020-06-27T09:30:23.293Z","title":"test3","testPF":{"__type":"Pointer","className":"Test2","objectId":"KIZ0y1ZG5j"},"title2":"4","title3":"1","testRL":{"__type":"Relation","className":null,"objects":null}}]
                  });

Expected Result:
Got one BHfYX9IibU object

Actual result:
All objects of table Test1 are received.
/[{"className":"Test1","objectId":"BHfYX9IibU","createdAt":"2020-06-27T08:05:28.397Z","updatedAt":"2020-07-04T19:40:25.045Z","title":"test1","testPF":{"__type":"Pointer","className":"Test2","objectId":"r5iLCHPMiS"},"title2":"123","title3":"123","testRL":{"__type":"Relation","className":null,"objects":null}}, {"className":"Test1","objectId":"3nIgR8jZsB","createdAt":"2020-06-27T08:56:40.729Z","updatedAt":"2020-06-27T09:29:50.750Z","title":"test2","testPF":{"__type":"Pointer","className":"Test2","objectId":"0RhHh8OXFB"},"title2":"4","title3":"1","testRL":{"__type":"Relation","className":null,"objects":null}}, {"className":"Test1","objectId":"Lu0sO0hwoO","createdAt":"2020-06-27T09:30:23.293Z","updatedAt":"2020-06-27T09:30:23.293Z","title":"test3","testPF":{"__type":"Pointer","className":"Test2","objectId":"KIZ0y1ZG5j"},"title2":"4","title3":"1","testRL":{"__type":"Relation","className":null,"objects":null}}]

<img width="1015" alt="Снимок экрана 2020-07-04 в 23 09 02" src="https://user-images.githubusercontent.com/41138925/86520435-e959f480-be4c-11ea-99c9-6f77b9a8846b.png">

iOS-sdk - no this error

**Comment by LavTeamProject** [comment]
please, help me

**Comment by ZeroNilZero** [comment]
@LavTeamProject any update?

**Comment by LavTeamProject** [comment]
> @LavTeamProject any update?

No.
Temporary solution:
Using cloud code, I get the necessary records.

Sorry my English

**Comment by ZeroNilZero** [comment]
Base on rest api
```
    QueryBuilder<ParseObject> query = QueryBuilder<User>(User(null, null, null))..whereRelatedTo('relationUserList', '_User', currentUser.objectId);
    var res = await query.query().then((value) {
      print(value.success);
 
      print(value.results.length);
    });
```
where **`relationUserList`** is a relational pointer to _User class And `User` is custom ParseUser object.

Hope this help.

**Comment by LavTeamProject** [comment]
> Base on rest api
> 
> ```
>     QueryBuilder<ParseObject> query = QueryBuilder<User>(User(null, null, null))..whereRelatedTo('relationUserList', '_User', currentUser.objectId);
>     var res = await query.query().then((value) {
>       print(value.success);
>  
>       print(value.results.length);
>     });
> ```
> 
> where **`relationUserList`** is a relational pointer to _User class And `User` is custom ParseUser object.
> 
> Hope this help.

Thank you!
