### ISSUE TITLE
loginWith firebase adapter

### ISSUE THREAD

**Issue by apoleo88** [parse-community/Parse-SDK-Flutter#401]
Hey Guys!

I had some problems to implement the login with parse server in flutter from external authentication and I opted to use firebase authentication and then create a user with its token.

I am using Parse Server with Express and I am trying to integrate a firebase login adapter.
Since I don't know any better I installed the adapter: `parse-server-firebase-auth-adapter`
with `npm i -S parse-server-firebase-auth-adapter`

I set in the express app.js -> in ParseServer({...})
```
  "auth" : {
       "firebase" : {
           "module" : "parse-server-firebase-auth-adapter",
           "databaseURL" : "https://MY.firebaseio.com",
           "credential" : "./serviceAccountKey.json",
       }
  },
```
I put the serviceAccountKey.json file from firebase in the main same folder.

In flutter, after the login is done correctly with firebase I want to create the user on my Parse Server:
```
    final ParseResponse response = await ParseUser.loginWith(
        'firebase',
        {
            "access_token": (await firebaseToken).token,
            "id": firebaseUid
        }
    );
```

the response is confusing since it is a parse response with success false, and no error
```
I/flutter ( 8779): ParseException (Type: No Results) :
I/flutter ( 8779): Code: 1
I/flutter ( 8779): Message: null----
```

Not sure what it means, it is trying to login an already existing user but since it is new it doesn't find one?
I thought that I should use instead `linkWith` on a new user but there is no implementation of it?

Thanks for any advice!

**Comment by phillwiggins** [comment]
Hey

That is a strange response. If the server is set correctly, I believe it
should return an error that states the user already has an account but it
looks like the SDK is having trouble parsing the response. Have you tried a
deep dive debug and debug the Parse SDK code to see what the actual server
is returning?

**Comment by apoleo88** [comment]
From the server-side? I don't know how to do that, yet!
Can you point me to some documentation to start?

Instead from the client-side, there is not much information from the response

**Comment by apoleo88** [comment]
I stand incorrect if I see what _loginWith is doing underneath the response is get is a 500, internal server error.

**Comment by phillwiggins** [comment]
Apologies, yes I did mean debug client side, but debug the library to check
the actual response.

**Comment by apoleo88** [comment]
In the server log I can only read "Uncaught internal server error", there is a way to get more info about the error?

**Comment by apoleo88** [comment]
The timezone of the server is 2h wrong, but it shouldn't be an issue, right?

**Comment by apoleo88** [comment]
found the error, not sure when but it installed `firebase-admin`
and my `app.js` had:
```
var admin = require("firebase-admin");
admin.initializeApp({...
```

That apparently triggered some conflict. Unfortunately the debug error was not mysterious until the end.
