### ISSUE TITLE
Inserting multiple objects at once

### ISSUE THREAD

**Issue by Atteprojects** [parse-community/Parse-SDK-Flutter#403]
I am using the flutter parse server SDK and I was wondering if there is a way to add multiple objects at once without using for each or for loop with async. I tried the for loops and it is not working like I wanted it to because of all the async behavior and I also did not want to do multiple requests to the server for each object.

**Comment by phillwiggins** [comment]
Duplicate question as #359. It's not support yet but I will mark as enhancement. I could use some assistance with this.
