### ISSUE TITLE
Plugin projects : connectivity_macos not found. Please update settings.gradle

### ISSUE THREAD

**Issue by Atteprojects** [parse-community/Parse-SDK-Flutter#404]
Hello, Before i installed the Parse server SDK, I did not have this error but after I installed the parse server SDK, I started getting this error. the Solution I found on stackoverflow requires modifying the flutter SDK itself and I don not want to do that. 
it only happens on Android. It works fine on IOS
The problem goes away when I remove the Parse server SDK from my projects. 
I am missing something?

**Comment by phillwiggins** [comment]
Thanks for raising this issue. What instructions does the Stackoverflow answer give you? I've not seen this issue as of yet?

**Comment by Atteprojects** [comment]
Thank you for the reply, 
this is the stackoverflow solution.
https://stackoverflow.com/questions/61904876/plugin-project-path-provider-macos-not-found-please-update-settings-gradle

**Comment by phillwiggins** [comment]
Thank you. 

I've just tried to search for this file but I don't seem to have it in any projects that I am using. Which IDE do you use?

**Comment by Atteprojects** [comment]
I am using VS Code. The error goes away when I uninstall the parse server SDK. I created an new flutter projects and the error is still there. Its only on android but the app still runs.

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
