### ISSUE TITLE
Add livequery example for DataTable (PaginatedDataTable)

### ISSUE THREAD

**Issue by aiv1** [parse-community/Parse-SDK-Flutter#405]
ParseLiveListWidget is a great implementation for List. Is it planned to do the same for PaginatedDataTable?

**Comment by maaeps** [comment]
I have not worked with DataTables yet. But as in the logic is separated from the widget it should be relatively easy to implement a working widget.
Have you seen [this](https://github.com/parse-community/Parse-SDK-Flutter/issues/330#issuecomment-626339650)?

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
