### ISSUE TITLE
Impossible to run in dart? 

### ISSUE THREAD

**Issue by krimpenrik** [parse-community/Parse-SDK-Flutter#408]
I went through the pain of setting up a parse server over the weekend and was just trying to do my first calls. But it seems like you can't use this package with dart? Trying to build a simple dart CLI app. I am running a fresh install. 
.
[test_parsie] pub get
Resolving dependencies...
Because every version of parse_server_sdk depends on flutter any from sdk which is forbidden, parse_server_sdk is forbidden.
So, because test_parsie depends on parse_server_sdk ^1.0.26, version solving failed.

Flutter users should run `flutter pub get` instead of `pub get`.
exit code 69

**Comment by krimpenrik** [comment]
can't get parse_server_sdk: ^1.0.11 to work with dart

**Comment by fischerscode** [comment]
We aim to fully support dart in version 1.0.28.

**Comment by fischerscode** [comment]
parse_server_sdk 2.0.0 supports dart. Please file an issue if you encounter bugs.
