### ISSUE TITLE
Parse SDK - Includeobject is not working while trying to fetch data from respective class

### ISSUE THREAD

**Issue by aniket453** [parse-community/Parse-SDK-Flutter#420]
Hello,

I am trying to fetch the values from my "Office" class and in my office class "user_id" column is the Pointer to my User class. So i also want to include user object. I am trying following code

```
QueryBuilder<ParseObject> parseQuery =
QueryBuilder<ParseObject>(ParseObject("Language"));
parseQuery.includeObject(['user_id']);

ParseResponse parseResponse = await parseQuery.query();
```

Output i am getting is : 

[{"className":" Language ","objectId":"w3U0iHfhkh","createdAt":"2020-08-16T10:23:15.961Z","updatedAt":"2020-08-16T10:23:15.961Z","name":"Lang2199","address":"Address1521","user_id":{"__type":"Pointer","className":"_User","objectId":"zbhsxhpr9x"}}]

Update this thread if anyone finds a solution.

Thanks.

**Comment by RodrigoSMarques** [comment]
@aniket453
Which version of the plugin are you using?

This works correctly in version 1.0.26

**Comment by aniket453** [comment]
@RodrigoSMarques  i am using "parse_server_sdk: ^1.0.26" latest version of parse sdk.

**Comment by RodrigoSMarques** [comment]
@aniket453 
I am using version 1.0.26. my log.

```dart
    final QueryBuilder queryBuilder =
        QueryBuilder<ParseObject>(ParseObject(keyFavoritesTable));
    //Two Pointers: Favorites to Ad (column ad) e Ad to _User (column onwer)
    queryBuilder.includeObject(['ad', 'Ad.owner']);
```
Query generated by Parse:
```
https://xxx.herokuapp.com/parse/classes/Favorites?where={"owner": "pYXeOSGNlF"}&include=Ad,Ad.owner&limit=1000
````
Result:
```
Payload: [{"className":"Favorites","objectId":"LmR5t9sBQp","createdAt":"2019-07-28T03:54:22.091Z","updatedAt":"2019-07-28T03:54:22.091Z","owner":"pYXeOSGNlF","ad":{"__type":"Pointer","className":"Ad","objectId":"DAP3lcVZRR"},"ACL":{"pYXeOSGNlF":{"read":true,"write":true}}}, {"className":"Favorites","objectId":"TdLzMRtN7R","createdAt":"2020-08-04T00:54:36.271Z","updatedAt":"2020-08-04T00:54:36.271Z","owner":"pYXeOSGNlF","ad":{"__type":"Pointer","className":"Ad","objectId":"pUUFsYYlkS"},"ACL":{"pYXeOSGNlF":{"read":true,"write":true}}}]
```
But the payload doesn't seem to be displaying correctly.

See the analysis in the debug:
![Captura de Tela 2020-08-17 às 08 52 41](https://user-images.githubusercontent.com/17687286/90394054-4fe74a80-e068-11ea-8c47-21bec459e1c1.png)
![Captura de Tela 2020-08-17 às 09 00 21](https://user-images.githubusercontent.com/17687286/90394061-55dd2b80-e068-11ea-9725-84b86f2fb838.png)

**Comment by MungaraJay** [comment]
Hello @RodrigoSMarques I have checked your answer.

Your payload is like,
Payload: [{"className":"Favorites","objectId":"LmR5t9sBQp","createdAt":"2019-07-28T03:54:22.091Z","updatedAt":"2019-07-28T03:54:22.091Z","owner":"pYXeOSGNlF","ad":{"__type":"Pointer","className":"Ad","objectId":"DAP3lcVZRR"},"ACL":{"pYXeOSGNlF":{"read":true,"write":true}}}, {"className":"Favorites","objectId":"TdLzMRtN7R","createdAt":"2020-08-04T00:54:36.271Z","updatedAt":"2020-08-04T00:54:36.271Z","owner":"pYXeOSGNlF","ad":{"__type":"Pointer","className":"Ad","objectId":"pUUFsYYlkS"},"ACL":{"pYXeOSGNlF":{"read":true,"write":true}}}]

But, can you try adding a new column in your ad pointer and when you will try to fetch those columns it's not going to return it anyway.

I am also getting similar kind of values. But, i am not getting all the columns. I think following three are different columns. You are also going to get those values without even using includeObject method.
"ad":{"__type":"Pointer","className":"Ad","objectId":"pUUFsYYlkS"}

But, i want all the column and properties of my class. 

So can you please try this?

Thanks.

**Comment by RodrigoSMarques** [comment]
@MungaraJay 
Did you check the print I sent?
The payload does not display the include objects, but they are in the response structure of ParseResponse

**Comment by MungaraJay** [comment]
@RodrigoSMarques How to map it using dart code if you are getting values?

**Comment by RodrigoSMarques** [comment]
@MungaraJay, try:

```dart
    if (parseResponse.success && parseResponse.results != null) {
     parseResponse.results.map((f) {
           final ad = f.get<ParseObject>('ad');
           print(ad);
          final user = ad.get<ParseUser>('owner');
          print(user);
      });
```

**Comment by fischerscode** [comment]
Are we save to close?

**Comment by MungaraJay** [comment]
You can close this one.
