### ISSUE TITLE
Cannot count User table

### ISSUE THREAD

**Issue by gadgetreviews** [parse-community/Parse-SDK-Flutter#423]
I just wanted to count how many users are in User table. I tried with following code. But it fails. If I replace User table with another newly created table, I get correct result with this code. Is there a security limitation by parse server for User table or are there any bug?
Thanks

````
QueryBuilder<ParseObject> queryPlayers = QueryBuilder<ParseObject>(ParseObject('User'));
var apiResponse = await queryPlayers.count();
if (apiResponse.success && apiResponse.result != null) {
      int countUsers = apiResponse.count + 1;
} else {
      print(apiResponse.error);
// It gives:  ParseException (Type: No Results) :
}
````

**Comment by RodrigoSMarques** [comment]
The _User class has certain restrictions. I already did it through the Cloud Code using masterkey.
Check if the count is allowed by the CLP - Class Level Permission.

Try:

```Dart
QueryBuilder<ParseUser> queryPlayers = QueryBuilder<ParseUser>(ParseUser.forQuery());
var apiResponse = await queryPlayers.count();
if (apiResponse.success && apiResponse.result != null) {
      int countUsers = apiResponse.count + 1;
} else {
      print(apiResponse.error);
// It gives:  ParseException (Type: No Results) :
}
```

**Comment by gadgetreviews** [comment]
Thanks for reply. It worked.

**Comment by RodrigoSMarques** [comment]
@gadgetreviews 
Very good. Please close the issue.

**Comment by fischerscode** [comment]
I am now closing this. Feel free to reopen if there is still a problem.
