### ISSUE TITLE
User.signUp() invalid token session

### ISSUE THREAD

**Issue by Danaru87** [parse-community/Parse-SDK-Flutter#426]
Hi all ;)

Using:
- SDK 1.0.27
- Flutter 1.20.2

When you create a user for the first time from a mobile app, everything is OK.

But, if the created user has been deleted on the server, the next time you register a new user from the same mobile application (same installation), the server will respond with 209 InvalidSessionToken.

Looking at ParseHttpClient we can see that if in ParseCoreData we have a sessionId, the request will be sent with the header "X-Parse-Session-Token: sessionId".

I think sessionId should not be sent for user registration/login and sessionId is not a good name, maybe sessionToken ?

**Comment by Danaru87** [comment]
I fixed this problem setting ParseCoreData().setSessionId(null) before calling ParseUser().signUp() in my code.

Maybe setting ParseCoreData().setSessionId(null) should be done in the signUp method directly.

**Comment by maaeps** [comment]
>Maybe setting ParseCoreData().setSessionId(null) should be done in the signUp/login method directly.

Sounds like a good idea. Are you creating a PR? Or should I do so?

**Comment by Danaru87** [comment]
I'll do it today ;)

> > Maybe setting ParseCoreData().setSessionId(null) should be done in the signUp/login method directly.
> 
> Sounds like a good idea. Are you creating a PR? Or should I do so?

I'll do it today ;)

**Comment by Danaru87** [comment]
@maaeps done ;) #427

**Comment by fischerscode** [comment]
As 1.0.27 is now released, I think this can be closed. :-)
