### ISSUE TITLE
request.user always undefined in cloud functions

### ISSUE THREAD

**Issue by na2axl** [parse-community/Parse-SDK-Flutter#429]
Hi all,

I'm experiencing an issue when calling cloud functions. `request.user` is always undefined, even if the user is logged in. I've seen that there was a similar issue (#266) but the solution was to use `autoSendSessionId: true` and define the client ID, things that I'have done before to know that it's a possible solution.

If it can help, there is how I'm initializing Parse:

```dart
await Parse().initialize(
  APPLICATION_ID,
  SERVER_URL,
  clientKey: CLIENT_KEY,
  autoSendSessionId: true,
  appName: APP_NAME,
  debug: true,
  coreStore: await CoreStoreSembastImp.getInstance(
    password: PARSE_LOCAL_STORE_PASSWORD,
  ),
);
```

Can someone help please ?

---

**EDIT**

I'm using:

- Parse SDK Flutter: 1.0.27
- Flutter: 1.20 (beta channel)

**Comment by phillwiggins** [comment]
Hey, do you have an example of the cloud function you are calling and the
response?

**Comment by na2axl** [comment]
Hi @phillwiggins, sorry for the delay. After some in depth debugging it's seems that the problem is an async/await misuse from my side 😅. Everything works as expected now. Sorry for the disturbing and thanks for the support 🙂

**Comment by sautible** [comment]
@na2axl Am facing the same problem, can you shed some light as to how you were able to solve this. Thanks

**Comment by negiot** [comment]
hi guys i have the same problem on back4app. I set both the autoSendSessionId and the clientkey .... any ideas? Thanks for your help
