### ISSUE TITLE
[Feature request] Graphql

### ISSUE THREAD

**Issue by FNPCMDs** [parse-community/Parse-SDK-Flutter#432]
Hi!!
Is there any plans to include Graphql on the package? Right now I'm using [graphql](https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql), but would be great include it on the SDK.
As you know, there is issues like: #424, #416, #338, #365, #229 where LiveQuery can't include Relations. Also, sometimes we must do two or three request to get all data (because querybuilder doesn't return relationed objects).

That is why I think it would be useful to include GraphQL on this package. Also Parse Community are working on GraphQL subscription [#6617](https://github.com/parse-community/parse-server/issues/6617), so we will be able to stop using LiveQuery.

Greetings!

**Comment by RodrigoSMarques** [comment]
@FNPCMDs 
To use GraphQL wouldn't it be just using any of the packages available on pub.dev?
I believe that there is no need for a specific package for Parse Server.

About Relation. The implementation of the relation seems to me to be incomplete.
I use relational objects in my projects through Pointer and I don't have any problems of use, using the ``` include```.
The output of the payload for some reason does not show the data, but they are in the result and I can access them using ``` get <ParseObject> ```.
I even have a case where I use Relation with ```whereMatchesQuery```.
Now the include using ``` LiveQuery```, I never needed to use it.
Next month I'm completing a project and I intend to take the time to take a look at this package again.

**Comment by prakash-indorkar** [comment]
@RodrigoSMarques  How to get the related data using the get method .. I'm not able to get it .. could you please provide the example?
Thanks
