### ISSUE TITLE
Flutter Parse SDK - ParseUser.currentuser null even after logging in.

### ISSUE THREAD

**Issue by MungaraJay** [parse-community/Parse-SDK-Flutter#442]
Hello,

I was trying to login to my app via the following method which is,

```
ParseUser user = ParseUser(email, event.password, email);
ParseResponse apiResponse = await user.login();
```

After logging in checking that the logged in user is also "emailverfified " i let the user to navigate to my app's home screen.

In initstate of my app's home screen, I try to get the details of my current logged in user like,
`ParseUser user = await ParseUser.currentUser();`

But, i am getting user value "null" every time even after login. It was working fine before.

So can you tell me what is  wrong with this approach?

Why i am getting currentuser data null?

I am using version **1.0.27** of flutter parse-sdk-sever package.

Thanks.

**Comment by fischerscode** [comment]
This should work. (I am doing basically the same.)

> After logging in checking that the logged in user is also "emailverfified "

And you are logging in an existing user? For signing up there is an extra function called `user.signUp()`.

**Comment by MungaraJay** [comment]
@fischerscode yes i am checking that only for existing user. But, it seems even after checking that emailverified is true. Then i navigate user to my home screen. There i am trying to get my current user. But, it's null every single time. It was working fine before. I have cleared cache, uninstalled app etc.

But, no luck.

What might be the possible cause?

**Comment by fischerscode** [comment]
Just verified that the login of my app still works. (I am using the current state of 1.0.28)
Which CoreStore are you using?
Could you please run this `print(await ParseUser.currentUser());` as well as `print(user.getUpdatedUser());` right after your login finished?

**Comment by MungaraJay** [comment]
I have tried it and it gives me following error,

 user : null
E/flutter (13275): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'getUpdatedUser' was called on null.

**Comment by fischerscode** [comment]
What does `print(ParseCoreData().sessionId);` right after the login return?
Are any strange messages in your ParseServer log?

**Comment by fischerscode** [comment]
@MungaraJay 
Can this be closed?

**Comment by MungaraJay** [comment]
You can close it if you want for the maintenance support.

**Comment by fischerscode** [comment]
@MungaraJay
I am just trying to clean up old/resolved issues.
If this is still a problem, I am happy to keep it open.

**Comment by tehsunnliu** [comment]
Hi, I'm facing something similar problem, in my case when I close the app and restart the app ParseUser.currentUser() returns null.
I'm calling that function after parse is initialized.

I'm using a FutureBuilder to check if user exists and navigate to the LoginView or HomeView 
`@override
  Widget build(BuildContext context) {
    getUser();
    return FutureBuilder(
      future: ParseUser.currentUser(),
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          return MaterialApp(
            title: 'Raph',
            theme: RaphTheme.themeData,
            home: ChangeNotifierProvider<BottomNavBarController>(
              create: (context) => BottomNavBarController(),
              child: HomeView(),
            ),
          );
        }
        return MaterialApp(
          home: LoginView(),
        );
      },
    );
  }
`

Everything works fine till I close the app and restart it. I've tried getting the user before the build function is called still no luck.
Thank you.

**Comment by fischerscode** [comment]
@tehsunnliu 
I assume the problem was [this](https://github.com/parse-community/Parse-SDK-Flutter/issues/299#issuecomment-722225325).

**Comment by tehsunnliu** [comment]
Yes @fischerscode 
That fixed my problem. Thank you.
