### ISSUE TITLE
Getting error when using Parse with flutter web

### ISSUE THREAD

**Issue by manatech** [parse-community/Parse-SDK-Flutter#451]
I am getting errors when I want to run the flutter web app:
`ang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:104:42: Error: Type 'Pointer' not found.
typedef _DeleteClass_Dart = int Function(Pointer obj, Pointer<Utf16> strClass,
                                         ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:104:55: Error: Type 'Pointer' not found.
typedef _DeleteClass_Dart = int Function(Pointer obj, Pointer<Utf16> strClass,
                                                      ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:104:55: Error: Expected 0 type arguments.
typedef _DeleteClass_Dart = int Function(Pointer obj, Pointer<Utf16> strClass,
                                                      ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:105:17: Error: Type 'Pointer' not found.
    int lFlags, Pointer<COMObject> pCtx, Pointer<IntPtr> ppCallResult);
                ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:105:17: Error: Expected 0 type arguments.
    int lFlags, Pointer<COMObject> pCtx, Pointer<IntPtr> ppCallResult);
                ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:105:50: Error: Type 'IntPtr' not found.
    int lFlags, Pointer<COMObject> pCtx, Pointer<IntPtr> ppCallResult);
                                                 ^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:400:15: Error: 'NativeFunction' isn't a type.
      Pointer<NativeFunction<_CreateClassEnumAsync_Native>>.fromAddress(
              ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:400:7: Error: Method not found: 'Pointer.fromAddress'.
      Pointer<NativeFunction<_CreateClassEnumAsync_Native>>.fromAddress(
      ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:405:19: Error: 'Pointer' isn't a type.
  int PutInstance(Pointer<COMObject> pInst, int lFlags, Pointer<COMObject> pCtx,
                  ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:405:57: Error: 'Pointer' isn't a type.
  int PutInstance(Pointer<COMObject> pInst, int lFlags, Pointer<COMObject> pCtx,
                                                        ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:406:19: Error: 'IntPtr' isn't a type.
          Pointer<IntPtr> ppCallResult) =>
                  ^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:406:11: Error: 'Pointer' isn't a type.
          Pointer<IntPtr> ppCallResult) =>
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:407:15: Error: 'NativeFunction' isn't a type.
      Pointer<NativeFunction<_PutInstance_Native>>.fromAddress(
              ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:407:7: Error: Method not found: 'Pointer.fromAddress'.
      Pointer<NativeFunction<_PutInstance_Native>>.fromAddress(
      ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:412:24: Error: 'Pointer' isn't a type.
  int PutInstanceAsync(Pointer<COMObject> pInst, int lFlags,
                       ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:413:11: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pCtx, Pointer<COMObject> pResponseHandler) =>
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:413:36: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pCtx, Pointer<COMObject> pResponseHandler) =>
                                   ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:414:15: Error: 'NativeFunction' isn't a type.
      Pointer<NativeFunction<_PutInstanceAsync_Native>>.fromAddress(
              ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:414:7: Error: Method not found: 'Pointer.fromAddress'.
      Pointer<NativeFunction<_PutInstanceAsync_Native>>.fromAddress(
      ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:419:22: Error: 'Pointer' isn't a type.
  int DeleteInstance(Pointer<Utf16> strObjectPath, int lFlags,
                     ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:420:11: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pCtx, Pointer<IntPtr> ppCallResult) =>
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:420:44: Error: 'IntPtr' isn't a type.
          Pointer<COMObject> pCtx, Pointer<IntPtr> ppCallResult) =>
                                           ^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:420:36: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pCtx, Pointer<IntPtr> ppCallResult) =>
                                   ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:421:15: Error: 'NativeFunction' isn't a type.
      Pointer<NativeFunction<_DeleteInstance_Native>>.fromAddress(
              ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:421:7: Error: Method not found: 'Pointer.fromAddress'.
      Pointer<NativeFunction<_DeleteInstance_Native>>.fromAddress(
      ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:426:27: Error: 'Pointer' isn't a type.
  int DeleteInstanceAsync(Pointer<Utf16> strObjectPath, int lFlags,
                          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:427:11: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pCtx, Pointer<COMObject> pResponseHandler) =>
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:427:36: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pCtx, Pointer<COMObject> pResponseHandler) =>
                                   ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:428:15: Error: 'NativeFunction' isn't a type.
      Pointer<NativeFunction<_DeleteInstanceAsync_Native>>.fromAddress(
              ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:428:7: Error: Method not found: 'Pointer.fromAddress'.
      Pointer<NativeFunction<_DeleteInstanceAsync_Native>>.fromAddress(
      ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:433:26: Error: 'Pointer' isn't a type.
  int CreateInstanceEnum(Pointer<Utf16> strFilter, int lFlags,
                         ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:434:11: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pCtx, Pointer<IntPtr> ppEnum) =>
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:434:44: Error: 'IntPtr' isn't a type.
          Pointer<COMObject> pCtx, Pointer<IntPtr> ppEnum) =>
                                           ^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:434:36: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pCtx, Pointer<IntPtr> ppEnum) =>
                                   ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:435:15: Error: 'NativeFunction' isn't a type.
      Pointer<NativeFunction<_CreateInstanceEnum_Native>>.fromAddress(
              ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:435:7: Error: Method not found: 'Pointer.fromAddress'.
      Pointer<NativeFunction<_CreateInstanceEnum_Native>>.fromAddress(
      ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:440:31: Error: 'Pointer' isn't a type.
  int CreateInstanceEnumAsync(Pointer<Utf16> strFilter, int lFlags,
                              ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:441:11: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pCtx, Pointer<COMObject> pResponseHandler) =>
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:441:36: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pCtx, Pointer<COMObject> pResponseHandler) =>
                                   ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:471:7: Error: Method not found: 'Pointer.fromAddress'.
      Pointer<NativeFunction<_ExecNotificationQuery_Native>>.fromAddress(
      ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:477:11: Error: 'Pointer' isn't a type.
          Pointer<Utf16> strQueryLanguage,
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:478:11: Error: 'Pointer' isn't a type.
          Pointer<Utf16> strQuery,
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:480:11: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pCtx,
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:481:11: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pResponseHandler) =>
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:482:15: Error: 'NativeFunction' isn't a type.
      Pointer<NativeFunction<_ExecNotificationQueryAsync_Native>>.fromAddress(
              ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:482:7: Error: Method not found: 'Pointer.fromAddress'.
      Pointer<NativeFunction<_ExecNotificationQueryAsync_Native>>.fromAddress(
      ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:488:11: Error: 'Pointer' isn't a type.
          Pointer<Utf16> strObjectPath,
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:489:11: Error: 'Pointer' isn't a type.
          Pointer<Utf16> strMethodName,
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:491:11: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pCtx,
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:492:11: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pInParams,
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:493:19: Error: 'IntPtr' isn't a type.
          Pointer<IntPtr> ppOutParams,
                  ^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:493:11: Error: 'Pointer' isn't a type.
          Pointer<IntPtr> ppOutParams,
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:494:19: Error: 'IntPtr' isn't a type.
          Pointer<IntPtr> ppCallResult) =>
                  ^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:494:11: Error: 'Pointer' isn't a type.
          Pointer<IntPtr> ppCallResult) =>
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:495:15: Error: 'NativeFunction' isn't a type.
      Pointer<NativeFunction<_ExecMethod_Native>>.fromAddress(
              ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:495:7: Error: Method not found: 'Pointer.fromAddress'.
      Pointer<NativeFunction<_ExecMethod_Native>>.fromAddress(
      ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:501:11: Error: 'Pointer' isn't a type.
          Pointer<Utf16> strObjectPath,
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:502:11: Error: 'Pointer' isn't a type.
          Pointer<Utf16> strMethodName,
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:504:11: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pCtx,
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:505:11: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pInParams,
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:506:11: Error: 'Pointer' isn't a type.
          Pointer<COMObject> pResponseHandler) =>
          ^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:507:15: Error: 'NativeFunction' isn't a type.
      Pointer<NativeFunction<_ExecMethodAsync_Native>>.fromAddress(
              ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.2/lib/src/generated/IWbemServices.dart:507:7: Error: Method not found: 'Pointer.fromAddress'.
      Pointer<NativeFunction<_ExecMethodAsync_Native>>.fromAddress(
      ^^^^^^^^^^^
Failed to compile application.

```
import 'package:flutter/material.dart';
import 'package:flutter_app_web/pages/home.dart';
import 'package:parse_server_sdk/parse_server_sdk.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    // TODO: implement initState
    initData();
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test',
      home: Home(),
    );
  }

  void initData() async {
    await Parse().initialize(
        'my_app_id',
        'my_server_url',
        masterKey: my_master_key',
        coreStore: await CoreStoreSembastImp.getInstance());
  }
}

```

**Comment by fischerscode** [comment]
Are you using version 1.0.27?
Web support for `CoreStoreSembastImp` was added with #436.
1.0.27 does only support web when using `CoreStoreSharedPrefsImp`.

**Comment by manatech** [comment]
Yes I am using 1.0.27
I also tested with both CoreStoreSharedPrefsImp and CoreStoreSembastImp  but the problem still exists and I am getting same error.

**Comment by manatech** [comment]
I just imported the package and even without using it and without initializing the Parse I am getting this error again. 

```
import 'package:flutter/material.dart';
import 'package:parse_server_sdk/parse_server_sdk.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'My Flutter App',
      home: Scaffold(
        appBar: AppBar(
          title: Text("Test AppBar"),
          centerTitle: true,
        ),
        body: Center(
          child: Text("Hello, World!"),
        ),
      ),
    );
  }
}
```

**Comment by FNPCMDs** [comment]
> I just imported the package and even without using it and without initializing the Parse I am getting this error again.
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:parse_server_sdk/parse_server_sdk.dart';
> 
> void main() {
>   runApp(MyApp());
> }
> 
> class MyApp extends StatefulWidget {
>   @override
>   _MyAppState createState() => _MyAppState();
> }
> 
> class _MyAppState extends State<MyApp> {
>   @override
>   void initState() {
>     super.initState();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'My Flutter App',
>       home: Scaffold(
>         appBar: AppBar(
>           title: Text("Test AppBar"),
>           centerTitle: true,
>         ),
>         body: Center(
>           child: Text("Hello, World!"),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> and here is my puspec.yaml file:
> 
> ```
> name: flutter_web
> description: A new Flutter project.
> 
> # The following line prevents the package from being accidentally published to
> # pub.dev using `pub publish`. This is preferred for private packages.
> publish_to: "none" # Remove this line if you wish to publish to pub.dev
> 
> # The following defines the version and build number for your application.
> # A version number is three numbers separated by dots, like 1.2.43
> # followed by an optional build number separated by a +.
> # Both the version and the builder number may be overridden in flutter
> # build by specifying --build-name and --build-number, respectively.
> # In Android, build-name is used as versionName while build-number used as versionCode.
> # Read more about Android versioning at https://developer.android.com/studio/publish/versioning
> # In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
> # Read more about iOS versioning at
> # https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
> version: 1.0.0+1
> 
> environment:
>   sdk: ">=2.7.0 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
>   parse_server_sdk: ^1.0.27
> 
>   # The following adds the Cupertino Icons font to your application.
>   # Use with the CupertinoIcons class for iOS style icons.
>   cupertino_icons: ^1.0.0
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
> 
> # For information on the generic Dart part of this file, see the
> # following page: https://dart.dev/tools/pub/pubspec
> 
> # The following section is specific to Flutter.
> flutter:
>   # The following line ensures that the Material Icons font is
>   # included with your application, so that you can use the icons in
>   # the material Icons class.
>   uses-material-design: true
> 
>   # To add assets to your application, add an assets section, like this:
>   # assets:
>   #   - images/a_dot_burr.jpeg
>   #   - images/a_dot_ham.jpeg
> 
>   # An image asset can refer to one or more resolution-specific "variants", see
>   # https://flutter.dev/assets-and-images/#resolution-aware.
> 
>   # For details regarding adding assets from package dependencies, see
>   # https://flutter.dev/assets-and-images/#from-packages
> 
>   # To add custom fonts to your application, add a fonts section here,
>   # in this "flutter" section. Each entry in this list should have a
>   # "family" key with the font family name, and a "fonts" key with a
>   # list giving the asset and other descriptors for the font. For
>   # example:
>   # fonts:
>   #   - family: Schyler
>   #     fonts:
>   #       - asset: fonts/Schyler-Regular.ttf
>   #       - asset: fonts/Schyler-Italic.ttf
>   #         style: italic
>   #   - family: Trajan Pro
>   #     fonts:
>   #       - asset: fonts/TrajanPro.ttf
>   #       - asset: fonts/TrajanPro_Bold.ttf
>   #         weight: 700
>   #
>   # For details regarding fonts from package dependencies,
>   # see https://flutter.dev/custom-fonts/#from-packages
> ```
> 
> My flutter version: Flutter 1.22.0-12.1.pre
> channel: beta
> Dart Version: 2.10.0
> OS: Windows 10 Pro 64 bit
> 
> This error does not happen when I deploy the app to a mobile device. Just with web

Hi, can you run `flutter clean`, and try again?

**Comment by manatech** [comment]
> Hi, can you run `flutter clean`? and then try again.
> 
> Greetings!

Thank you but still no success

**Comment by fischerscode** [comment]
I am sorry, some how this disappeared from my github notifications.
Does this problem still appear? Does this still appear after migrating to 2.0.0?

**Comment by manatech** [comment]
> I am sorry, some how this disappeared from my github notifications.
> Does this problem still appear? Does this still appear after migrating to 2.0.0?

No it disappeared without any reason. Thank you

**Comment by fischerscode** [comment]
I am closing this now, I assume some file was cached wrongly.
