### ISSUE TITLE
How to use ParseRole?

### ISSUE THREAD

**Issue by manatech** [parse-community/Parse-SDK-Flutter#453]
Is there anyway to use ParseRoles in my Flutter app?

```
var roleACL = new ParseACL()
roleACL.publicReadAccess = true;
var role = new ParseRole("Administrator", roleACL);
await role.save();
```

It seems that there is no ParseRole class in the API

**Comment by felix-ht** [comment]
@manatech 
You can use `"_Role" `as the class key to access Roles as expected.

Get all Roles:
```dart
ParseObject("_Role").getAll();
```

Query all users related to a Role:
```dart
 var query = QueryBuilder(ParseUser(null,null,null))
        ..whereRelatedTo("users", "_Role", objectId);
var response = query.query();
```

https://docs.parseplatform.org/rest/guide/#retrieving-roles

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
