### ISSUE TITLE
Can I use this not in a flutter project? For example in a dart aqueduct?

### ISSUE THREAD

**Issue by AlexKenbo** [parse-community/Parse-SDK-Flutter#454]
Can I use this not in a flutter project? For example in a dart aqueduct?

**Comment by fischerscode** [comment]
In version 1.0.28 we try to split this repository in a flutter and a dart package.
You should be able to add `parse_server_sdk` like [this](https://github.com/parse-community/Parse-SDK-Flutter/issues/385#issuecomment-694116773).
```
parse_server_sdk:
    path: ../Parse-SDK-Flutter/packages/dart
```

For more information, see #439.

Please note, that the documentation is not finished for the dart package.

**Comment by SuperKMan** [comment]
Thank you. I got an error about "CoreStoreSharedPrefsImp" when I use Dart package instead of Flutter package. Do you have any suggestion?

**Comment by fischerscode** [comment]
As 1.0.28 is now released, [parse_server_sdk](https://pub.dev/packages/parse_server_sdk) should now work fine with dart.
