### ISSUE TITLE
How to make several related ParseObjects

### ISSUE THREAD

**Issue by AlexKenbo** [parse-community/Parse-SDK-Flutter#455]
Here is an example for one class without links. How would multiple classes with links look like? One to one, one to many, many to many?

https://github.com/parse-community/Parse-SDK-Flutter#custom-objects

**Comment by fischerscode** [comment]
I am not sure if I understand your problem correctly.

- For a one to one relation, I suggest using a pointer in one class.
Technically this allows a one to many relation so you have to make sure to only use it as a one to one relation.
- For a one to many relation, I suggest using also a pointer in the "ManyClass"
- For a many to many relation, I suggest creating a ClassOne_ClassTwo class, that contains a Pointer to both classes.

**Comment by AlexKenbo** [comment]
I just wanted to see some code examples. for one to one and one to many

**Comment by AlexKenbo** [comment]
`class DietPlan extends ParseObject implements ParseCloneable {

  DietPlan() : super(_keyTableName);
  DietPlan.clone(): this();

  /// Looks strangely hacky but due to Flutter not using reflection, we have to
  /// mimic a clone
  @override clone(Map map) => DietPlan.clone()..fromJson(map);

  static const String _keyTableName = 'Diet_Plans';
  static const String keyName = 'Name';
  
  String get name => get<String>(keyName);
  set name(String name) => set<String>(keyName, name);

  //one to one ???
  static const Position dietPosition = 'Position';
  
  Position get name => get<Position>(dietPosition);
  set name(Position name) => set<Position>(dietPosition, name);

 //one to many ???
  static const List<Client> dietClients = 'Client';
  
  List<Client> get clients => get<List<Client>>(dietClients);
  set clients(List<Client> clients) => set<List<Client>>(dietClients, name);

}`

**Comment by igorgoncalves** [comment]
LIke this? 


`dart
List<Desafio> get desafios => get<List<dynamic>>(keyDesafios)
      ?.map((desafio) =>
          Desafio.clone()..fromJson((desafio as ParseObject).toJson()))
      ?.toList();
  set desafios(List<Object> desafios) =>
      set<List<Object>>(keyDesafios, desafios);
`

> ```dart
> class DietPlan extends ParseObject implements ParseCloneable {
> 
>   DietPlan() : super(_keyTableName);
>   DietPlan.clone(): this();
> 
>   /// Looks strangely hacky but due to Flutter not using reflection, we have to
>   /// mimic a clone
>   @override clone(Map map) => DietPlan.clone()..fromJson(map);
> 
>   static const String _keyTableName = 'Diet_Plans';
>   static const String keyName = 'Name';
>   
>   String get name => get<String>(keyName);
>   set name(String name) => set<String>(keyName, name);
> 
>   //one to one ???
>   static const Position dietPosition = 'Position';
>   
>   Position get name => get<Position>(dietPosition);
>   set name(Position name) => set<Position>(dietPosition, name);
> 
>  //one to many ???
>   static const List<Client> dietClients = 'Client';
>   
>   List<Client> get clients => get<List<Client>>(dietClients);
>   set clients(List<Client> clients) => set<List<Client>>(dietClients, name);
> }
> ```

Try something like this: 

```Dart
List<Desafio> get desafios => get<List<dynamic>>(keyDesafios)
      ?.map((desafio) =>
          Desafio.clone()..fromJson((desafio as ParseObject).toJson()))
      ?.toList();
  set desafios(List<Object> desafios) =>
      set<List<Object>>(keyDesafios, desafios);
```

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
