### ISSUE TITLE
[Regression] Registration not working in 1.0.28 

### ISSUE THREAD

**Issue by BaranMichal25** [parse-community/Parse-SDK-Flutter#456]
So because of issue https://github.com/parse-community/Parse-SDK-Flutter/issues/444 and then PR https://github.com/parse-community/Parse-SDK-Flutter/pull/446 registration stopped working with Parse returning: 
```
ParseException (Type: PasswordMissing) :
Code: 201
Message: password is required----
```
This can be easily fixed by adding [here](https://github.com/parse-community/Parse-SDK-Flutter/blob/release/1.0.28/packages/dart/lib/src/objects/parse_user.dart#L151):
```dart
      final Map<String, dynamic> bodyData = _getObjectData();
      bodyData['password'] = password;
      final Uri url = getSanitisedUri(_client, '$path');
```
but I wonder if this the approach we wanna take? Or if there are other things broken because of that?
@fischerscode

**Comment by fischerscode** [comment]
I think, as [this](https://github.com/parse-community/Parse-SDK-Flutter/blob/release/1.0.28/packages/dart/lib/src/objects/parse_user.dart#L151) is the only time where `_objectData` is directly accessed by `ParseUser`, we should be fine by doing your change.
