### ISSUE TITLE
Query specific column

### ISSUE THREAD

**Issue by SuperKMan** [parse-community/Parse-SDK-Flutter#461]
I have a large object but I want to select only some property. I try to use keysToReturn method of QueryBuilder but still return all properties of the object in response. What is my mistake?

**Comment by fischerscode** [comment]
Can you provide an example query, that does not work?

**Comment by SuperKMan** [comment]
Future<List<District>> getDistrict() async {
    final QueryBuilder<District> query = QueryBuilder<District>(District())
      ..keysToReturn(['districtID', 'nameTh'])
      ..whereEqualTo('provinceID', _selectedProvince.provinceId);

    ParseResponse response = await query.query();
    _districts = [];
    if (response.success && response.count > 0) {
      for (final District district in response.results) {
        _districts.add(district);
      }
    }
    return _districts;
  }

**Comment by fischerscode** [comment]
This should work.
Only system fields like objectId or createdAt should be received.

**Comment by SuperKMan** [comment]
I understood, thank you so much.

**Comment by fischerscode** [comment]
I am closing this now.
