### ISSUE TITLE
Pagination with flutter_pagewise

### ISSUE THREAD

**Issue by SuperKMan** [parse-community/Parse-SDK-Flutter#463]
Hi,

Does anyone use to used Parse pagination with flutter_pagewise? Which lazy-loading widget that best for Parse?

**Comment by fischerscode** [comment]
@SuperKMan 
For lazy-loading a list, I suggest using the [ParseLiveListWidget](https://github.com/parse-community/Parse-SDK-Flutter/tree/release/1.0.27#parselivelist).

**Comment by SuperKMan** [comment]
Thank you.

**Comment by fischerscode** [comment]
I'm closing this now. Feel free to reopen if there are any more questions.
