### ISSUE TITLE
ParseResponse.results should return empty list instead of null

### ISSUE THREAD

**Issue by ephrimlawrence** [parse-community/Parse-SDK-Flutter#464]
ParseResponse.results should return an empty list instead of null.
This will reduce the work of having to check whether ParseResponse.results is always null or count > 0 on every request/query.

For example, "response.count > 0" is unneccessary if   response.results is an empty list by default.
```dart
ParseResponse response = await query.query();
_districts = [];
if (response.success && response.count > 0) {
  for (final District district in response.results) {
    _districts.add(district);
  }
}
return _districts;
```

The response.count can be removed like below (if response.results is an empty list by default)
```dart
ParseResponse response = await query.query();
_districts = [];
if (response.success) {
  for (final District district in response.results) {
    _districts.add(district);
  }
}
return _districts;
```

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
