### ISSUE TITLE
SignUp encoding data to JSON

### ISSUE THREAD

**Issue by itmesh** [parse-community/Parse-SDK-Flutter#466]
https://github.com/parse-community/Parse-SDK-Flutter/blob/6e01d28020c80142984b14c7e7d1edef7016d9fb/packages/dart/lib/src/objects/parse_user.dart#L144

Hi,
 
I was trying add some data while registering user, but it doesn't work with DateTime object because DateTime does't has toJson method. And we have to send different format to parse than just DateTime in String.

I paste my solution below to save password to unsavedChanges and use existing method toJson from your library.
Instead of current code
```
      final Map<String, dynamic> bodyData = _getObjectData();
      bodyData[keyVarPassword] = password;
      ...
      final String body = json.encode(bodyData);
```
I use this
```
      _unsavedChanges[keyVarPassword] = password;
      ...
      final String body = json.encode(toJson(forApiRQ: true));
```
With this body we can create parse user with all data.

Let me know if it's clear. If not I will come back with more info.

**Comment by fischerscode** [comment]
Just to clarify:
You want to create a ParseUser object, then add extra data (esp. a date) and then sign up?
And in order to solve this, you replaced [this](https://github.com/parse-community/Parse-SDK-Flutter/blob/6e01d28020c80142984b14c7e7d1edef7016d9fb/packages/dart/lib/src/objects/parse_user.dart#L155) by [this](https://github.com/parse-community/Parse-SDK-Flutter/blob/6e01d28020c80142984b14c7e7d1edef7016d9fb/packages/dart/lib/src/objects/parse_object.dart#L71).

This change sounds reasonable, as `ParseObject.update()` as well as `ParseObject.create()` are using the `toJson` method.

**Comment by itmesh** [comment]
Exactly.
You can create ParseUser object now with some simple data using json encoding from Flutter, but it doesn't with Date!

**Don't forget to add password to _unsavedChanges, because you can't use bodyData like before**

**Comment by fischerscode** [comment]
> but it doesn't with Date

That's weird, as [this](https://github.com/parse-community/Parse-SDK-Flutter/blob/2088bf1b07594a080b91d5002eda0515dae63568/lib/src/utils/parse_encoder.dart#L19) should encode the date properly.

**Comment by fischerscode** [comment]
I have tried adding a date before signUp using [this](https://github.com/fischerscode/Parse-SDK-Flutter/tree/issue-%23466) branch. For me this worked.
```dart
ParseUser user = ParseUser("test4", "secret", "test@example.com");
user.set("test", DateTime.now());
user.signUp();
```

**Comment by itmesh** [comment]
> I have tried adding a date before signUp using [this](https://github.com/fischerscode/Parse-SDK-Flutter/tree/issue-%23466) branch. For me this worked.
> 
> ```dart
> ParseUser user = ParseUser("test4", "secret", "test@example.com");
> user.set("test", DateTime.now());
> user.signUp();
> ```

Yes, it works well.
To clarify with master branch it will not work so fix is required.

**Comment by fischerscode** [comment]
I see. Thanks for the clarification.

**Comment by fischerscode** [comment]
@itmesh I've created a PR #470. Can you please have a quick look at the changes?

**Comment by itmesh** [comment]
We can close issue, everything is fine, tested on the newest version 1.0.28.
