### ISSUE TITLE
Why did LiveQuery get deprecated?

### ISSUE THREAD

**Issue by ThatoXDev** [parse-community/Parse-SDK-Flutter#467]
My project was working fine with LiveQuery now I get null error and deprecated message. What is the alternative method?

NoSuchMethodError (NoSuchMethodError: The method 'on' was called on null.
Receiver: null
Tried calling: on(Instance of 'LiveQueryEvent', Closure: (dynamic) => Null))

**Comment by fischerscode** [comment]
Are you using `LiveQuery` as described [here](https://github.com/parse-community/Parse-SDK-Flutter#live-queries)?
I assume, your subscription is null.
Which version are you using, In which version did it work?

**Comment by ThatoXDev** [comment]
Hi, I managed to make it work. I needed to add Subscription sub = await liveQuery....
Thanks, I didn't know it was changed
