### ISSUE TITLE
How to Migrate to version 2.x

### ISSUE THREAD

**Issue by fischerscode** [parse-community/Parse-SDK-Flutter#477]
Follow the [migration guide](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/docs/migrate-2-0-0.md) in order to upgrade from 1.0.27 to 2.0.0.
Note: 1.0.28 has been renamed to 2.0.0 in order to reflect the breaking changes in the version number.

> # Migrate your Flutter application to version 2.0.0
> 
> Starting with version 2.0.0, this repository is now separated in a pure dart (parse_server_sdk) and a flutter package (parse_server_sdk_flutter).
> This was done in order to provide a dart package for the parse-server, while keeping maintenance simple.
> You can find both packages in the package directory.
> 
> ### 1. pubspec.yaml
> In your projects pubspec.yaml at the dependencies section, you have to change
> ```
> dependencies:
>     parse_server_sdk: ^1.0.27
> ```
> to
> ```
> dependencies:
>     parse_server_sdk_flutter: ^2.0.0
> ```
> This is the current released version of the parse_server_sdk_flutter package: [![pub package](https://img.shields.io/pub/v/parse_server_sdk_flutter.svg)](https://pub.dev/packages/parse_server_sdk_flutter)
> 
> ### 2. imports
> As the package name changed, you have to change
> ```
> import 'package:parse_server_sdk/parse_server_sdk.dart';
> ```
>  to  
> ```
> import 'package:parse_server_sdk_flutter/parse_server_sdk.dart';
> ```
> in every file.
> 
> It is recommended to do so by the replacement feature of your IDE.
> 
> ### optional: provide app information on web
> As flutter web is now in beta, this SDK aims to be web compatible.
> But there are some parts completely different on web. For example, the wep-app cant determine it's name, version or packagename.
> That's why you should provide this information on web.
> ```dart
> Parse().initialize(
>     ...
>     appName: kIsWeb ? "MyApplication" : null,
>     appVersion: kIsWeb ? "Version 1" : null,
>     appPackageName: kIsWeb ? "com.example.myapplication" : null,
> );
> ```
> 
> ### optional: adjust your tests
> You tests might fail if the package tries to automatically discover facts like you applications name, version, package name or the default file directory.
> You can avoid this automatic discovery by providing values for `appName`, `appVersion`, `appPackageName` as well as `fileDirectory` at you `Parse().initialize()` call.
> 
> ### changed network library
> In order to provide a `ProgressCallback` for heavy file operations,
> the network library was switched from [http](https://pub.dev/packages/http) to [dio](https://pub.dev/packages/dio).
> There should be no breaking changes regarding this change, except if you are overriding the `ParseHTTPClient`.

**Comment by RodrigoSMarques** [comment]
I understood the issue, my project is working.
This was just an exercise.

As there was only an increment in the patch version, I am sure that many will not notice that the package has changed.

The changelog says that the package has been separated, but for example, it does not advise that anyone who uses Flutter should change the package and do the migration.

I know there is guidance on the page, but it is not highlighted.

I work daily with developers with all levels of knowledge.

I have a Flutter course on an online platform with more than 30,000 students. There we built an app using Parse Server and the package.

It may seem simple, but I am sure that many will have difficulties in migrating.

Not because the migration process is complicated, but because in version 1.0.28, you expect a patch and not a change in your working code.

If there was a split between Dart and Flutter, jumping to version 2.0.0 is not wrong.

In doing this, you are saying: "I have a big change, you need to check the changelog and check some migration guide".

See for example the provider's package:
https://pub.dev/packages/provider#migration-from-v3x0-to-v400

Well, this is my point of view.

**Comment by SuperKMan** [comment]
Good job.

**Comment by fischerscode** [comment]
1.0.28 was renamed to 2.0.0 in order to make the breaking changes reflected in the version number.

**Comment by xor22h** [comment]
@fischerscode Any ideas why a "flutter" version doesn't allow to specify custom path? I've tried to migrate to "flutter" version but that one is freezing. Seems that a freeze is being cause by path (documentsDirectory);

Sample code below, only relevant parts. ;)

```
import 'package:flutter/material.dart';
import 'package:package_info/package_info.dart';
import 'package:parse_server_sdk/parse_server_sdk.dart';
import 'package:path_provider/path_provider.dart';
import 'package:provider/provider.dart';
import 'configuration.dart';

Future<void> main() async {
  await SentryFlutter.init(
    (options) {
      options.dsn =
          'https://**************.ingest.sentry.io/5599838';
    },
    appRunner: () => runApp(QConfig(child: MyApp())),
  );
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    Future<LoginRecoveryResult> parse = initiliazeParse();
    return new FutureBuilder<LoginRecoveryResult>(
      future: parse,
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          return MultiProvider(
            providers: [
              ChangeNotifierProvider<AuthProvider>(
                create: (context) => AuthProvider(snapshot.data.user),
              ),
              Provider<LiveSocket>(
                lazy: false,
                create: (context) => LiveSocket()..connect(),
              ),
            ],
            child: MaterialApp(
              title: 'App',
              theme: ThemeData(
                primarySwatch: Colors.pink,
                primaryColor: Color(0xFFFF1251),
                visualDensity: VisualDensity.adaptivePlatformDensity,
              ),
              home: Consumer<AuthProvider>(
                builder: (context, value, child) {
                  var user = value.current();
                  return user == null
                      ? Center(child: Text("please login"))
                      : Center(child: Text("User logged in ${user.username}"));
                },
              ),
            ),
          );
        }
        return Container(color: Color(0xFFFF1251));
      },
    );
  }

  Future<LoginRecoveryResult> initiliazeParse() async {
    var dir = await getApplicationSupportDirectory();
    // this one works. Difference from flutter version is that I'm using getApplicationSupportDirectory();
    var coreStore = await CoreStoreSembastImp.getInstance(dir.path + "/parse.db");
    // if i change import and use next line - it fails.
    // var coreStore = await CoreStoreSembastImp.getInstance();

    await Parse().initialize(
      "************************",
      "https://example.com",
      coreStore: coreStore,
      autoSendSessionId: true,
    );

    var user = await ParseUser.currentUser();
    var install = await ParseInstallation.currentInstallation();
    await install.save();
    return LoginRecoveryResult(user: user, isLoggedIn: user != null);
  }
}

class LoginRecoveryResult {
  final ParseUser user;
  final bool isLoggedIn;
  LoginRecoveryResult({this.user, this.isLoggedIn});
}
```

**Comment by xor22h** [comment]
Seems this fails due to missing path. Final exception is 
```
flutter: NoSuchMethodError: The getter 'length' was called on null.
```
which comes from as "openDatabase" inside some databaseHelper method.

iOS 14;

**Comment by xor22h** [comment]
Nevermind, seems to be solved by: https://github.com/parse-community/Parse-SDK-Flutter/pull/548
It just requires a password to be provided.
