### ISSUE TITLE
Unable to delete object

### ISSUE THREAD

**Issue by ernestasga** [parse-community/Parse-SDK-Flutter#479]
I was able to successfully create an object from my app but I'm unable to delete any.

`    var obj = ParseObject('Trip')..getObject(id);`
`    var res = await obj.delete();` 
returns

`result null`, 
`statusCode -1`, 
`error Message: DioError [DioErrorType.RESPONSE]: Http status error [404]----`

What am I missing?

**Comment by fischerscode** [comment]
The problem is in this line:
```dart
var obj = ParseObject('Trip')..getObject(id);
```
As you are using the ".." notation, your return value is `ParseObject('Trip')`. `getObject(id)` does fetch the object in the background, but the return value is not used.

This should work:
```dart
var obj = await ParseObject('Trip').getObject(id);
var res = await obj.delete();
```

**Comment by ernestasga** [comment]
Line
   ` var obj = await ParseObject('Trip').getObject(id);` returns `ParseResponse` object which does not have method `delete()`

**Comment by fischerscode** [comment]
Sorry, you are right.
You have to unwrap the `ParseObject` first.
Like this:
```dart
ParseObject obj = (await ParseObject('Trip').getObject(id)).results.first;
```

**Comment by ernestasga** [comment]
Thanks, this worked well.
