### ISSUE TITLE
Login with email only

### ISSUE THREAD

**Issue by ernestasga** [parse-community/Parse-SDK-Flutter#483]
`ParseUser()` constructor requires 3 parameters: username, email and password. How would I login with email only, without username?

**Comment by RodrigoSMarques** [comment]
Create the user and place the email in the user field.
Use null in e-mail Field

```dart
final ParseUser parseUser = ParseUser(email.toLowerCase(), password, null);
```

**Comment by ernestasga** [comment]
Thanks, it's easier than I thought it would be
