### ISSUE TITLE
Error management after migration to 2.0.0

### ISSUE THREAD

**Issue by Chralu** [parse-community/Parse-SDK-Flutter#484]
Hi,

after migrating from `1.0.27` to `2.0.0`, I encounter an issue with error management on cloud functions.

1. Call a function that fails (or that does not exist)
```
final ParseCloudFunction myFunction = ParseCloudFunction("notDefined");
final response = await myFunction.execute();
```

2. `execute()` will raise an exception instead of returning a `ParseResponse` object.

Is that change of behavior intended ?

**Comment by fischerscode** [comment]
@Chralu 
I think this is related to #481 and considered to be a bug.
Could you please try if [this change](https://github.com/parse-community/Parse-SDK-Flutter/issues/481#issuecomment-707612970) fixes the problem?
1. `git clone https://github.com/fischerscode/Parse-SDK-Flutter.git`
2. `git checkout dio-error-response`
3. open `packages/flutter/pubspec.yaml` and replace `parse_server_sdk: ^2.0.0` with
```yaml
  parse_server_sdk:
    path: ../dart
```
4. open your apps `pubspec.yaml` and replace `parse_server_sdk_flutter: ^2.0.0` with
```yaml
  parse_server_sdk_flutter:
    path: pathToTheClonedRepo/packages/flutter
```

**Comment by Chralu** [comment]
@fischerscode 
I agree, it seems to be the same issue as #481.

The change does not fix the problem : `ParseCloudFunction:execute` is not wrapped in `try catch`.

Adding `try catch` seems to fix the problem though : 

```dart
  Future<ParseResponse> execute(
      {Map<String, dynamic> parameters, Map<String, String> headers}) async {
    final String uri = '${_client.data.serverUrl}$_path';
    if (parameters != null) {
      _setObjectData(parameters);
    }
    try {
      final Response<String> result = await _client.post<String>(uri,
          options: Options(headers: headers),
          data: json.encode(_getObjectData()));
      return handleResponse<ParseCloudFunction>(
          this, result, ParseApiRQ.execute, _debug, parseClassName);
    } on Exception catch (e) {
      return handleException(e, ParseApiRQ.getConfigs, _debug, parseClassName);
    }
}
```

**Comment by fischerscode** [comment]
@Chralu 
I've created https://github.com/fischerscode/Parse-SDK-Flutter/commit/a6ebc41cf841444f8bea1745c60bf5af61ef83aa
Thanks for the issue, I will merge #482 soon.
