### ISSUE TITLE
v2.0 probably has performance issue in web app

### ISSUE THREAD

**Issue by gorillatapstudio** [parse-community/Parse-SDK-Flutter#489]
I tested back and force several times and am pretty sure that comparing to 1.7 and 2.0, my app is 5-6 times faster when loading or switching tab to a whole page of network images. In 1.7, it takes around 0.5 second while on 2.0, it takes 3-4 seconds. It might be slower on ios/android too but not very noticeable.

I also noticed that in 1.7, the switching of tabs is async while on 2.0, the switching is not available until the content is loaded which seems to be synchronous, which is weird.

**Comment by fischerscode** [comment]
With 2.0.0, we switched from [http](https://pub.dev/packages/http) to [dio](https://pub.dev/packages/dio).
> In 1.7, it takes around 0.5 second while on 2.0, it takes 3-4 seconds.

Personally, I haven't discovered a difference, but I've not done any bench marking.
Can you provide some kind of example, where a difference is noticeable?

> I also noticed that in 1.7, the switching of tabs is async while on 2.0, the switching is not available until the content is loaded which seems to be synchronous, which is weird.

Can you provide an example where this problem occurs?
For me, there is no delay when switching tabs, but I am almost exclusively using `ParseLiveListWidgets`.

**Comment by gorillatapstudio** [comment]
Thanks for the reply, @fischerscode ! I just set up two websites for comparison.
[1.0.27](https://artisse.us/) 
[2.0.0](https://artisse.us/web_v2/index.html#/)
it is pretty noticeable by eye.

I used standard iOS tab widget and I also just tested using the Android tab widget (on a bigger screen, the view will automatically use android tab). Either way, it has a big performance drop when switching to v2.

**Comment by fischerscode** [comment]
@gorillatapstudio 
I agree, there is definitively a difference noticeable. :-)
I assume, you build both sites using the same flutter version./The issue is also present, when using the same flutter version for building.

**Comment by gorillatapstudio** [comment]
Yes, both are built from exactly the same environment 20 min ago with only the difference of SDK version change, refactor of library names at imports, and adding web app name, version at parse init.

**Comment by gorillatapstudio** [comment]
FYI I will keep these two links working for the near future so that you guys can check it out.

**Comment by fischerscode** [comment]
Great, I will try to investigate further.
Are you using ParseFileWeb? Or how are you loading the images?

**Comment by gorillatapstudio** [comment]
Thanks! I am just using the Image.network as follows and the imageUrl is get<ParseFileBase>("imageFile").url

`if (kIsWeb) {
      return Image.network(
        imageUrl,
        fit: fit,
        width: width,
        height: height,
      );
    } else {
      return CachedNetworkImage(
        imageUrl: imageUrl,
        width: width,
        height: height,
        fit: fit,
        placeholder: placeholder,
      );
    }`

**Comment by gorillatapstudio** [comment]
@fischerscode  would it be possible to provide two options of http sdk when init the parse server just like the storage option? I am very excited to use the latest version of the parse-sdk-flutter but the performance regression is too big to move forward for my project. Does anyone else experience the same performance issue? Thanks!

**Comment by fischerscode** [comment]
> would it be possible to provide two options of http sdk when init the parse server just like the storage option?

That might be a solution.

@gorillatapstudio 
I've been able to reproduce this issue downloading 1mb testfiles on web using dio and http.
So it seems like this is an performance issue with dio on web.

```dart
// activate the download here: https://www.speedtestx.de/
import 'package:dio/dio.dart' as dio;
import 'package:http/http.dart' as http;

void main() async {

  await getHttp();
  await getDio();
}

Future<void> getDio() async {
  DateTime start = DateTime.now();
  try {
    await dio.Dio().get("https://www.speedtestx.de/testfiles/data_1mb.test");
    print("Dio: ${DateTime.now().difference(start)}");
  } catch (e) {
    print(e);
  }
}

Future<void> getHttp() async{
  DateTime start = DateTime.now();
  try {
    await http.get("https://www.speedtestx.de/testfiles/data_1mb.test");
    print("Http: ${DateTime.now().difference(start)}");
  } catch (e) {
    print(e);
  }
}
```

**Comment by gorillatapstudio** [comment]
What does your benchmark look like? For my application, i think it is 4-5 times or even more.

**Comment by fischerscode** [comment]
@gorillatapstudio 
It was up to 9 times slower on web.
> would it be possible to provide two options of http sdk when init the parse server just like the storage option

I am working on this. This way, the developer can tell the sdk to use a client based on http and when a progresscallback is needed, the dio version can be used for this operation. ([branch](https://github.com/fischerscode/Parse-SDK-Flutter/tree/issue-489))

**Comment by gorillatapstudio** [comment]
that's great! Thanks! In future, I guess it would be great to use feature flags to introduce such big changes so that it will be easier to switch between them, make comparison, or sometimes have both options eventually.

**Comment by gorillatapstudio** [comment]
@fischerscode  do you have an ETA of a working branch that we can choose between Http or Dio? thanks! I am really looking forward to that!

**Comment by fischerscode** [comment]
@gorillatapstudio 
I am working on such a branch, but I can't don't know when it is finished. I will notify you if it is ready for testing.

**Comment by fischerscode** [comment]
@gorillatapstudio 
I've pushed some commits to [this branch](https://github.com/fischerscode/Parse-SDK-Flutter/tree/issue-489).
From a short test, setting http as the used client seems to work. But more testing is definitely required.
You can give it a try by setting this in you pubspec.yaml:
```yaml
  parse_server_sdk_flutter:
    git:
      url: git://github.com/fischerscode/Parse-SDK-Flutter.git
      ref: issue-489
      path: packages/flutter
```
and providing a custom ParseClientCreator at you `Parse().initialize` call:
```dart
Parse().initialize(
...
clientCreator: ({bool sendSessionId, SecurityContext securityContext}) =>
    ParseHTTPClient(sendSessionId: sendSessionId, securityContext: securityContext),
);
```

**Comment by fischerscode** [comment]
In case we merge #495, this might be a great opportunity to change the "securityContext-option".
Currently the `SecurityContext` (part of `dart:io`) is stored inside `ParseCoreData`.
After merging #495, this option could be removed, as the developer could specify the `SecurityContext` using a custom `ParseClientCreator`.
This would remove one more part of `dart:io` from the package, which is good for web support.

**Comment by gorillatapstudio** [comment]
@fischerscode  the branch works fine for me. The web loading speed super fast again! thank you so much!
Is it possible to push this change together with the issue-490 so that web can be fully functional! thanks! Are we expecting a new release soon?

**Comment by fischerscode** [comment]
@gorillatapstudio 
Great to hear this!
I think there is currently a bug with the error management in #495. I will investigate before merging it.
In addition to this, I will update the Readme first.
But for now, I've created [this branch](https://github.com/fischerscode/Parse-SDK-Flutter/tree/production-branch-2).
It's the branch I'm currently using in my project.
> Are we expecting a new release soon?

Only @phillwiggins has access to the pub.dev site. So I can't guaranty you, when the next release (I think 2.1.0) will be.
But I think it is better to test the changes made in #495 for at least a week before releasing the next version.

**Comment by phillwiggins** [comment]
@fischerscode - Let me know when you want the next release is ready to go out. I'm taking a back seat on this at the moment but I'm around to push releases as and when.

**Comment by gorillatapstudio** [comment]
@fischerscode  thanks a lot for making it work so fast! Looking forward to the 2.1!

**Comment by fischerscode** [comment]
@phillwiggins 
Great, I will create a PR to master as soon as I think we should create a new release.
Releasing the current development state as 2.0.2 might be an idea, as it fixes a problem developers have when using back4app in combination with a web project, it would be a 'small' release.
Let me know what you think, I could prepare the release.
Btw: Don't worry about my PR's to development too much. I simply prefer merging using PR's as it adds makes the changes easier to understand.

**Comment by phillwiggins** [comment]
@fischerscode I'd probably follow the practice of prepping the development branch as the release candidate. Make all the changes to development so that it is ready to release, create a PR to master and I will release it in that state. That way development stays in sync with master.

I'd probably also start to adopt the version codes as something like 2.2.0 rather than 2.0.2. 
First digit is major release
Second digit is minor release
Third digit is reserved for hotfixes

What's your thoughts?

**Comment by RodrigoSMarques** [comment]
Hi @phillwiggins / @fischerscode 
I suggest adopting the semantic pattern:
https://semver.org

- MAJOR version when you make incompatible API changes,
- MINOR version when you add functionality in a backwards compatible manner, and
- PATCH version when you make backwards compatible bug fixes.

I would put this version as 2.1.0

**Comment by phillwiggins** [comment]
@RodrigoSMarques - Agreed.  I think your explanation is the same as mine but much clearer.

**Comment by fischerscode** [comment]
@phillwiggins @RodrigoSMarques 
Sounds good, I thought third digit is very small changes, but hot fixes makes more sens I guess.

**Comment by RodrigoSMarques** [comment]
Exact.
I work as follows.
It is a bug fix, increase the PATCH = x.x.1
It is an improvement, increases MINOR and restarts PATCH = x.1.x
It is an improvement but it generates any incompatibility (BREAKING CHANGES), increases MAJOR, restarts MINOR and PATCH = 2.x.x

**Comment by gorillatapstudio** [comment]
Yes totally agree!

**Comment by fischerscode** [comment]
@phillwiggins 
> Make all the changes to development so that it is ready to release, create a PR to master and I will release it in that state.

I can do it like this. The only problem is that this would temporarily break the development branch, as the `parse_server_sdk` dependency in `packages/flutter/pub.dev` would have to point to a non existing pub.dev release.

**Comment by fischerscode** [comment]
@gorillatapstudio 
> I think there is currently a bug with the error management in #495. I will investigate before merging it.

This is fixed, it was just a copy-past mistake. (https://github.com/fischerscode/Parse-SDK-Flutter/commit/afe48040dfcc0d0df368ed634b57d3e3449971c2)
Please let me know if you encounter any problems.

**Comment by gorillatapstudio** [comment]
it works for me so far!

**Comment by Mohsen7s** [comment]
I also face the same performance downgrade. I coudnt migrate to version 2 because its like ten times slower!
Is there any ETA on when releasing 2.1 ? 
We really need it

**Comment by RodrigoSMarques** [comment]
Version 2.1 has been released.
The default client is Http again and the slowing problem should not be occurring.
It will be the discretion of the developer to use the additional features of the DIO.
