### ISSUE TITLE
loginAnonymous not working without Masterkey?

### ISSUE THREAD

**Issue by nstrelow** [parse-community/Parse-SDK-Flutter#492]
Is this the correct behavior?

I recently found out the Masterkey should not be provided to a client app.
Now I was not able to create an anonymous user using `loginAnonymous`.

I wonder if this is intended behavior?
Do user logins usually require the Masterkey? Is it the same with 3rd party logins?

**Comment by RodrigoSMarques** [comment]
hi @nstrelow 
This behavior is not expected.
Did you enable the anonymous option on your server?
Using the masterkey you should be able to use anonymous login, even if it was disabled, as the key with more privileges in Parse.

**Comment by nstrelow** [comment]
Interesting. Thanks for your input.

[Doc ](http://parseplatform.org/parse-server/api/master/ParseServerOptions.html) says it defaults to true 
> enableAnonymousUsers | Boolean | Enable (or disable) anonymous users, defaults to **true**.

Will check if explicitly setting it works.

**Comment by nstrelow** [comment]
Closing this, as this seems to be related to my heroku setup and not to the flutter sdk.
