### ISSUE TITLE
flutter-web: use package_info_plus

### ISSUE THREAD

**Issue by fischerscode** [parse-community/Parse-SDK-Flutter#496]
In order to improve the development experience um flutter web, we could use [package_info_plus](https://pub.dev/packages/package_info_plus) instead of [package_info](https://pub.dev/packages/package_info).

As package_info_plus supports web, [this](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/docs/migrate-2-0-0.md#optional-provide-app-information-on-web) would not be required anymore.

**Comment by RodrigoSMarques** [comment]
@fischerscode 
Good idea. If we have a package that runs on the web, it is better than having this information as initialize parameters.
