### ISSUE TITLE
ParseUser.signup return null response

### ISSUE THREAD

**Issue by elobeparfait** [parse-community/Parse-SDK-Flutter#498]
After migrating from version 1.0.26 to 2.0.0 when I try to signup new user, the response return null. Please I need help. I even upgraded to version 2.0.1 but nothing fix. When I use ParseUser.create a new user is created online in the User class but when i try to get the currentUser.objectId on device it return null. This is the code I use to signup user:
`void signUp({String email, String pass, String username}) async {
    print("SignUp started");
    ParseUser user = ParseUser.createUser(username, pass, email);
    print(user);
    ParseResponse response = await user.signUp();
    print(response);
    if (response.success) {
      print("SignUp Success");
    } 
  }
`

**Comment by RodrigoSMarques** [comment]
Hi @elobeparfait 

Some questions:
- Are you using Flutter? Confirm which package you are using. Place the pubspec.yaml declaration here.
- When starting Parse (Parse (). Initialize (...)), are you using the coreStore parameter?

**Comment by elobeparfait** [comment]
Yes am using flutter and this is my pubspec.yaml:
`cupertino_icons: ^0.1.3
  country_code_picker: ^1.3.15
  cached_network_image: ^2.2.0+1
  flutter_show_more: ^0.1.2
  sqflite: ^1.3.1+2
  image_cropper: ^1.2.3
  shared_preferences: ^0.5.12+2 
  image_picker: ^0.6.7+1
  font_awesome_flutter: ^8.5.0
  parse_server_sdk_flutter: ^2.0.1
  url_launcher: ^5.4.11
  simple_s3: ^0.2.1
  chat_pickers: ^0.2.2
  file_picker: ^1.12.0
  clay_containers: ^0.2.2
  flutter_reaction_button: ^1.0.1
  flutter_fullpdfview: ^1.1.2
  connectivity: ^0.4.8+6
  intl: ^0.16.1
  permission_handler: ^5.0.1+1
  loading_indicator: ^1.2.0
  percent_indicator: ^2.1.5
  flutter_typeahead: ^1.8.6
  device_info: ^0.4.2+4
  image_slider: ^1.0.2
  dio: ^3.0.10
  amazon_cognito_identity_dart: ^0.0.22
  firebase_storage: ^4.0.0
  async: ^2.4.2
  fluentui_icons: ^0.2.0
  emoji_text_support: ^1.0.0+5
  animate_icons: ^0.0.4
  flutter_map: ^0.10.1+1
  firebase_auth: ^0.18.1+2
  firebase_core: "^0.5.0+1"`

and this is how i initialized parse:
`Parse().initialize(
    ParseConst.appId, 
    ParseConst.serverUrl,
    masterKey: ParseConst.masterKey,
    autoSendSessionId: true,
    liveQueryUrl: ParseConst.liveQueryUrl,
    debug: true,
    coreStore: await CoreStoreSharedPrefsImp.getInstance(),
  );`

**Comment by RodrigoSMarques** [comment]
The Version its correct.
Try chaged corestore to Sembast and change password
```dart
coreStore: await CoreStoreSembastImp.getInstance(password: 'put your password here'),
```

I identified a problem using sharedpreference. I didn't have time to analyze.
With Sembast it's OK

**Comment by elobeparfait** [comment]
ok let me try with Semblast thanks very much

**Comment by elobeparfait** [comment]
Everything worked fine with Semblast

**Comment by fischerscode** [comment]
Well, that's weird.
Just to clarify:
So you used the `CoreStoreSharedPrefsImp` `CoreStore` and user sign up didn't work. And after you switched to `CoreStoreSembastImp` it worked.

Are you using `parse_server_sdk: ^2.0.1` or `parse_server_sdk_flutter: ^2.0.1`?
Did you migrate using [this](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/docs/migrate-2-0-0.md) guide?
Did you especially perform [step 2](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/docs/migrate-2-0-0.md#2-imports)?

**Comment by RodrigoSMarques** [comment]
@fischerscode 

He already answered above.
He posted pubspec.yaml. You are using parse_server_sdk_flutter 2.0.1

Some of my students also had a problem with sharedpreference in version> 2.0.0

I didn't analyze the error, but it instructs everyone to use Sembast and it's working.

**Comment by fischerscode** [comment]
@RodrigoSMarques 
> He posted pubspec.yaml. You are using parse_server_sdk_flutter 2.0.1

My bad, didn't saw that.

> Some of my students also had a problem with sharedpreference in version> 2.0.0
> I didn't analyze the error, but it instructs everyone to use Sembast and it's working.

Interesting, so this means it should be easy to reproduce the issue.

**Comment by RodrigoSMarques** [comment]
@fischerscode 
I don't have a lucky day.

I just did the test to post the error and the error did not occur, it worked.

I need to sleep. I'm seeing errors where they don't exist.

But, an error appeared when calling getString () at startup, stating that it was null.

It appears that he did not save the user's information.

If I get the code from a student with a problem, I will analyze it.

**Comment by fischerscode** [comment]
@RodrigoSMarques 
> I need to sleep.

It's the same for me. :-)

Currently user sign up is disabled on my test-server. I will try to reproduce this tomorrow.

I am just skeptical about the fact that the `CoreStoreSharedPrefsImp` should be the problem.
It should just store the data after the signup was successful. I can't see why it should break something.

**Comment by fischerscode** [comment]
> `void signUp({String email, String pass, String username}) async { print("SignUp started"); ParseUser user = ParseUser.createUser(username, pass, email); print(user); ParseResponse response = await user.signUp(); print(response); if (response.success) { print("SignUp Success"); } } `

For me, your function works while using the `CoreStoreSharedPrefsImp`.


I assume you did not provide an email. This results in a null response. https://github.com/parse-community/Parse-SDK-Flutter/blob/540190b2fc900a9b1dd6c2615ca2ea57877d3ca7/packages/dart/lib/src/objects/parse_user.dart#L159-L161
And a after you switched to the `CoreStoreSembastImp`, it appease like the email has been not `null` for some reason.

**Comment by elobeparfait** [comment]
> > `void signUp({String email, String pass, String username}) async { print("SignUp started"); ParseUser user = ParseUser.createUser(username, pass, email); print(user); ParseResponse response = await user.signUp(); print(response); if (response.success) { print("SignUp Success"); } } `
> 
> For me, your function works while using the `CoreStoreSharedPrefsImp`.
> 
> I assume you did not provide an email. This results in a null response.
> 
> https://github.com/parse-community/Parse-SDK-Flutter/blob/540190b2fc900a9b1dd6c2615ca2ea57877d3ca7/packages/dart/lib/src/objects/parse_user.dart#L159-L161
> 
> 
> And a after you switched to the `CoreStoreSembastImp`, it appease like the email has been not `null` for some reason.

You are right my the email was null, I made an error while passing the email parameter.

**Comment by fischerscode** [comment]
> You are right my the email was null, I made an error while passing the email parameter.

 👍 
Thanks for opening this issue. I've created a PR (#502) that should prevent other developers from running into the same issue.

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
