### ISSUE TITLE
ParseUser login() method returns false (web)

### ISSUE THREAD

**Issue by kharitonovAL** [parse-community/Parse-SDK-Flutter#500]
Hi! I'm trying to login to server with already created user. But response always returns `false`.
Here is my init code:
```
void main() async {
  await Parse().initialize(
      PARSE_APP_ID,
      PARSE_APP_URL,
      masterKey: MASTER_KEY,
      // debug: true,
      autoSendSessionId: true,
      coreStore: await CoreStoreSharedPrefsImp.getInstance());

  setupServiceLocator();
  runApp(MyApp());
}
```

here is my login method:
```
Future<ParseUser> signIn({String email, String password}) async {
    ParseUser user = ParseUser(email, password, email);
    print('method signIn, user is: $user');

    ParseResponse response = await user.login();
    print('auth_service_parse.dart, method signIn, response is: ${response.error}');

    if (response.success) {
      print('user logged in with id: ${user.objectId}');
      return user;
    } else {
      print('user logging in error: ${response.error.message}');
    }

    print('user sign in is null');
    return null;



    // String url = 'http://...:1337/parse/login';
    // var body = json.encode({'username': email, 'password': password, 'email': email});
    // var response = await http.post(
    //   url,
    //   headers: {
    //     'Content-Type': 'application/json',
    //     'X-Parse-Application-Id': 'appId',
    //     'X-Parse-REST-API-Key': 'masterKey'
    //   },
    //   body: body
    // );
    //
    // print(response.body);
  }
```

if I'm using REST API instead of SDK method, the everything is OK, and response returns info about user.

How can I fix this?

Thanks!

**Comment by fischerscode** [comment]
@kharitonovAL 
> `ParseResponse response = await user.login();`

You are using the login method. In order to signup, you have to use `ParseUser().signUp()`.

**Comment by kharitonovAL** [comment]
@fischerscode 

I tried to use `ParseUser().signUp()`, but it also returns `false`. Here is modified method, where I'm signing up and then logging in:

```
Future<ParseUser> signIn({String email, String password}) async {
    ParseUser user = ParseUser(email, password, email);
    print('method signIn, user is: $user');

    user.signUp().then((singUpResponse) async {
      print('singUpResponse: ${singUpResponse.success}');

      ParseResponse response = await user.login();
      print('auth_service_parse.dart, method signIn, response is: ${response.success}');

      if (response.success) {
        print('user logged in with id: ${user.objectId}');
        return user;
      } else {
        print('user logging in error: ${response.error.message}');
      }

      print('user sign in is null');
      return null;
    });
  }
```

The console prints the following:
```
method signIn, user is: {"className":"_User","username":"t@t.com","email":"t@t.com"}
singUpResponse: false
auth_service_parse.dart, method signIn, response is: false
user logging in error: null
```

**Comment by fischerscode** [comment]
For me, your second code (the one with `user.signUp().then(`) seems to work.
But you are essentially singing up a user. As a result of that, you are logged in. And then you log in again.

The error you are getting is a little bit odd.
Could you please set `debug: true,` at your `Parse().initialize()`-call and send me the logs?
(Make sure to remove sensible data like the server URL or `X-Parse-Client-Key`)

**Comment by fischerscode** [comment]
One other idea:
Does your server prevent login without a valid email?
https://github.com/parse-community/parse-server/blob/5f261cc49f245c423f5485f7a196086b52823028/src/Options/Definitions.js#L301-L307

**Comment by kharitonovAL** [comment]
@fischerscode 
> The error you are getting is a little bit odd.
> Could you please set `debug: true,` at your `Parse().initialize()`-call and send me the logs?

Sure! Here it is:
```
method signIn, user is: {"className":"_User","username":"t@t.com","email":"t@t.com"}
╭-- Parse Request
curl -X POST -H 'X-Parse-Revocable-Session: 1' -H 'X-Parse-Installation-Id: INSTALL_ID' -H 'content-type: null' -H 'X-Parse-Application-Id: APP_ID' -H 'X-Parse-Master-Key: MASTER_KEY' http://URL/parse/classes/_User

 http://URL/parse/classes/_User
╰--
=====
null
╭-- Parse Response
Class: _User
Function: ParseApiRQ.signUp
Status Code: null
Type: null
Exception: null
╰-- 

singUpResponse: false

╭-- Parse Request
curl -X GET -H 'X-Parse-Revocable-Session: 1' -H 'X-Parse-Installation-Id: INSTALL_ID' -H 'content-type: null' -H 'X-Parse-Application-Id: APP_ID' -H 'X-Parse-Master-Key: MASTER_KEY' http://URL/parse/login?username=t%40t.com&password=fakepassword

 http://URL/parse/login?username=t@t.com&password=fakepassword
╰--
╭-- Parse Response
Class: _User
Function: ParseApiRQ.login
Status Code: null
Type: null
Exception: null
╰-- 

auth_service_parse.dart, method signIn, response is: false
user logging in error: null
```

>Does your server prevent login without a valid email?

We have default settings for this.
I edited this field for my user in dashboard and set to `true`.

**Comment by fischerscode** [comment]
This is not related to this issue, but it is not recommended to use the masterkey in a client side application, as every user (esp. on a web application) could extract this key and gain admin access to you database.

---

I think I have been able to reproduce this issue.
For me the same output appeared when using your `Future<ParseUser> signIn({String email, String password})`-method while providing an existing email and the wrong password.
Based on your server response, I assume you are using version 2.0.0. If this is the case, please upgrade to 2.0.1 for a hotfix regarding the error management.

**Comment by kharitonovAL** [comment]
@fischerscode 
> ...it is not recommended to use the masterkey in a client side application...
Do you mean I have to remove masterkey from server initialisation code?

> ...the same output appeared ... while providing an existing email and the wrong password.
I'll check it later, thanks!

>  ...please upgrade to 2.0.1 ...
I'm using   parse_server_sdk_flutter: ^2.0.1

**Comment by fischerscode** [comment]
> Do you mean I have to remove masterkey from server initialisation code?

It depends on your use case. Some functions require this to be set. If you are running you application only in a safe environment (you trust every user) it is more or less fine using the master key in you application. But if this application is available for public, it is definitely a security concern. In this case, I would rather use cloud functions for actions that require the master key.

> I'm using parse_server_sdk_flutter: ^2.0.1

OK, so maybe I recreated a n other issue. For me the log was different.

**Comment by kharitonovAL** [comment]
@fischerscode 

Hi! What our next steps? May be you need more info?

**Comment by fischerscode** [comment]
@kharitonovAL 
Sorry I've had no time doing further investigations.
Could you please give [this](https://github.com/fischerscode/Parse-SDK-Flutter/tree/release_2.0.1/packages/flutter/test_app) example a try. It uses a demo server. If it worked, please change the server to your details and try it again.

**Comment by kharitonovAL** [comment]
@fischerscode 
No need for excuses! 

I tried `test_app` with default configs and all worked. Console prints out following:
```
╭-- Parse Request
curl -X POST -H 'X-Parse-Session-Token: r:57dabdbb9fe97f9ae2581c89b188e90a' -H 'content-type: null' -H 'X-Parse-Application-Id: Parse-Demo' -H 'X-Parse-Client-Key: jyHsBFje6ShMWe6TW3FXQtuWW87HWPLx2YHFCWKS9ua8FY8nbT' https://parse-demo.thomax-it.com/parseserver/logout

 https://parse-demo.thomax-it.com/parseserver/logout
╰--
╭-- Parse Response
Class: _User
Function: ParseApiRQ.logout
Status Code: 200
Payload: {"className":"_User"}
╰-- 

╭-- Parse Request
curl -X POST -H 'X-Parse-Revocable-Session: 1' -H 'X-Parse-Installation-Id: 70487b82-ab6b-4466-8d13-5e0faf9365b4' -H 'content-type: null' -H 'X-Parse-Application-Id: Parse-Demo' -H 'X-Parse-Client-Key: jyHsBFje6ShMWe6TW3FXQtuWW87HWPLx2YHFCWKS9ua8FY8nbT' https://parse-demo.thomax-it.com/parseserver/classes/_User

 https://parse-demo.thomax-it.com/parseserver/classes/_User
╰--
╭-- Parse Response
Class: _User
Function: ParseApiRQ.signUp
Status Code: 201
Payload: {"className":"_User","objectId":"V3pggOE0A0","createdAt":"2020-11-02T18:12:40.486Z","username":"Ju3kBNtirJ@example.com","email":"Ju3kBNtirJ@example.com","sessionToken":"r:a07aa7a533703608c288c594074efa85"}
╰-- 


Sign up was success full. Response is not null.
```

But if I changes server init parameters to my own:
```
_MyAppState() : initFuture = CoreStoreSharedPrefsImp.getInstance().then(
          (CoreStore coreStore) => Parse().initialize(
            'APP_ID_HERE',
            'http://URL:1337/parse',
            // clientKey: 'jyHsBFje6ShMWe6TW3FXQtuWW87HWPLx2YHFCWKS9ua8FY8nbT',
            // liveQueryUrl: 'https://parse-demo.thomax-it.com/parseserver',
            autoSendSessionId: true,
            coreStore: coreStore,
            debug: true,
          ),
        );
```

the console prints next:
```
╭-- Parse Request
curl -X POST -H 'X-Parse-Revocable-Session: 1' -H 'X-Parse-Installation-Id: 70487b82-ab6b-4466-8d13-5e0faf9365b4' -H 'content-type: null' -H 'X-Parse-Application-Id: APP_ID_HERE' http://URL:1337/parse/classes/_User

 http://URL:1337/parse/classes/_User
╰--
╭-- Parse Response
Class: _User
Function: ParseApiRQ.signUp
Status Code: null
Type: null
Exception: null
╰-- 

Sign up was not success full. Response is not null.
```

I mentioned that I have no `clientKey`. May be this is the cause of my failures? 

Thank you!

**Comment by fischerscode** [comment]
@kharitonovAL 
You have no client key?
I think a client key is required.
Do you have a [different](https://docs.parseplatform.org/parse-server/guide/#usage) key?

**Comment by kharitonovAL** [comment]
@fischerscode 

> You have no client key?

No

> I think a client key is required.

I thought that `appId` and `masterKey` are required. Didn't know about `clientKey`. How can I set it up? Just assign a random value for `clientKey` variable in server settings?
And then every app (iOS, android or web) will be use this `clientKey`?

> Do you have a [different](https://docs.parseplatform.org/parse-server/guide/#usage) key?

No, only `masterKey`.

**Comment by fischerscode** [comment]
@kharitonovAL 
> I thought that appId and masterKey are required. Didn't know about clientKey. How can I set it up? Just assign a random value for clientKey variable in server settings?

If you are self hosting your server, you can do so.

> And then every app (iOS, android or web) will be use this `clientKey`?

If you added the `clientKey` to the SDK, it will add this key in the header every time a request gets send to the server.
In case you have also other applications communicating with your server, you will have to 'tell' them to use the `clientKey`, too.

The `clientKey` adds a small security layer, as it blocks every request that does not contain this key. As a result, you are pretty safe from random brute-force attacks. But as the key is stored on the client side, every user could decompile your application and extract the key. So it is no absolute security.

The `masterKey` can be used to gain admin access to the server.

I do not know if this SDK works when only providing a `masterKey`.

**Comment by kharitonovAL** [comment]
@fischerscode 

I added the `clientKey` and nothing changed. Same error and console prints:
```
╭-- Parse Request
curl -X POST -H 'X-Parse-Revocable-Session: 1' -H 'X-Parse-Installation-Id: aa1f2096-6f14-4577-a51e-af057a609130' -H 'content-type: null' -H 'X-Parse-Application-Id: APP_AD' -H 'X-Parse-Client-Key: KLIENT_KEY' https://URL/parse/classes/_User

 https://URL/parse/classes/_User
╰--
╭-- Parse Response
Class: _User
Function: ParseApiRQ.signUp
Status Code: null
Type: null
Exception: null
╰-- 

Sign up was not success full. Response is not null.
```

May be there is some extra setting on server that I didn't done? Can you please provide setting for your server?
Thanks!

**Comment by kharitonovAL** [comment]
@fischerscode 
Here is our main server's settings:
**.env**
```
DATABASE_URI="mongodb://localhost:27017/dev"
APP_ID="MyAppID"
MASTER_KEY="MyMasterKey"
CLIENT_KEY=‘MyClientKey’
SERVER_URL="http://localhost:1337/parse"
PARSE_SERVER_PREVENT_LOGIN_WITH_UNVERIFIED_EMAIL=true
PORT=1337
```

**app.js**
```
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  clientKey: process.env.CLIENT_KEY || '',
  autoSendSessionId: true,
  masterKey: process.env.MASTER_KEY || '', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  preventLoginWithUnverifiedEmail: true,
  allowOrigin: '*',
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  },
  supportedPushLocales: ["en", "ru"]
});
```

**start script**
`express.js app on pm2 daemon`

**Comment by fischerscode** [comment]
@kharitonovAL 
And does it work?

> `preventLoginWithUnverifiedEmail: true,`

This line might cause the issue, unless you are verifying the emails before your log in.

**Comment by kharitonovAL** [comment]
@fischerscode 

>This line might cause the issue, unless you are verifying the emails before your log in.

we set it to `false` but it have no sense.

> And does it work?

what exactly? `clientKey` didn't help. I think something wrong with settings, but don't know what exactly. Can you provide settings from your server?

**Comment by fischerscode** [comment]
@kharitonovAL 

> clientKey didn't help

Interesting. Nether the less, I would recommend you, to keep this change. 

You can find my server setup [here](https://github.com/fischerscode/k8s-ParseServer).

> we set it to `false` but it have no sense.

So after you set it to `false` nothing changed?

**Comment by kharitonovAL** [comment]
@fischerscode 

> Interesting. Nether the less, I would recommend you, to keep this change.

sure!

> You can find my server setup here.

thanks!

>So after you set it to `false` nothing changed?

yep! nothing!

**Comment by kharitonovAL** [comment]
@fischerscode 

just to be clear:

if I created user with `ParseUser().createUser()` method, the next step will be `..login()` or `..signUp()`? I understand that `signUp()` means create new user and login immediately.

**Comment by fischerscode** [comment]
I am kind a out of ideas, as the test-app works with my server and not with yours, I assume it is some kind of server configuration problem.

You are able to access data from the server without login, right?

**Comment by kharitonovAL** [comment]
> I am kind a out of ideas, as the test-app works with my server and not with yours, I assume it is some kind of server configuration problem.

yep, but what exactly? :)

> You are able to access data from the server without login, right?

Honestly, I even didn't try to access data this way, but I think I can.

**Comment by fischerscode** [comment]
> Honestly, I even didn't try to access data this way, but I think I can.

Please query a collection, that does not require authentication.
Are you using the parse-dashoard? And if you do, does it work?

**Comment by kharitonovAL** [comment]
> Please query a collection, that does not require authentication.

Ok, I'll try few hours later and will report here.

> Are you using the parse-dashoard? And if you do, does it work?

Yes, we use it. And yes, it works.

**Comment by kharitonovAL** [comment]
@fischerscode 

Actually in dashboard there is `Session` class, and every failed attempt to login or sign up is reflected there. Here are some screenshots:
![image](https://user-images.githubusercontent.com/11362629/98114199-52ff1380-1ebe-11eb-8b32-3bd5239a33ef.jpeg)

![image](https://user-images.githubusercontent.com/11362629/98114220-598d8b00-1ebe-11eb-9bbb-76a999bb84c4.jpeg)

**Comment by kharitonovAL** [comment]
@fischerscode 
> Please query a collection, that does not require authentication.

Successful! what's next?

**Comment by fischerscode** [comment]
@kharitonovAL 
Could you please try to use the `CoreStoreSembastImp` as the `CoreStore`?
(Don't forget to specify a password.)

**Comment by kharitonovAL** [comment]
@fischerscode 
> Could you please try to use the `CoreStoreSembastImp` as the `CoreStore`?

Nothing changed...

**Comment by kharitonovAL** [comment]
@fischerscode 
One more thing: I'm using Flutter from dev channel. May this be the cause of my login issues?

**Comment by kharitonovAL** [comment]
@fischerscode 
so what can we do else? may be we can schedule Zoom call and I'll share you my screen and show how everything work?

**Comment by fischerscode** [comment]
Sorry, have been busy again.

> may be we can schedule Zoom call and I'll share you my screen and show how everything work?

Might be an idea.
But first, I suggest you try a branch with more debugging. I think I am able to publish such a branch later today or tomorrow.

> One more thing: I'm using Flutter from dev channel. May this be the cause of my login issues?

I don't think that's the issue, as the example app I gave you worked on you PC with my server but not with yours.

**Comment by kharitonovAL** [comment]
> Sorry, have been busy again.

No need for apologies!

> But first, I suggest you try a branch with more debugging. I think I am able to publish such a branch later today or tomorrow.

Ok, I'll be waiting for your reply! Thanks!

**Comment by fischerscode** [comment]
@kharitonovAL 
I've published [this](https://github.com/fischerscode/Parse-SDK-Flutter/tree/signup-debuging) branch.
This branch should print debugging information when calling `signUp`.
Note: The password might be printed out.

**Comment by kharitonovAL** [comment]
@fischerscode 

Sorry that I'm bothering you with such question, but how can I install it? I'm trying to add the following in my `pub spec.yaml`:
```
parse_server_sdk_flutter:
    git:
      url: https://github.com/fischerscode/Parse-SDK-Flutter.git
      ref: signup-debuging
```

but failed with `flutter pub get` ending with error `Could not find a file named "pubspec.yaml" in git://github.com/fischerscode/Parse-SDK-Flutter.git e7c814a39c090cce58ddae2983d0038afac1fd76`

Thanks!

**Comment by kharitonovAL** [comment]
@fischerscode 
If I'll remove line `ref: signup-debuging`, then console prints the following:
```
Error on line 1, column 7: "name" field doesn't match expected name "parse_server_sdk_flutter".
  ╷                                                                     
1 │ name: parse_server_sdk                                              
  │       ^^^^^^^^^^^^^^^^                                              
  ╵                                                                     
Running "flutter pub get" in uk_web...                                  
pub get failed (65;   ╵)
```

**Comment by kharitonovAL** [comment]
@fischerscode 

> I've published this branch.

Ok, so it seems that I finally was able to checkout `signup-debuging` branch. But it's for `parse_server_sdk` and not for `parse_server_sdk_flutter`. Anyway, I just replaced `import` notations with correct one in files.

So the console log is below, and never mind about username and password for now:
```
q@q.com, 111111
method signIn, user is: {"className":"_User","username":"q@q.com","password":"111111","email":"q@q.com"}
╭-- Parse Request
curl -X POST -H 'X-Parse-Revocable-Session: 1' -H 'X-Parse-Installation-Id: 88011xxx03981' -H 'content-type: text/plain; charset=utf-8' -H 'X-Parse-Application-Id: xxx' -H 'X-Parse-Client-Key: xxx' -d '{"username":"q@q.com","password":"111111","email":"q@q.com"}' https://xxx/parse/classes/_User
 https://xxx/parse/classes/_User
╰--

╭-- Parse Response
Class: _User
Function: ParseApiRQ.signUp
Status Code: -1
Type: UnknownError
Exception: XMLHttpRequest error.
╰--

singUpResponse: false
╭-- Parse Request
curl -X GET -H 'X-Parse-Revocable-Session: 1' -H 'X-Parse-Installation-Id: 880116xxxc7503981' -H 'X-Parse-Application-Id: xxx' -H 'X-Parse-Client-Key: xxx' https://xxx/parse/login?username=q%40q.com&password=111111
 https://xxx/parse/login?username=q@q.com&password=111111
╰--
╭-- Parse Response
Class: _User
Function: ParseApiRQ.login
Status Code: -1
Type: UnknownError
Exception: XMLHttpRequest error.
╰--
auth_service_parse.dart, method signIn, response is: false
user logging in error: XMLHttpRequest error.
```

I tried both, `signUp()` and `login()` methods, and both failed

**Comment by fischerscode** [comment]
@kharitonovAL 
> but how can I install it

Use this in your applications pubspec.yaml
```yaml
  parse_server_sdk_flutter:
    git:
      url: git://github.com/fischerscode/Parse-SDK-Flutter.git
      ref: signup-debuging
      path: packages/flutter
```

> field doesn't match expected name "parse_server_sdk_flutter"

I think there has been something wrong with the import.

> Ok, so it seems that I finally was able to checkout signup-debuging branch. But it's for parse_server_sdk and not for parse_server_sdk_flutter. Anyway, I just replaced import notations with correct one in files.

As your log does not contain [this log](https://github.com/fischerscode/Parse-SDK-Flutter/blob/e7c814a39c090cce58ddae2983d0038afac1fd76/packages/dart/lib/src/objects/parse_user.dart#L157). I assume there was a problem at the dependencies.

You should not have to change any imports. I think you run into errors, as you probably used the `packages/dart` path and not the `packages/flutter` path.

**Comment by kharitonovAL** [comment]
@fischerscode 

> Use this in your applications pubspec.yaml

Thank you so much! It installed successfully! Here are logs:

```
t@t.com, 111111
method signIn, user is: {"className":"_User","username":"t@t.com","email":"t@t.com"}
ParseSDK: signUp started
ParseSDK: forgetLocalSession started
ParseSDK: forgetLocalSession finished
ParseSDK: [signUp] url = https://xxx/parse/classes/_User
ParseSDK: [signUp] body = {"username":"t@t.com","email":"t@t.com","password":"111111"}
ParseSDK: _saveChanges started
ParseSDK: _saveChanges finished
ParseSDK: [signUp] installationId = 0ce44d5d-xxx-a5da82c54235
╭-- Parse Request
curl -X POST -H 'X-Parse-Revocable-Session: 1' -H 'X-Parse-Installation-Id: 0ce44d5d-xxx-a5da82c54235' -H 'content-type: null' -H 'X-Parse-Application-Id: xxx' -H 'X-Parse-Client-Key: xxx' https://xxx/parse/classes/_User

 https://xxx/parse/classes/_User
╰--
ParseSDK: [signUp] caught: DioError [DioErrorType.RESPONSE]: XMLHttpRequest error.
╭-- Parse Response
Class: _User
Function: ParseApiRQ.signUp
Status Code: null
Type: null
Exception: null
╰-- 

singUpResponse: false
ParseSDK: forgetLocalSession started
ParseSDK: forgetLocalSession finished
ParseSDK: _saveChanges started
ParseSDK: _saveChanges finished

╭-- Parse Request
curl -X GET -H 'X-Parse-Revocable-Session: 1' -H 'X-Parse-Installation-Id: 0ce44d5d-xxx-a5da82c54235' -H 'content-type: null' -H 'X-Parse-Application-Id: xxx' -H 'X-Parse-Client-Key: xxx' https://xxx/parse/login?username=t%40t.com&password=111111

 https://xxx/parse/login?username=t@t.com&password=111111
╰--
╭-- Parse Response
Class: _User
Function: ParseApiRQ.login
Status Code: null
Type: null
Exception: null
╰-- 

auth_service_parse.dart, method signIn, response is: false
user logging in error: null
user sign in is null
```

**Comment by kharitonovAL** [comment]
@fischerscode 

Hi, I'm sorry for bothering you, and you are probably busy, but have you already took a look at the logs that I posted?
Thanks!

**Comment by fischerscode** [comment]
@kharitonovAL 
It seems like `parseUser.signUp()` works as expected.
Both `login()`-calls used your login function and not `parseUser.login()`, right?
Please set a breakpoint in the `catch` block of the `signUp()` method and inspect the exception `e`.
Some information about that error might be useful.

**Comment by danibjor** [comment]
Testing with a new Flutter project, added support for Web/Desktop too in this one.

Here testing in browser.
First init parse

```
await Parse().initialize(
    'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', // app id
    'https://x.x.x/instance',
    coreStore: await CoreStoreSembastImp.getInstance(),
    debug: true,
    autoSendSessionId: true,
  );
```

Create a User object

```
  ParseUser user = ParseUser('user', 'pass', 'x.x@x.x');
  print('user is: $user');
```

Prints result

```
user is: {"className":"_User","username":"user","email":"x.x@x.x"}
```

Then do a

```
  ParseResponse response = await user.login();
  print('auth_service_parse.dart, method signIn, response is: ${response.success}');
  if (response.success) {
    print('user logged in with id: ${user.objectId}');
  } else {
    print('user logging in error: ${response.error.message}');
  }
```

Prints this response

```
-- Parse Request
curl -X GET -H 'X-Parse-Revocable-Session: 1' -H 'X-Parse-Installation-Id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' -H 'content-type: null' -H 'X-Parse-Application-Id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' https://x.x.x/instance/login?username=user&password=pass
 https://x.x.x/instance/login?username=user&password=pass
╰--
╭-- Parse Response
Class: _User
Function: ParseApiRQ.login
Status Code: null
Type: null
Exception: null
╰--
auth_service_parse.dart, method signIn, response is: false
user logging in error: null

```

Then do a fetch with the http package

```
  var url = 'https://x.x.x/instance/login?username=user&password=pass';

  var res = await http.get(
    url,
    headers: {
      'X-Parse-Application-Id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
    },
  );

  print(res.body);
```
That prints out
```
{"objectId":"xXXxXXxXxX","emailVerified":true,"username":"user","createdAt":"2020-11-12T10:31:05.361Z","updatedAt":"2020-11-12T10:42:05.770Z","email":"x.x@x.x","ACL":{"*":{"read":true},"xXXxXXxXxX":{"read":true,"write":true}},"sessionToken":"r:000x0xx00xx00xx0000000xx0x0x00x00"}
```

Same if I do a GET from Postman/Insomnia - get a user object back when trying to login. 

Requests from Postman/Insomnia and http-package generates new rows in the session table. UserObject.login() does not.

Something is fishy when it runs in the browser.

Tested with both
```
  parse_server_sdk_flutter:
    git:
      url: git://github.com/fischerscode/Parse-SDK-Flutter.git
      ref: signup-debuging
      path: packages/flutter  
```
and 
```
  parse_server_sdk_flutter: any
```

**Comment by danibjor** [comment]
Workaround until fix is in place

```
// login helper
Future<ParseUser> signIn(String username, String password) async {
  var url = '$serverUrl/login?username=$username&password=$password';
  // login in using http package
  var res = await http.get(
    url,
    headers: {
      'X-Parse-Revocable-Session': '1',
      'X-Parse-Application-Id': appId,
    },
  );
  // grab response and decode json
  var jsonObject = json.decode(res.body);
  // grab session token 
  var token = jsonObject['sessionToken'];
  // log in via Parse using session token, setting SDK up with a user as if we logged in normally  
  var response = await ParseUser.getCurrentUserFromServer(token);
  // return current user 
  return response.result;
}
```

Usage: 

```
  var user = await ParseUser.currentUser();

  if (user == null) {
    print('no existing user - fetching from server');
    user = await signIn(username, password);
  } else {
    print('found existing user - skipping roundtrip to server');
  }

  print('user');
  print(user);
```

**Comment by fischerscode** [comment]
Are you both using back4app? If yes, this might be related to #490.

**Comment by kharitonovAL** [comment]
> Are you both using back4app? If yes, this might be related to #490.

No! I forked git from Parse Server community

**Comment by danibjor** [comment]
> Are you both using back4app? If yes, this might be related to #490.

No, self hosted on Docker.

**Comment by fischerscode** [comment]
And did you allow the installation header? (https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/flutter#web-support)

**Comment by danibjor** [comment]
> And did you allow the installation header? (https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/flutter#web-support)

> When running directly via docker, set the env var PARSE_SERVER_ALLOW_HEADERS=X-Parse-Installation-Id. When running via express, set ParseServerOptions allowHeaders: ['X-Parse-Installation-Id']

Setting the ENV VAR in Docker did not help, but adding ´allowHeaders: ['X-Parse-Installation-Id']` to the `ParseServerOptions` did the trick. Thanks @fischerscode.

**Comment by kharitonovAL** [comment]
> > And did you allow the installation header? (https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/flutter#web-support)
> 
> > When running directly via docker, set the env var PARSE_SERVER_ALLOW_HEADERS=X-Parse-Installation-Id. When running via express, set ParseServerOptions allowHeaders: ['X-Parse-Installation-Id']
> 
> Setting the ENV VAR in Docker did not help, but adding `allowHeaders: ['X-Parse-Installation-Id']` to the `ParseServerOptions` did the trick. Thanks @fischerscode.

same for me, now everything works!
@danibjor  and @fischerscode , that you guys!
