### ISSUE TITLE
Cloud function does not provide user to backend

### ISSUE THREAD

**Issue by mishachesnokov** [parse-community/Parse-SDK-Flutter#504]
request.user is empty in cloud function on backend.
Seems like intended (or maybe not finished) behaviour of plugin since there is nothing about current user's session token being included into request headers.
If I do like this:
`var headers = {"X-Parse-Session-Token": currentUser.sessionToken};
final ParseResponse result =
        await function.execute(parameters: params, headers: headers);`
then backend of course provides request.user

I am not that pro to understand fully/correctly the code of the plugin. Please approve or decline my point of view. 
Thanks.

**Comment by fischerscode** [comment]
@mishachesnokov 
I think this is intended, as every program should send as few information about the user to the server as possible.

If your cloud function needs the user information, you should either use `ParseCloudFunction("functionName", autoSendSessionId: true)` or set `autoSendSessionId: true` in your `Parse.initialize()` call.

Please let me know setting `autoSendSessionId` solves your problem, as it should be a bug if it doesn't.

**Comment by RodrigoSMarques** [comment]
@fischerscode 
This problem with the autoSendSessionId parameter is common.
I see no reason for it to be false by default.
I checked the ParseHTTPClient and if there is no X-Parse-Session-Token, the value is not sent, so we have no impact.
I will send a PR to make it true by default.

**Comment by fischerscode** [comment]
@RodrigoSMarques 
I think `autoSendSessionId` is false by default, as it regulates the amount of of data, the server gets from the clients.
But I think, as long as we mention it in the change log, setting the default to true is fine, as everybody who wants the old behavior can easily set it to false at the initialize call.

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.

**Comment by adolfokrah** [comment]
> var headers = {"X-Parse-Session-Token": currentUser.sessionToken};

when autoSendSessionId is set to true, This is the response of the header in the cloud code

headers: {
    'user-agent': 'Flutter Parse SDK 3.1.0',
    'x-parse-session-token': 'r:78a9cf628b5da073c0135ef0e43e8bb2',
    'x-parse-application-id': 'app-d5a255b9ff7187c535ae24e6245e2163',
    'accept-encoding': 'gzip',
    'content-length': '2',
    host: '192.168.1.101:1337',
    'x-parse-master-key': 'master-60fcca29aaa0a2db48de26da021dd85f',
    'content-type': 'text/plain; charset=utf-8',
    'x-parse-client-key': 'client-86be6a70eafc1cb279e81b1fa48c52d6'
  },
  
  but yet still  req.user is undefined.
  
  {
  params: {},
  master: true,
  user: undefined,
  installationId: undefined,
  log: LoggerController {
    options: {
      jsonLogs: false,
      logsFolder: './logs/',
      verbose: false,
      logLevel: undefined,
      silent: undefined,
      maxLogFiles: undefined
    },
    appId: 'app-d5a255b9ff7187c535ae24e6245e2163',
    debug: [Function (anonymous)],
    verbose: [Function (anonymous)],
    silly: [Function (anonymous)],
    [Symbol()]: WinstonLoggerAdapter {}
  },
  headers: {
    'user-agent': 'Flutter Parse SDK 3.1.0',
    'x-parse-session-token': 'r:78a9cf628b5da073c0135ef0e43e8bb2',
    'x-parse-application-id': 'app-d5a255b9ff7187c535ae24e6245e2163',
    'accept-encoding': 'gzip',
    'content-length': '2',
    host: '192.168.1.101:1337',
    'x-parse-master-key': 'master-60fcca29aaa0a2db48de26da021dd85f',
    'content-type': 'text/plain; charset=utf-8',
    'x-parse-client-key': 'client-86be6a70eafc1cb279e81b1fa48c52d6'
  },
  ip: '::ffff:192.168.1.102',
  functionName: 'getWalletBalance',
  context: {}
}
