### ISSUE TITLE
ParseInstallation Issue

### ISSUE THREAD

**Issue by maravilhosinga** [parse-community/Parse-SDK-Flutter#505]
When i run this cocde

```
ParseInstallation installation = await ParseInstallation.currentInstallation();
ParseResponse response = await installation.create();
```

I get rhis error and Installation doesn’t create.

[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'isNotEmpty' was called on null.

**Comment by RodrigoSMarques** [comment]
@maravilhosinga 
Some questions:
Which target platform Flutter (Mobile or Web) or Dart?
What version of the package are you using?
If it is a version greater than 2.0.0. Did you follow the migration guide?
[https://github.com/parse-community/Parse-SDK-Flutter/issues/477](https://github.com/parse-community/Parse-SDK-Flutter/issues/477)

**Comment by ken1020** [comment]
> When i run this cocde
> 
> ```
> ParseInstallation installation = await ParseInstallation.currentInstallation();
> ParseResponse response = await installation.create();
> ```
> 
> I get rhis error and Installation doesn’t create.
> 
> [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'isNotEmpty' was called on null.

You can use REST API for installation instance saving, and let ParseInstallation object just generate installation_id, like this:

final ParseInstallation installation = await ParseInstallation.currentInstallation();

Response dioResponse;

    var dio = Dio(BaseOptions(
      headers: {
        "X-Parse-Application-Id" : "xxx",
        "X-Parse-REST-API-Key" : "xxx",
      },
      contentType: Headers.jsonContentType,
      responseType: ResponseType.plain,
    ));

    dioResponse = await dio.post(
      'https://parseapi.back4app.com/installations',
      data: {
        'user': parseUser.toPointer(),
        'appName': "xxx
        'userName': parseUser.username,
        'appVersion': packageInfo.version,
        'appIdentifier': packageInfo.packageName,
        'deviceType': 'ios',
        'deviceToken': deviceToken,
        'installationId': installation.installationId
      },);
    print('dioResponse:');
    print(dioResponse.data);

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
