### ISSUE TITLE
LiveQuery with QueryBuilder.or not working

### ISSUE THREAD

**Issue by monster555** [parse-community/Parse-SDK-Flutter#510]
I'm having issues with OR queries when connecting to LIveQuery. No errors but not receiving any updated data matching the query.

Here are my queryBuilders. Performing a normal query iy works fine but not as a LiveQuery.

```
    QueryBuilder<ParseObject> q1 = QueryBuilder<ParseObject>(myClass)
      ..whereEqualTo('field1', 'value1')
      ..whereNotEqualTo('field2, 'value2');

    QueryBuilder<ParseObject> q2 = QueryBuilder<ParseObject>(myClass)
      ..whereContainedIn('arrayField', arrayValue)
      ..whereNotEqualTo('field2', 'value2');

    QueryBuilder<ParseObject> mainQuery = QueryBuilder.or(
     myClass,
      [q1, q2],
    )
      ..orderByDescending("createdAt")
      ..setLimit(15);
```

**Comment by RodrigoSMarques** [comment]
@monster555 
If you don't use OR (a simple query) does Livequery return results?

**Comment by monster555** [comment]
@RodrigoSMarques 
Yes... without OR it works. With OR it works only on the rows that I already fetched from the DB.
For example:
Let's say I have query1, query2 and mainQuery = QueryBuilder.or(someClass, [query1, query2])
I run a simple query and fetch the data that matches the query, everything ok so far. I connect the LiveQuery with the same query and it updates tha rows I already fetched but if I update some other row that matches mainQuery (either query1 or query2) I don't get that event on my app and I should get those rows matching mainQuery. If I'm mistaken please tell me.

**Comment by RodrigoSMarques** [comment]
@monster555 
Are you monitoring all LiveQuey events? **create, enter, update, leave**

This seems to me like a bug in Parse Server and not a problem in the plugin.
Which version of Parse Server?

**Comment by monster555** [comment]
Yes, I'm monitoring all LiveQuery events.
I'm on Parse Server 3.2.3, NodeJS 8.11.2.

**Comment by monster555** [comment]
Solved! I didn't noticed that I have commented enter and leave events :(
