### ISSUE TITLE
loginWith Apple

### ISSUE THREAD

**Issue by pamarcan** [parse-community/Parse-SDK-Flutter#511]
Hi guys,
I'm trying to implement the "login with Apple" functionality which is mandatory for Apple if you want to publish an iOS app with third party authentication.
I am using the plugin https://pub.dev/packages/sign_in_with_apple but I cannot understand how to build the authData (id, token) object to be sent to the Parse Server with the data present in the credential object

```
final credential = await SignInWithApple.getAppleIDCredential (
       scopes: [
         AppleIDAuthorizationScopes.email,
         AppleIDAuthorizationScopes.fullName,
       ],
     );

```
I think it would be useful for everyone if a solution is added as it is mandatory.

Thank you

**Comment by RodrigoSMarques** [comment]
Hi @pamarcan 

authData is a <String, dynamic> map and should be populated according to the link https://docs.parseplatform.org/parse-server/guide/#apple-authdata.

{
   "apple": {
     "id": "user",
     "token": "the identity token for the user"
   }
}

You must retrieve this data from the plugin (id and token) and create the map with the necessary information.

There are many articles on how to get the Apple id and token from the plugin (this is indifferent if the backend is Parse or Firebase, for example).

In the documentation we have instructions for Facebook and Google https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/flutter#facebook-oauth-and-3rd-party-loginuser

I have no access to my code right now. I can submit an example later and update the documentation with an example.

**Comment by pamarcan** [comment]
Thank you @RodrigoSMarques 
I solved!

In flutter, using the plugin
https://pub.dev/packages/sign_in_with_apple

The authentication on Parse Server using the credential object returned by Apple

```
final credential = await SignInWithApple.getAppleIDCredential (
        scopes: [
          AppleIDAuthorizationScopes.email,
          AppleIDAuthorizationScopes.fullName,
        ],
      );
```

it goes like this:

```
ParseResponse response =
                                                   await ParseUser.loginWith (
                                                       'apple', {
                                                 'id': credential.userIdentifier,
                                                 'token':
                                                     credential.identityToken
                                               });
```
