### ISSUE TITLE
coreStore vs repository pattern - flutter example 

### ISSUE THREAD

**Issue by felix-ht** [parse-community/Parse-SDK-Flutter#516]
So i started playing around with parse_server_sdk. I also looked into your example code. 

In you documentation you mention that parse already offers store functionality by default. 

```dart
await Parse().initialize(
  	keyParseApplicationId, 
  	keyParseServerUrl,
    coreStore: await CoreStoreSembastImp.getInstance("/data"));
```

In your example you set up a repository per class e.g.: https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/flutter/example/lib/data/repositories/user

In the `login_page.dart` example widget you end up using the the sdk variant to login and signup:
```dart
final User user = User(_email, _password, _email);

...

user.login()
```
In  `main.dart` you use the repository, to create users and to login.

This lefts me with couple of questions:

What does the coreStore store? 

All results of queries? 

Does it buffer requests that timeout?

When to apply the repository pattern?

What the recommended method to use in the context of the Provider state management lib?

**Comment by prakash-indorkar** [comment]
No one providing the proper solution.. why do we have to use restore and if so .. a good working example with proper explanation needed.. the example provide is very hotchpotch ..

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
