### ISSUE TITLE
Add linkWith method

### ISSUE THREAD

**Issue by csshenouda** [parse-community/Parse-SDK-Flutter#522]
Hi, 

`ParseUser`'s `loginWith()` method always creates a new user. 
```dart
// Logs in a user using a service
  static Future<ParseResponse> loginWith(
      String provider, Object authData) async {
    final ParseUser user = ParseUser.createUser();
    final ParseResponse response = await user._loginWith(provider, authData);
    return response;
  }
````

What if I want to link an existing Parse user to another service (in my case I'm using a [FirebaseAuth adapter](https://github.com/L3K0V/parse-server-firebase))?
Can we add a method like [linkWith](https://docs.parseplatform.org/js/guide/#Linking-Users)? Something along the lines of:

```dart
  // Logs in an existing user using a service
  Future<ParseResponse> linkWith(
      String provider, Object authData) async {
    final ParseResponse response = await this._loginWith(provider, authData);
    return response;
  }
```
Thanks! :)

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
