### ISSUE TITLE
when add my ACL on object and try to get objects get null 

### ISSUE THREAD

**Issue by mohyM** [parse-community/Parse-SDK-Flutter#526]
**get objects **
`await Parse().initialize(keyParseApplicationId, keyParseServerUrl,
        masterKey: keyParseMasterKey,
        liveQueryUrl: keyLiveQuery,
        clientKey: keyParseClientKey,
        autoSendSessionId: true);
    ParseUser user = await ParseUser.currentUser();
    final QueryBuilder<ParseObject> queryBuilder =
        QueryBuilder<ParseObject>(ParseObject('chatRooms'))
          ..whereContains("users", user.objectId)
          ..orderByDescending("updatedAt");
    final ParseResponse apiResponse = await queryBuilder.query();
    print(apiResponse.results);
    List<ParseObject> chatrooms = apiResponse.results;`

**save object**

` await Parse().initialize(keyParseApplicationId, keyParseServerUrl,
        masterKey: keyParseMasterKey,
        liveQueryUrl: keyLiveQuery,
        clientKey: keyParseClientKey,
        autoSendSessionId: true);
    ParseUser user = await ParseUser.currentUser();
    print(user.objectId);
    final QueryBuilder<ParseObject> queryBuilder =
        QueryBuilder<ParseObject>(ParseObject('chatRooms'))
          ..whereEqualTo('chatId', chatId);
    final ParseResponse apiResponse = await queryBuilder.query();
    print(apiResponse.results);
    List<ParseObject> chatrooms = apiResponse.results;
    if (chatrooms == null || chatRooms.length == 0) {
      ParseACL parseACL = ParseACL();
      parseACL.setReadAccess(userId: user.objectId, allowed: true);
      parseACL.setWriteAccess(userId: user.objectId, allowed: true);
      parseACL.setReadAccess(userId: otherId, allowed: true);
      parseACL.setWriteAccess(userId: otherId, allowed: true);
      var _chatRoom = ParseObject('chatRooms')
        ..set('chatId', chatId)
        ..set('name', name)
        ..set('senderId', user.objectId)
        ..set('hasLast', true)
        ..set('notificationNum', 1)
        ..set('lastMsg', lastMsg)
        ..set("users", [user.objectId, otherId])
       ..setACL(parseACL);
      var response = await _chatRoom.save();`

### please help me all my object will be public without any privacy

**Comment by mkoehne** [comment]
I had the same problem.
To solve the problem I had to add autoSendSessionId and set it to true in the Parse().initialize methode.

`Parse().initialize(
      autoSendSessionId: true,
    );`

**Comment by RodrigoSMarques** [comment]
In the next release the autoSendSessionId option will be True by default, to avoid these problems. 
Rarely will anyone use Parse without sending the session id to protect the data.

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
