### ISSUE TITLE
ParseObject().getAll() method returns max 100 objects

### ISSUE THREAD

**Issue by kharitonovAL** [parse-community/Parse-SDK-Flutter#527]
Hello everybody!

I have a method that retrieves objects from ParseServer:
```dart
Future<List<UserRequest>> getUserRequestList() async {
    final ParseResponse response = await UserRequest().getAll();
    final list = response.results.map((request) => (request as UserRequest)).toList();
    return list;
  }
```

and response limited to 100 objects. I found that for `ParseQueries` there are few [solutions](https://stackoverflow.com/questions/17246991/how-to-retrieve-more-than-1000-rows-from-parse-com), but how change limit for `.getAll()` method?

Thanks!

**Comment by kharitonovAL** [comment]
Temporary solution is below (`Owner` is `ParseObject` class):
```dart
QueryBuilder getQuery() {
    final QueryBuilder query = QueryBuilder<Owner>(Owner());
    query.setLimit(1000);
    return query;
  }

final q = getQuery();

q.query().then((value) {
   var list = value.results.map((e) => e as Owner).toList();
   list.forEach((element) {
     op += 1;
     print('$op ${element.accountNumber}');
   });
});
```

**Comment by Danaru87** [comment]
Hi @kharitonovAL ,

This is not a limitation from SDK but from ParseServer:

`You can use the limit and skip parameters for pagination.limit defaults to 100. In the old Parse hosted backend, the maximum limit was 1,000, but Parse Server removed that constraint. Thus, to retrieve 200 objects after skipping the first 400`

https://docs.parseplatform.org/rest/guide/#queries

**Comment by kharitonovAL** [comment]
> Hi @kharitonovAL ,
> 
> 
> 
> This is not a limitation from SDK but from ParseServer:
> 
> 
> 
> `You can use the limit and skip parameters for pagination.limit defaults to 100. In the old Parse hosted backend, the maximum limit was 1,000, but Parse Server removed that constraint. [...]`
> 
> 
> 
> https://docs.parseplatform.org/rest/guide/#queries

@Danaru87 
Thanks! Will check and report later!

**Comment by kharitonovAL** [comment]
> Hi @kharitonovAL ,
> 
> 
> 
> This is not a limitation from SDK but from ParseServer:
> 
> 
> 
> `You can use the limit and skip parameters for pagination.limit defaults to 100. In the old Parse hosted backend, the maximum limit was 1,000, but Parse Server removed that constraint. [...]`
> 
> 
> 
> https://docs.parseplatform.org/rest/guide/#queries

Accepted as solution! Thanks!
