### ISSUE TITLE
ParseInstallation - Quick updates produce concurrency errors

### ISSUE THREAD

**Issue by Chralu** [parse-community/Parse-SDK-Flutter#529]
Hi,

when doing quick updates of `ParseInstallation`, multiple objects get created on the server.

Running the following example will create two ParseInstallation.
```dart
    final parseInstallation1 = await ParseInstallation.currentInstallation();
    parseInstallation1.set<String>(
        'property1', 'value1');
    await parseInstallation1.save();

    final parseInstallation2 = await ParseInstallation.currentInstallation();
    parseInstallation2.set<String>(
        'property2', 'value2');
    await parseInstallation2.save();
```

The issue comes from a missing `await` in `parse_installation.dart`, on line 121 :
```dart
      saveInStorage(keyParseStoreInstallation);
```

This issue was analysed by @Danaru87.
We will submit a fix real soon.

# A thought :
Usage of [pedantic linter](https://dart.dev/guides/language/analysis-options#the-analysis-options-file) would prevent that kind of mistakes.

Cheers :)

**Comment by Danaru87** [comment]
Working on it ;)

**Comment by Danaru87** [comment]
Done in #531
