### ISSUE TITLE
[LiveList] Error Bulk delete

### ISSUE THREAD

**Issue by deepss1** [parse-community/Parse-SDK-Flutter#538]
Hello,

As I was testing the LiveList with around 100 rows deletion at once.

So what I did was bulk inserted 100 rows in a loop.

Then while in live list screen, I deleted those 100 rows from parse dashboard. And the live list got into some error. I will add the logs tomorrow.

Thank you

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
