### ISSUE TITLE
Parse Server not available due to

### ISSUE THREAD

**Issue by agus-tin** [parse-community/Parse-SDK-Flutter#540]
Hello,
While integrating Parse-SDK-Flutter with Parse Server (running on NodeJS), I'm receiving an error message on the Screen as shown below: 
    Parse Server Not Available due to
   Parse Exception (Type: null, Code: Null, Message: Null

In Android's Debug Console, I'm seeing the following curl command and error:
    _curl -X GET -H 'content-type: null' -H 'user-agent: Flutter Parse SDK 2.0.1' -H 'X-Parse-Application-Id: myAppId' -H 'X-Parse-Client-Key: myKeyParseClientKey' -H 'X-Parse-Master-Key: myKeyParseServerKey' http://localhost:1337/parse/health_
 **_Server health check failed_**

I'm sure the ParseServer is responding properly by means of "http://localhost:1337/test"

What I noticed with the auto generated CURL statement is that if I change manually the **Content-Type** and I remove the **user-agent**, the **X-Parse-Client-Key** and **X-Parse-Master-Key** keys (as shown below), the command executes correctly.

[This works OK: ]**_curl -X POST -H "X-Parse-Application-Id: myAppId" -H "Content-Type: application/json" http://localhost:1337/parse/health_**

Is this because the Parse-SDK-Flutter is incorrectly generating such tags, or am I missing something on the Client or  Server's configuration?

CLIENT
parse_server_sdk 2.0.1
Flutter 1.22.5
Android 4.1.1

SERVER
parse-server 4.5.0 (Locally)
Node.js v14.15.0
Mongo DB 4.1.1 (local)
Windows 10

Thanks

**Comment by dark4eg** [comment]
up

**Comment by alparslantopbas** [comment]
I am having the same problem, but only on Android. It works normally on iOS.

**Comment by dark4eg** [comment]
@alparslantopbas it is not difficult to show how your parse-server runs locally?
if there is a docker file or docker-compose.yml will be cool

**Comment by alparslantopbas** [comment]
Thanks @dark4eg, I took care of the problem.
But another problem arose, when the firewall does url filtering, Android cannot pass through HTTPS, but iOS can pass.
Yes, my parse-server runs locally.

**Comment by dark4eg** [comment]
@alparslantopbas please show how you run it locally, it is interesting to look at the parameters that you use to run.
P.S
no need to show your parameters for production)

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
