### ISSUE TITLE
'package:parse_server_sdk_flutter/parse_server_sdk.dart' is legacy, and should not be imported into a null safe library.\nTry migrating the imported library.",

### ISSUE THREAD

**Issue by prakash-indorkar** [parse-community/Parse-SDK-Flutter#541]
Hi there,

As Dart and flutter have moved into sound null safety, it is mandatory to have all the packages to be following null safety. Although I'm  using with un-sound null safety, still there is a warning on the package import as below

{
	"resource": "/C:/src/vscode/myapp/lib/app/data/model/user.dart",
	"owner": "dart",
	"code": "import_of_legacy_library_into_null_safe",
	"severity": 2,
	"message": "The library 'package:parse_server_sdk_flutter/parse_server_sdk.dart' is legacy, and should not be imported into a null safe library.\nTry migrating the imported library.",
	"source": "dart",
	"startLineNumber": 2,
	"startColumn": 8,
	"endLineNumber": 2,
	"endColumn": 64,
	"tags": []
}

Please do something about this.
Thanks, Prakash

**Comment by RodrigoSMarques** [comment]
@phillwiggins e @fischerscode .
Good Morning. 
Null safety. Is anyone working on it?

**Comment by pcegarra** [comment]
We need to migrate all code to null safety, right?

**Comment by RodrigoSMarques** [comment]
@pcegarra, yes.

I started to evaluate the migration, but the package depends on some dependencies that have not yet been migrated (for example, DIO).

It is not possible to run the migration tool. We have a lot of work to do.

**Comment by fischerscode** [comment]
@RodrigoSMarques 
I have finally time to return to my parse based project.
First of all: **Thank you for your work on the repository.**
Would you mind, me having a look at null safety? Or is there currently something more important to work on?

**Comment by RodrigoSMarques** [comment]
Hello, welcome again.

I see that the priority is null safety, the next version of Flutter is coming and many packages are already migrated.

I started the migration, using the tool but there are some dependencies that have not been updated and the process has not progressed.

The migration will have to be manual.

**Comment by fischerscode** [comment]
Ok, while going through the code in order to migrate, adding comments might be an idea, as there are almost none.
Do you think, creating a nullsafety-development branch is necessary/useful?

**Comment by RodrigoSMarques** [comment]
@fischerscode 
Punctual comments would be good (thinking about clean code).

In my Fork I created a "nullsafety" branch, because if there is a critical problem in the current version (2.1), we can fix it.

In the migration I was also considering removing the deprecated methods. What do you think?

I'm thinking of creating Project in the repository, listing all classes. We can signal which class we are working on and from this we can migrate in parallel. What do you think?

**Comment by fischerscode** [comment]
@RodrigoSMarques
> Punctual comments would be good (thinking about clean code).

I thought more about documenting comments in order to improve the [api docs](https://pub.dev/documentation/parse_server_sdk_flutter/latest/flutter_parse_sdk_flutter/flutter_parse_sdk_flutter-library.html).

> In my Fork I created a "nullsafety" branch, because if there is a critical problem in the current version (2.1), we can fix it.

Good point. I propose, we create a branch in this repo, this way we would both have push access.

> In the migration I was also considering removing the deprecated methods. What do you think?

Sounds reasonable. I think most deprecated methods are pretty unnecessary and/or deprecated for a while now.

> I'm thinking of creating Project in the repository, listing all classes. We can signal which class we are working on and from this we can migrate in parallel. What do you think?

Sounds good. 👍 I've never used this GitHub feature but I think it would be quite handy.

**Comment by nstrelow** [comment]
Nice, approach 😁 

I might help as well if possible.

**Comment by Katekko** [comment]
Maybe would be nice create a pinned issue and showing to us how is the progress for the nullsaf migration, what do you think @nstrelow? Because Im trying to use now in my project but found out that no has any version yet for nullsaft

**Comment by RodrigoSMarques** [comment]
@Katekko 
The package depends on others that have not been migrated.

I am evaluating replacement alternatives or whether they will be updated.

But I was not able to dedicate much time, as I was handling another package.

Today I will take the time to evaluate the necessary adjustments.

A Project has been created in the repository, but it is still empty.

https://github.com/parse-community/Parse-SDK-Flutter/projects/1

**Comment by RodrigoSMarques** [comment]
All dependencies that the package needs have been updated to null safety.

I started the code analysis and migration process. Initially, a simple migration, leaving the variables as nullable.

Around 75% of the code has already been migrated.

Soon I will bring more information.

**Comment by nstrelow** [comment]
@RodrigoSMarques Is there still a way I could help?
I am currently in a dependency hell and getting this done would be awesome for my sanity 🙈

**Comment by RodrigoSMarques** [comment]
@nstrelow 

Thank you for offering support. 
I'm currently in testing. I believe that I am very close to a "beta" version.
I will need support for testing.
I will keep you informed.

**Comment by nstrelow** [comment]
Awesome, I would run anything, just give me a branch I can point my pubspec.yaml too ;) (I am running on the development branch anyway)

**Comment by RodrigoSMarques** [comment]
Good Morning @nstrelow .

I finished the migration and am making final adjustments.

All functionalities are working, with the exception of ParseRelation (by history it was not 100%, #533)

I will make some adjustments to pubspec.yaml and let the branch know for you to support with the tests.

Thanks!

**Comment by nstrelow** [comment]
@RodrigoSMarques Awesome, I am itching to test it out.

It would be great id other people also test.

My current apps are not using all the features of Parse, such as 3rd party logins, cloudfunctions, live lists.

So whoever can test out their app with those functions, please do :)

**Comment by RodrigoSMarques** [comment]
@nstrelow 
Update your pubspec.yaml
``` dart
  parse_server_sdk_flutter:
    git:
      url: https://github.com/RodrigoSMarques/Parse-SDK-Flutter.git
      ref: nullsafety
      path: packages/flutter
```

I have a test project, which simulates operations on the package on Parse Server:

Login / Logout
Upload / Download files
Create Object
Update Object
Geopoint
Simple Query
Complex Query
Pointer / relation
Installation

All tests were performed successfully.

I appreciate anyone who can help with the tests.

**Comment by pasrot943** [comment]
I got the initializing part working! I never used parse before,  but I’ll try to be as helpful as I can. You are the boss rodrigo!

**Comment by nstrelow** [comment]
@RodrigoSMarques Thanks a lot.
I added your branch:

I am running in the following error on compile. I have **NOT** updated run `flutter pub upgrade` yet.
Also my app is still on Dart SDK 2.7 (which still makes it possible to run null safe packages).

```
../../../AppData/Local/Pub/Cache/git/Parse-SDK-Flutter-dec0eb12146c36fba8c4ae458f1519ce432078bd/packages/dart/lib/src/network/parse_dio_client.dart:135:49: Error: The argument type 'SecurityContext?' can't be assigned to the parameter type 'SecurityContext' because 'SecurityContext?' is nullable and 'SecurityContext' isn't.
 - 'SecurityContext' is from 'dart:io'.
    httpClientAdapter = createHttpClientAdapter(securityContext);
```

**Comment by nstrelow** [comment]
The error does not make sense, because everything is a nullable `SecurityContext?`.
So weird

**Comment by nstrelow** [comment]
Running using ParseDioClient and using Android as target:

```
E/flutter ( 7203): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The getter 'isNotEmpty' was called on null.
E/flutter ( 7203): Receiver: null
E/flutter ( 7203): Tried calling: isNotEmpty
E/flutter ( 7203): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter ( 7203): #1      _ParseDioClient.request (package:parse_server_sdk/src/network/parse_dio_client.dart:169:33)
E/flutter ( 7203): #2      DioMixin.get (package:dio/src/dio_mixin.dart:53:12)
E/flutter ( 7203): #3      ParseDioClient.get (package:parse_server_sdk/src/network/parse_dio_client.dart:26:63)
E/flutter ( 7203): #4      Parse.healthCheck (package:parse_server_sdk/parse_server_sdk.dart:160:25)
E/flutter ( 7203): #5      ParseInit.initParse (package:studyou_core/util/parse_init.dart:51:20)
E/flutter ( 7203): <asynchronous suspension>
E/flutter ( 7203): #6      _ParseListFutureBuilderState._parseQuery (package:studyou_core/util/parse_future_builder.dart:42:22)
E/flutter ( 7203): <asynchronous suspension>
```

**Comment by nstrelow** [comment]
Now I can do more with the app.

Working:
* Fetching (with Queries)
* Deleting a user

Not working:
Getting the User from Local Storage.
`ParseUser.currentUser()`
Possibily the user has not been created at that point. I expected it to return null.

```
E/flutter ( 7755): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FormatException: Unexpected end of input (at character 1)
E/flutter ( 7755): 
E/flutter ( 7755): ^
E/flutter ( 7755): 
E/flutter ( 7755): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
E/flutter ( 7755): #1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:522:7)
E/flutter ( 7755): #2      _parseJson (dart:convert-patch/convert_patch.dart:41:10)
E/flutter ( 7755): #3      JsonDecoder.convert (dart:convert/json.dart:506:36)
E/flutter ( 7755): #4      JsonCodec.decode (dart:convert/json.dart:157:41)
E/flutter ( 7755): #5      ParseUser._getUserFromLocalStore (package:parse_server_sdk/src/objects/parse_user.dart:460:49)
E/flutter ( 7755): <asynchronous suspension>
E/flutter ( 7755): #6      ParseUser.currentUser (package:parse_server_sdk/src/objects/parse_user.dart:156:14)
E/flutter ( 7755): <asynchronous suspension>
E/flutter ( 7755): #7      UserQueries.getOrCreateUser (package:studyou_core/util/user.dart:11:29)
E/flutter ( 7755): <asynchronous suspension>
E/flutter ( 7755): #8      _KickoffScreen._storeUserStudy (package:studyu/screens/study/onboarding/kickoff.dart:22:18)
```

**Comment by nstrelow** [comment]
The problem for ParseUser.currentUser() is that `userJson` is not null, but is an empty string.

```
    final CoreStore coreStore = ParseCoreData().getStore();
    final String? userJson = await coreStore.getString(keyParseStoreUser);

    if (userJson != null) {
      final Map<String, dynamic> userMap = json.decode(userJson);
```

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques Thanks a lot.
> I added your branch:
> 
> I am running in the following error on compile with Flutter Web using ParseHttpClient (maybe it somehow initializes Dio anyway).
> Also my app is still on Dart SDK 2.7 (which still makes it possible to run null safe packages).
> 
> ```
> ../network/parse_dio_client.dart:135:49: Error: The argument type 'SecurityContext?' can't be assigned to the parameter type 'SecurityContext' because 'SecurityContext?' is nullable and 'SecurityContext' isn't.
>  - 'SecurityContext' is from 'dart:io'.
>     httpClientAdapter = createHttpClientAdapter(securityContext);
> ```
> 
> My init of parse using clientCreator:
> 
> ```
> clientCreator: ({sendSessionId, securityContext}) => kIsWeb
>             ? ParseHTTPClient(sendSessionId: sendSessionId, securityContext: securityContext)
>             : ParseDioClient(sendSessionId: sendSessionId, securityContext: securityContext),
> ```

Very strange because it was tested.
```dart
  await Parse().initialize("xxxxxxxxxxxxxxxxxxxxxxxxx",
      "https://api.xxxxxxxxxxxxxxxxxxxxxxxxx.com/1",
      clientKey: "xxxxxxxxxxxxxxxxxxxxxxxxx",
      debug: true,
      coreStore: await CoreStoreSembastImp.getInstance(password: 'parse_teste'),
      clientCreator: (
              {bool? sendSessionId, SecurityContext? securityContext}) =>
          ParseDioClient(
              sendSessionId: sendSessionId, securityContext: securityContext),
      liveQueryUrl: "https://api.xxxxxxxxxxxxxxxxxxxxxxxxx.com/1");
```

**Comment by RodrigoSMarques** [comment]
> Makes sense, since masterKey is null (it should not be set in Flutter client apps).
> I will set it anyway and see if anything else is not working.

Masterkey is not nullable. It is initialized with a empty. 

![Captura de Tela 2021-03-16 às 08 32 40](https://user-images.githubusercontent.com/17687286/111302708-7be4a180-8632-11eb-95fe-69c7ab0329d3.png)

In the example project, I do not inform masterkey

```dart
  await Parse().initialize("xxxxxxxxxxxxxxxxxxxxxxxxx",
      "https://api.xxxxxxxxxxxxxxxxxxxxxxxxx.com/1",
      clientKey: "xxxxxxxxxxxxxxxxxxxxxxxxx",
      debug: true,
      coreStore: await CoreStoreSembastImp.getInstance(password: 'parse_teste'),
      clientCreator: (
              {bool? sendSessionId, SecurityContext? securityContext}) =>
          ParseDioClient(
              sendSessionId: sendSessionId, securityContext: securityContext),
      liveQueryUrl: "https://api.xxxxxxxxxxxxxxxxxxxxxxxxx.com/1");
```

**Comment by RodrigoSMarques** [comment]
> Now I can do more with the app.
> 
> Working:
> 
> * Fetching (with Queries)
> * Deleting a user
> 
> Not working:
> Getting the User from Local Storage.
> `ParseUser.currentUser()`
> The user has not been created at that point. I expected it to return null.
> 
> ```
> E/flutter ( 7755): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FormatException: Unexpected end of input (at character 1)
> E/flutter ( 7755): 
> E/flutter ( 7755): ^
> E/flutter ( 7755): 
> E/flutter ( 7755): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
> E/flutter ( 7755): #1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:522:7)
> E/flutter ( 7755): #2      _parseJson (dart:convert-patch/convert_patch.dart:41:10)
> E/flutter ( 7755): #3      JsonDecoder.convert (dart:convert/json.dart:506:36)
> E/flutter ( 7755): #4      JsonCodec.decode (dart:convert/json.dart:157:41)
> E/flutter ( 7755): #5      ParseUser._getUserFromLocalStore (package:parse_server_sdk/src/objects/parse_user.dart:460:49)
> E/flutter ( 7755): <asynchronous suspension>
> E/flutter ( 7755): #6      ParseUser.currentUser (package:parse_server_sdk/src/objects/parse_user.dart:156:14)
> E/flutter ( 7755): <asynchronous suspension>
> E/flutter ( 7755): #7      UserQueries.getOrCreateUser (package:studyou_core/util/user.dart:11:29)
> E/flutter ( 7755): <asynchronous suspension>
> E/flutter ( 7755): #8      _KickoffScreen._storeUserStudy (package:studyu/screens/study/onboarding/kickoff.dart:22:18)
> ```

ParseUser.currentUser is nullable. If it does not exist, it will return null.

```dart
  print('********************************************************');
  print('Get current user');
  print('********************************************************');

  final ParseUser? currentUser = await ParseUser?.currentUser() as ParseUser?;

  if (currentUser != null) {
    print('********************************************************');
    print('User loggedin');
    print('********************************************************');
  }

````

Function ` _getUserFromLocalStore`

```dart
  static Future<dynamic?> _getUserFromLocalStore(
      {ParseCloneable? cloneable}) async {
    final CoreStore coreStore = ParseCoreData().getStore();
    final String? userJson = await coreStore.getString(keyParseStoreUser);

    if (userJson != null) {
      final Map<String, dynamic> userMap = json.decode(userJson);
      if (cloneable != null) {
        return cloneable.clone(userMap);
      } else {
        ParseCoreData().setSessionId(userMap[keyParamSessionToken]);
        return parseDecode(userMap);
      }
    }

    return null;
  }
```
The error occurred during the json Parse. Strange because it was verified if it is null.

**Comment by RodrigoSMarques** [comment]
> The problem for ParseUser.currentUser() is that `userJson` is not null, but is an empty string.
> 
> I don't get why it is an empty string. Somehow the ParseSDK intializes it with an empty string, which should not be the case.
> 
> ```
>     final CoreStore coreStore = ParseCoreData().getStore();
>     final String? userJson = await coreStore.getString(keyParseStoreUser);
> 
>     if (userJson != null) {
>       final Map<String, dynamic> userMap = json.decode(userJson);
> ```

I adjusted the code and put a validation to validate that it is empty.

**Comment by RodrigoSMarques** [comment]
> The problem for ParseUser.currentUser() is that `userJson` is not null, but is an empty string.
> 
> I don't get why it is an empty string. Somehow the ParseSDK intializes it with an empty string, which should not be the case.
> 
> ```
>     final CoreStore coreStore = ParseCoreData().getStore();
>     final String? userJson = await coreStore.getString(keyParseStoreUser);
> 
>     if (userJson != null) {
>       final Map<String, dynamic> userMap = json.decode(userJson);
> ```

I adjusted the code and put a validation to validate that it is empty.

**Comment by nstrelow** [comment]
About masterkey:
I am setting it to null myself (because I am loading the value from a .env file, if it is set, if not it's null). So this is kinda my fault. But it used to work before, therefore a somewhat breaking change. Maybe we can initialize masterkey and all the others with null and not empty string? I think this makes much more sense.

**Comment by nstrelow** [comment]
> I adjusted the code and put a validation to validate that it is empty.

I think it should **not** be an empty string. It should be null if nothing is there right?

**Comment by nstrelow** [comment]
```
clientCreator: (
              {bool? sendSessionId, SecurityContext? securityContext}) =>
          ParseDioClient(
              sendSessionId: sendSessionId, securityContext: securityContext),
```
I cannot use this, because I am not using null safety yet.

**Comment by RodrigoSMarques** [comment]
> > I adjusted the code and put a validation to validate that it is empty.
> 
> I think it should **not** be an empty string. It should be null if nothing is there right?

It should be null.

How are you running on SDK 2.7 if the package minimum is
environment:
   sdk: '> = 2.12.0 <3.0.0'

**Comment by nstrelow** [comment]
Sorry, I meant

My sdk is `sdk: '>=2.7.0 <3.0.0'`, which then resolves to 2.12.0, but it lets me run my code, without using null-safety.
If I change it to `>=2.12.0`, I have to migrate all the code, or I get tons of errors.

**Comment by RodrigoSMarques** [comment]
I'm going to change my SDK to 2.7 and run my test project and evaluate it.

**Comment by nstrelow** [comment]
Thanks a lot :)

I can also try and fix "my problems" and make a PR to your branch

**Comment by nstrelow** [comment]
`final response = await ParseUser(null, null, null).loginAnonymous(doNotSendInstallationID: true);`

```
Message: FormatException: Unexpected end of input (at character 1)
```

Seems to be a similar issue here. Not sure at what point it is caused though. I'll try to investigate.

**Comment by RodrigoSMarques** [comment]
@nstrelow 
I changed my SDK to 2.7 and undid the null safety changes

My test project ran without errors.

I am at work right now. I will see your comments later.

Thanks.

**Comment by nstrelow** [comment]
Besides those small problems I have yet not found anything wrong :D Awesome work @RodrigoSMarques.

I will try to fix what I found and make a PR to your repo.

Summary:
**Critical**
* installationJson is empty and not null (fix: either check also for isNotEmpty or figure out why it is empty string)
* userJson is empty and not null (fix: same as above)
* Only on **web** error using clientCreator: `'SecurityContext' because 'SecurityContext?' is nullable and 'SecurityContext' isn't.`

**Potentially breaking**
* Masterkey cannot be null (fix: Make Masterkey null by default, instead of empty String.)
* All other fields initialized with empty String.

**Comment by nstrelow** [comment]
I finished changing most of emptyString things to nullables.
I will test that now with my app and commit the changes to my fork.

Afterwards I would still like to review more of your changes, which will take some time. I hope to get it done today.

**Comment by RodrigoSMarques** [comment]
Hello Guys, run the test and report the problems.

```dart
  parse_server_sdk_flutter:
    git:
      url: https://github.com/parse-community/Parse-SDK-Flutter.git
      ref: nullsafety
      path: packages/flutter
```
@pastordee

**Comment by RodrigoSMarques** [comment]
Hi guys.

Has anyone done tests? Any feedback? Everything working?

**Comment by spk22** [comment]
Hi, I am observing this issue for last few days since my backend is back4app. I used the above dependency to my project. 
It is operating as expected now.
But, I'm not expert enough to submit any particular tests or details.

**Comment by RodrigoSMarques** [comment]
New Version 3.0 with support null safety available.
