### ISSUE TITLE
Change default login and signin method to POST

### ISSUE THREAD

**Issue by jjunineuro** [parse-community/Parse-SDK-Flutter#542]
Hello, thank you very much for your help.

When testing on the Parse Flutter SDK, I don't have this option and I can't login or sigin using the POST method.

Could you help me with the Parse Flutter SDK?

**In the Parse Flutter SDK**
![fluttersdk](https://user-images.githubusercontent.com/30479720/104033586-a431c900-51c7-11eb-845a-563f5edcb5c8.png)

**In the Parse Javascript SDK**
![javascriptsdk](https://user-images.githubusercontent.com/30479720/104033867-068ac980-51c8-11eb-940f-8d9f9dbd7537.png)

**Comment by RodrigoSMarques** [comment]
Hi @jjunineuro 

For login, the SDK follows the instructions as described in the REST API

https://docs.parseplatform.org/rest/guide/#logging-in

![image](https://user-images.githubusercontent.com/17687286/104039349-06350300-51b5-11eb-9b34-6ded65212b0a.png)

**Comment by jjunineuro** [comment]
Hello Rodrigo, how are you?

Sorry but I don't think it was explained.

I understand that I can login via the Rest API. But just as in the Javascript SDK there is this option, I would like to know if you also have it in the Flutter SDK.

I searched all the code and found nothing about it.

Would it be possible to implement this functionality in the next SDK update to perform Login and SignIn using the POST method?

This is a problem that I see as serious, as the network administrator can see the user's access credentials. And that’s not cool.

**Comment by dplewis** [comment]
@jjunineuro For a little history. The login only supported GET initially which is why the SDK have a GET and not POST since POST was added later on. Look at the JS SDK, didn't have usePost until recently [2.17.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/2.17.0)

**Comment by RodrigoSMarques** [comment]
The Parse-SDK-Flutter package internally calls the Parse REST API.

There is no reference in the Parse API documentation that the POST method also works for login.

For this reason it is not implemented. We have to investigate.

**Comment by jjunineuro** [comment]
Perfect @dplewis. The purpose of the comment is, for a next update of the Flutter SDK, can it be implemented as well? So how was it done with the Javascript SDK?

**Comment by dplewis** [comment]
It was added 3 years ago when it was added to the server, released on version [2.6.4](https://github.com/parse-community/parse-server/releases/tag/2.6.4).

PR -> https://github.com/parse-community/parse-server/pull/4268

Since it was so long ago, we can make POST the default.

**Comment by RodrigoSMarques** [comment]
@dplewis 
It would be important to update the REST API documentation

**Comment by jjunineuro** [comment]
> It was added 3 years ago when it was added to the server, released on version [2.6.4](https://github.com/parse-community/parse-server/releases/tag/2.6.4).
> 
> PR -> [parse-community/parse-server#4268](https://github.com/parse-community/parse-server/pull/4268)
> 
> Since it was so long ago, we can make POST the default.

Dear @dplewis , that would be very important. For I am deepening my knowledge with Parse Server and this question involves the current Data Protection Laws. I am looking forward to the next update of the Flutter SDK with this improvement. The Login and SignIn classes using the POST method.

**Comment by RodrigoSMarques** [comment]
@jjunineuro 
I will do a PR with the change as soon as I have time.

**Comment by jjunineuro** [comment]
@RodrigoSMarques 

Just to confirm the @dplewis information, it is possible to login via POST through the Parse Rest API.

![restapiparse](https://user-images.githubusercontent.com/30479720/104044294-0cd37280-51d5-11eb-93fa-df1cd4ade94a.png)

**Comment by jjunineuro** [comment]
Only a question.

Sorry if it's a basic question, but it's my first time here.

When this implementation is launched, is it possible to notify this question or do I have to attend the Flutter SDK group?

**Comment by dplewis** [comment]
It would be awesome if you can join the group 😄 . You can watch for new releases.

<img width="612" alt="Screen Shot 2021-01-08 at 11 27 22 AM" src="https://user-images.githubusercontent.com/9830365/104045834-c23a0200-51a4-11eb-8ba4-7141a957a5ae.png">

**Comment by jjunineuro** [comment]
Thank you @dplewis. I done. I'm participating now.

**Comment by jjunineuro** [comment]
Hi,

I analyzed the codes carefully and found the changes:

**Current code**
[https://github.com/parse-community/Parse-SDK-Flutter/blob/master/packages/dart/lib/src/objects/parse_user.dart#L203,L208](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/packages/dart/lib/src/objects/parse_user.dart#L203,L208)

**Changed to**
`      final Uri url = getSanitisedUri(_client, '$keyEndPointLogin');`
`      _saveChanges();`
`      final Response<String> response = await _client.post<String>(`
`        url.toString(),`
`        data: queryParams,`
`        options: Options(headers: <String, String>{`

![postfluttersdklogin](https://user-images.githubusercontent.com/30479720/104181530-dc731a80-5406-11eb-8171-cde32a67d474.png)

I'm going to try to commit the project, but I think I need authorization, right? A great week everyone.

**Comment by RodrigoSMarques** [comment]
@jjunineuro 
Read the guidelines #515

**Comment by jjunineuro** [comment]
I believe everything went well with the commit :)

[https://github.com/jjunineuro/Parse-SDK-Flutter/blob/master/packages/dart/lib/src/objects/parse_user.dart](https://github.com/jjunineuro/Parse-SDK-Flutter/blob/master/packages/dart/lib/src/objects/parse_user.dart)

**Comment by jjunineuro** [comment]
Resolved, thank you @RodrigoSMarques 

[https://github.com/parse-community/Parse-SDK-Flutter/pull/544](https://github.com/parse-community/Parse-SDK-Flutter/pull/544)
