### ISSUE TITLE
please update this project soon!!!

### ISSUE THREAD

**Issue by fee-studio** [parse-community/Parse-SDK-Flutter#549]
such as ACL ROLE functions...

**Comment by RodrigoSMarques** [comment]
Hi @fee-studio 

If you can contribute to the project, we would be grateful.

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
