### ISSUE TITLE
Can you include query/object cache in next release ? it is the must have feature in mobile 

### ISSUE THREAD

**Issue by ghost** [parse-community/Parse-SDK-Flutter#55]

**Comment by phillwiggins** [comment]
Hey

We haven't got that just yet. We've not found a suitable NoSQL dB for Dart that is stable enough. 

This will be added in the future.

**Comment by sawrose** [comment]
Thanks , hope it comes soon .
hey , i fount that this line in livequery is causing issue for me 
`subscribeMessage['query']['className'] = className;`

so , for quick fix i have just moved 
`subscribeMessage = {
      "op": "subscribe",
      "requestId": 1,
      "query": {
        "className": className,
        "where": {},
      }
    };`

to subscribe class in parse_livequery.dart

**Comment by cadaniel** [comment]
HIve might be a good option for a pure dart NoSQL. 

If your able to point me in the right direction I'd be instrested in contributing.

**Comment by mbfakourii** [comment]
The subject of caching the object and sending it after the availability of Parse is called ```saveEventually```, which is discussed in this [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues/149), otherwise you can use nosql to save.
