### ISSUE TITLE
Pull to refresh to ParseLiveList

### ISSUE THREAD

**Issue by pastordee** [parse-community/Parse-SDK-Flutter#550]
I was wondering if there’s a way we can add pull to refresh to the ParseLiveList

**Comment by RodrigoSMarques** [comment]
@fischerscode.
How you created the widget. You can answer?

**Comment by pastordee** [comment]
> @fischerscode.
> How you created the widget. You can answer?

sorry I don't get your question

**Comment by pastordee** [comment]
> > @fischerscode.
> > How you created the widget. You can answer?
> 
> sorry I don't get your question

oh, I get what you're saying now but it was @fischerscode who created it I just contributed but I am looking into it.

**Comment by RodrigoSMarques** [comment]
@pastordee 
The problem persists? Can we close this issue?
