### ISSUE TITLE
ParseInstallation currentInstallation not created in dashboard

### ISSUE THREAD

**Issue by gucci-quoci** [parse-community/Parse-SDK-Flutter#551]
Hey, so I am trying to get the current installation and update the device token. Aftter calling installation.save() I get the print from response.result ({"className":"_Installation","objectId":"L1iFJzUDQP"..), but in my dashboard neither the installation was created nor updated. My Installation stays empty with no new installations.
```
final ParseInstallation installation = await ParseInstallation.currentInstallation();
installation.deviceToken = token;

final ParseResponse response= await installation.save();
if(response.success){
    print(response.result); 
} else {
    print(response.error.message);
}
```

**Comment by gucci-quoci** [comment]
I fixed that. This happens because I saved the installation on two different blocs. But this shouldn't happen either.

**Comment by gucci-quoci** [comment]
Sorry it isn't fixed. The installation entry is created and everything is set except the installationId, although I get it from the prints.

**Comment by RodrigoSMarques** [comment]
Hi @gucci-quoci 

What is your version of Parse Server? 

I also have the same problem and I'm investigating. I'm on 4.5.0.

InstallationId is generated by Parse Server. It is not sent by the package.

If you activate the debug mode, the create message returns the installationId, but it is not being saved.

If you check in Sessions, the session created by the user on the device, has an installationId that is the same as the debug.

This worked correctly and I have already returned some versions of the package and the problem persists.

**Comment by gucci-quoci** [comment]
Hi @RodrigoSMarques 
I'm using `parse_server_sdk_flutter: ^2.0.1`

**Comment by gucci-quoci** [comment]
Hi @RodrigoSMarques 
I cloned the [parse-server-example](https://github.com/parse-community/parse-server-example).
I noticed something in my case. If I call `installation.save()` before `ParseUser.loginWith` the installation is setup correctly on the dashboard, but if I call `ParseUser.loginWith` before `installation.save()`,  the issue which I commented happens.
```
final ParseInstallation installation = await ParseInstallation.currentInstallation();
installation.deviceToken = token;
final ParseResponse response= await installation.save();
if(response.success)
...

final ParseResponse userResponse = await ParseUser.loginWith(
  'anonymous',
  <String, String>{
    'id': id.,
  },
);
...
````
```
final ParseResponse userResponse = await ParseUser.loginWith(
  'anonymous',
  <String, String>{
    'id': id,
  },
);
...

final ParseInstallation installation = await ParseInstallation.currentInstallation();
installation.deviceToken = token;
final ParseResponse response= await installation.save();
if(response.success)
...
````

> Sorry it isn't fixed.
> On my first start I get this response, but the installationId isn't set on the dashboard, but in my response it is set.
> On my second start of the app, the installation entry is deleted.
> I'm just calling the await installation.save()
> `{"className":"_Installation","installationId":"b9cc5687-3a26-40b6-a5ad-f3b15ff38948","deviceType":"android","localeIdentifier":"de_DE","appName":"name","appVersion":"1.0.0","appIdentifier":"com.example.myApp","parseVersion":"2.0.1","deviceToken":"cDwvW1o6QQirO2wRHflfiq:APA91bFLHGSnWVCS1h6u8JSJo_wZBrH6fPI2CL7Inh6GGqWRo2mydxG2cX8wVhh2iXu3T4GLzyOiRJmVgKLQUjtka5_O-YqjGQDGRqP2s58mpMtVrv9ywn4FCYYcQMJIjA_oRUdyy4dt"}`

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
