### ISSUE TITLE
Request for Flutter Web Support

### ISSUE THREAD

**Issue by msoham123** [parse-community/Parse-SDK-Flutter#555]
Maybe you could port over the JS SDK?

**Comment by RodrigoSMarques** [comment]
The package is already compatible with Flutter Web

https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/flutter#web-support

**Comment by msoham123** [comment]
I see, can you update Pub.dev to reflect this? I only asked because it only says Android and IOS there.

**Comment by RodrigoSMarques** [comment]
Is up to date. In both packages.

Section Web support

- Dart: https://pub.dev/packages/parse_server_sdk
- Flutter: https://pub.dev/packages/parse_server_sdk_flutter

**Comment by msoham123** [comment]
The label on pub.dev does not show web as a supported platform. This label is used to sort and find web supported packages.

![image](https://user-images.githubusercontent.com/51520568/105392655-48f0d500-5bd0-11eb-8d47-22d6553e3488.png)
