### ISSUE TITLE
Parse QueryBuilder collection having file object

### ISSUE THREAD

**Issue by ccs1428** [parse-community/Parse-SDK-Flutter#557]
Trying to query QueryBuilder using ParseObject, returns only string data.

How to get file object and other data too, but it not working like that.

<img width="1135" alt="Screenshot 2021-01-25 at 12 53 12 PM" src="https://user-images.githubusercontent.com/585841/105673763-888b2a00-5f0c-11eb-84a7-316ae7a40c3c.png">

Code Sample
`    final QueryBuilder<ParseObject> queryBuilder =
        QueryBuilder<ParseObject>(ParseObject('Sacrament'))
          ..whereEqualTo('Collection', widget.sacramentCollection)
          ..whereEqualTo('Status', 'A')
          ..orderByAscending('Name');
    //var apiResponse = await queryBuilder.query();
    final ParseResponse apiResponse = await queryBuilder.query();
`

Response

`{"className":"######","objectId":"********","createdAt":"2018-05-23T16:57:59.705Z","updatedAt":"2018-06-18T17:40:58.970Z","Name":"*****","Collection":"$$$$","Language":"***","Status":"A","email":"#######","username":"####","Created":"######"}`

**Comment by RodrigoSMarques** [comment]
Hi @ccs1428 .

Try 

```dart
    final ParseResponse apiResponse = await queryBuilder.query();
    if (apiResponse.success && apiResponse.results != null) {
      for (final object in apiResponse.results as List<ParseObject>) {
        print(object.objectId);
        print(object.createdAt);
        print(object.updatedAt);
        print(object.getACL());
        print(object.createdAt);
        print(object.get<String>("Name"));
        print(object.get<String>("Status"));
        final image = object.get<ParseFile>("Sacrament");
        if (image != null) {
          print(image.url);
          print(image.name);
        }
      }
    }
```

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.

**Comment by ccs1428** [comment]
@RodrigoSMarques 

I have tried the above solution but returning null response for file object.

final image = object.get<ParseFile>("Sacrament");

Please help me, sorry for the late response.

**Comment by ccs1428** [comment]
@RodrigoSMarques 

ParseObject not found method getFIleObject. Please help me
