### ISSUE TITLE
The getter 'debug' was called on null

### ISSUE THREAD

**Issue by agus-tin** [parse-community/Parse-SDK-Flutter#560]
When I try to instantiate ParseUser(username, pass, email), I get a "NoSuchMethodError: The getter 'debug' was called on null." error on class ParseObject (parse_object.dart) at line: **__debug = isDebugEnabled(objectLevelDebug: debug);_**

As per the definition of the object, I understand that such parameter is optional, hence no error should  be triggered if omitted
  **_ParseObject(String className, {bool debug, ParseHTTPClient client, bool autoSendSessionId})_**

Even if I supply the **_debug_** parameter as shown below, I'm getting the same type of error:
 ParseUser(username, pass, email, debug:true)

I'm running Node, Flutter (via AndroidStudio) & MongoDB locally on a Windows 10 desktop

Below an extract of my settings & dependencies
  -Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
  -Dart 2.10.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
...
  encrypted_shared_preferences: ^1.0.7
  parse_server_sdk_flutter: ^2.0.0
...

Below the complete error description:

**Comment by RodrigoSMarques** [comment]
@agus-tin 
Does the problem still persist? Can we close this issue?

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity.
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
