### ISSUE TITLE
ParseLiveListWidget Loses Scroll Position

### ISSUE THREAD

**Issue by pastordee** [parse-community/Parse-SDK-Flutter#561]
Hi guys can anyone help, I've noticed that in ParseLiveListWidget  whenever you scroll everything reset,  example I have a check list tile when you select it and scroll up and when you come back down it has unchecked it self now I have tried this with the normal list view any it works fine but whenever I use it with ParseLiveListWidget it doesn't work does anyone know what is going on I've been reading about it and it saying something about the PageStorageKey and ObjectKey I've done everything and I can't seem to get it to work.
@fischerscode

**Comment by RodrigoSMarques** [comment]
Does the problem still persist? Can we close this issue?
