### ISSUE TITLE
Unable to load parse server library

### ISSUE THREAD

**Issue by DaBlitzStein** [parse-community/Parse-SDK-Flutter#562]
Hello,
Even after installed with pub get, I've got:
`error: Target of URI doesn't exist: 'package:parse_server_sdk_flutter/parse_server_sdk.dart'. (uri_does_not_exist at [eB] lib\models\data_model.dart:9)`

There is no code, looks like it doesn't load the library on the import sentence.
```
import 'dart:core';
import 'dart:math';
import 'package:parse_server_sdk_flutter/parse_server_sdk.dart';
```

It doesn't happen with any another package.

**Comment by RodrigoSMarques** [comment]
@DaBlitzStein 
Does the problem still persist? Can we close this issue?

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity.
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
