### ISSUE TITLE
Unable to set custom Object Id

### ISSUE THREAD

**Issue by Krid86abc** [parse-community/Parse-SDK-Flutter#567]
Hi,
When creating an Object with custom object ID
`ParseObject object = ParseObject("parseUsers");
    object.objectId ="kT2DENLttz12";
    object.create(allowCustomObjectId: true);`

It does not work, with error: 
`I/flutter ( 5297): ----
I/flutter ( 5297): ParseException (Type: InvalidKeyName) :
I/flutter ( 5297): Code: 105
I/flutter ( 5297): Message: objectId is an invalid field name.----`

**Comment by RodrigoSMarques** [comment]
@Krid86abc 
Did you enable the `allowCustomObjectId` option on your server?

[https://parseplatform.org/parse-server/api/master/ParseServerOptions.html](https://parseplatform.org/parse-server/api/master/ParseServerOptions.html)

**Comment by Krid86abc** [comment]
Oh no, thank you and sorry
