### ISSUE TITLE
Add null safety support

### ISSUE THREAD

**Issue by rlazom** [parse-community/Parse-SDK-Flutter#573]
Could you please add **null safety support** to this plugin please?

**Comment by RodrigoSMarques** [comment]
Check this issue #541

**Comment by RodrigoSMarques** [comment]
@rlazom 

Can you test your project using this version?

Update your pubspec.yaml

```dart
  parse_server_sdk_flutter:
    git:
      url: https://github.com/RodrigoSMarques/Parse-SDK-Flutter.git
      ref: nullsafety
      path: packages/flutter
```

**Comment by NuclleaR** [comment]
@RodrigoSMarques I have issue with version that you mentioned. why `initialize` returns `Future<Parse>`?

**Comment by gcostaapps** [comment]
When trying to use this version on my application I got the following error when trying to run

```
/C:/flutter/.pub-cache/git/Parse-SDK-Flutter-123876a10d997f5bded788a0ee3388c0ecb736a3/packages/dart/lib/src/objects/response/parse_exception_response.dart:6:20: Error: 'DioError' isn't a type.
  if (exception is DioError) {
                   ^^^^^^^^
/C:/flutter/.pub-cache/git/Parse-SDK-Flutter-123876a10d997f5bded788a0ee3388c0ecb736a3/packages/dart/lib/src/objects/response/parse_exception_response.dart:15:7: Error: Non-nullable variable 'errorResponse' must be assigned before it can be used.
      errorResponse ??= <String, dynamic>{};
      ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/git/Parse-SDK-Flutter-123876a10d997f5bded788a0ee3388c0ecb736a3/packages/dart/lib/src/objects/response/parse_exception_response.dart:15:7: Warning: Operand of null-aware operation '??=' has type 'Map<String, dynamic>' which excludes null.
 - 'Map' is from 'dart:core'.
      errorResponse ??= <String, dynamic>{};
      ^
/C:/flutter/.pub-cache/git/Parse-SDK-Flutter-123876a10d997f5bded788a0ee3388c0ecb736a3/packages/dart/lib/src/objects/response/parse_exception_response.dart:18:18: Error: Non-nullable variable 'errorResponse' must be assigned before it can be used.
        message: errorResponse['error']?.toString() ??
                 ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/git/Parse-SDK-Flutter-123876a10d997f5bded788a0ee3388c0ecb736a3/packages/dart/lib/src/objects/response/parse_exception_response.dart:21:15: Error: Non-nullable variable 'errorResponse' must be assigned before it can be used.
        code: errorResponse['code'] ?? exception.response?.statusCode,
              ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/git/Parse-SDK-Flutter-123876a10d997f5bded788a0ee3388c0ecb736a3/packages/dart/lib/src/objects/response/parse_exception_response.dart:26:22: Error: The argument type 'Object' can't be assigned to the parameter type 'Exception?'.
 - 'Object' is from 'dart:core'.
 - 'Exception' is from 'dart:core'.
          exception: error);
```

**Comment by RodrigoSMarques** [comment]
@gcostaapps 
We are adjusting the version will be available tonight.

**Comment by RodrigoSMarques** [comment]
Hello Guys, run the test and report the problems.

```dart
  parse_server_sdk_flutter:
    git:
      url: https://github.com/parse-community/Parse-SDK-Flutter.git
      ref: nullsafety
      path: packages/flutter
```
@gcostaapps @NuclleaR  @rlazom

**Comment by NuclleaR** [comment]
@RodrigoSMarques why`initialize` method returns `Future<sdk.Parse>` instead of `Future<Parse>` like it was previously?
`Parse` class has additional methods. It breaks backward compatibility

**Comment by RodrigoSMarques** [comment]
@NuclleaR 
I'll adjust. I was giving type errors, but I found the solution.

**Comment by RodrigoSMarques** [comment]
@NuclleaR 
New commit performed. Please test again.

**Comment by RodrigoSMarques** [comment]
Hi guys.

Has anyone done tests? Any feedback? Everything working?

**Comment by gcostaapps** [comment]
@RodrigoSMarques I've just tested authentication right now and it's working, I'll test more features from the sdk in the next week.

**Comment by gcostaapps** [comment]
I think the error from the logout method is in the unpin, now the code looks like:
```
Future<bool> unpin({String? key}) async {
    if (objectId != null) {
      await ParseCoreData().getStore().remove(key ?? objectId!);
      return true;
    }

    return false;
  }
```
In the loggout the objectId is null but the key isn't. The code works well when I changed the if method to:
`if(objectId != null || key != null)`

**Comment by RodrigoSMarques** [comment]
> I think the error from the logout method is in the unpin, now the code looks like:
> 
> ```
> Future<bool> unpin({String? key}) async {
>     if (objectId != null) {
>       await ParseCoreData().getStore().remove(key ?? objectId!);
>       return true;
>     }
> 
>     return false;
>   }
> ```
> 
> In the loggout the objectId is null but the key isn't. The code works well when I changed the if method to:
> `if(objectId != null || key != null)`

Thanks for the feedback.
I will make the fix.

**Comment by pastordee** [comment]
hi guys I'm still getting this error 
 When the exception was thrown, this was the stack:
#0      ParseLiveListWidget.createState (package:parse_server_sdk_flutter/src/utils/parse_live_list.dart:53:47)

and is taken me to this 
_ParseLiveListWidgetState<T> createState() => _ParseLiveListWidgetState<T>(
        query: query,
        removedItemBuilder: removedItemBuilder!, <===========
        listenOnAllSubItems: listenOnAllSubItems,
        listeningIncludes: listeningIncludes,
        lazyLoading: lazyLoading,
        preloadedColumns: preloadedColumns,
      );


and this is how I'm calling it 
Expanded(
                flex: 1,
                child: ParseLiveListWidget<Prayer>(
                  query: controller.getAllPrayers(),
                  listenOnAllSubItems: true,
                  lazyLoading: false,
                  duration: const Duration(milliseconds: ParseLiveListDuration),
                  childBuilder: (BuildContext context,
                      ParseLiveListElementSnapshot<Prayer> snapshot) {
                    if (snapshot.failed) {
                       return const Text('something went wrong!');
                    } else
                    if (snapshot.hasData) {
                      
                      return PrayerItem(snapshot.loadedData); 
                    } else {
                      return ProfileShimmer(
                        padding: const EdgeInsets.all(5.0),
                        hasBottomLines: true,
                        isDarkMode: darkMode ? true : false,
                      );
                    }
                  },
                  queryEmptyElement: queryEmptyElement("No Prayers available"),
                  listLoadingElement: ProfileShimmer(
                    padding: const EdgeInsets.all(5.0),
                    hasBottomLines: true,
                    isDarkMode: darkMode ? true : false,
                  ),
                ),
              ),

In my controller
QueryBuilder<Prayer> getAllPrayers() {
    return QueryBuilder<Prayer>(Prayer())
      ..includeObject(["user"])
      ..setLimit(100)
      ..orderByDescending("createdAt");
  }

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques I've just tested authentication right now and for me it seems that the logout method isn't deleting value from storage. When I logout and then restart the app the method to get the current user still returns the user that was logged before.
> 
> Also, the docs seems to have the parameters from login with google swapped. In the docs the login with google is:
> 
> ```
> await ParseUser.loginWith(
>         'google',
>         google(_googleSignIn.currentUser!.id, 
>                authentication.accessToken!, 
>                authentication.idToken!));
> ```
> 
> The code that woked was:
> 
> ```
> await ParseUser.loginWith(
>           'google',
>           google(authentication.accessToken!, _googleSignIn.currentUser!.id,
>               authentication.idToken!));
> ```
> 
> (I've put the ! in the nullable fields)
> 
> I'll test more features from the sdk in the next week.

You were right. Updated documentation

**Comment by RodrigoSMarques** [comment]
> and this is how I'm calling it

The parameter `removedItemBuilder`. 
Aren't you passing it on to the ParseLiveListWidget?
It is required. Did it work before?

**Comment by pastordee** [comment]
> > and this is how I'm calling it
> 
> The parameter `removedItemBuilder`.
> Aren't you passing it on to the ParseLiveListWidget?
> It is required. Did it work before?

Yes it did work before

**Comment by pastordee** [comment]
> > and this is how I'm calling it
> 
> The parameter `removedItemBuilder`.
> Aren't you passing it on to the ParseLiveListWidget?
> It is required. Did it work before?

I have added it and it works fine but it only loads the first 100 items

**Comment by wangbo4020** [comment]
We quite looked forward to the version of nullsafety!
So, how long publish the version of nullsafety.

**Comment by gcostaapps** [comment]
I'm trying LiveQueries now and it seems that it's not working here. 

I've tried to listen to the stream events from the LiveList but it didn't fire.

I've also tried use ParseLiveListWidget but the items don't update. I've tried to create new items in the parse dashboard and updating the fields of the items but none of these options worked. I only get the list of the actual values and get it update just if I leave the page and open it again.

Here's my ParseLiveList

`
ParseLiveListWidget<ParseObject>(
      query: QueryBuilder(ParseObject('Notebook'))
        ..whereEqualTo('userId', 'kY0RifKueR'),
      lazyLoading: false,
      listenOnAllSubItems: true,
      removedItemBuilder: (context, snapshot) {
        return Container();
      },
      shrinkWrap: true,
      scrollPhysics: NeverScrollableScrollPhysics(),
      listLoadingElement: Center(
        child: CircularProgressIndicator(),
      ),
      childBuilder: (BuildContext context,
          ParseLiveListElementSnapshot<ParseObject> snapshot) {
        if (snapshot.failed) {
          return const Text('something went wrong!');
        } else if (snapshot.hasData) {
          return Padding(
            padding: const EdgeInsets.only(bottom: 24),
            child: NotebookBarItem(
              notebook:
                  Notebook.fromJson(snapshot.loadedData.toString()),
              isSelected: false,
              onTap: () => {},
            ),
          );
        } else {
          return ListTile(
            title: Text(
              "loading comment from: ${snapshot.preLoadedData?.get<ParseObject>("sender")?.get<String>("username")}",
            ),
          );
        }
      },
    )
`

**Comment by gcostaapps** [comment]
@RodrigoSMarques  I've found a error but I can't find a solution for it, I think it's related to the nullsafety migration.

I have a class Card that have a pointer Tag that can be null. 

When I watch the a card object using LiveQuery including the pointer, when a new card object is added that doesn't have a tag I got an error. I've found some places that I fixed but the error is still here.

The stacktrace of the error is below:

```
I/flutter (16713): [ERROR] { exception: Null check operator used on a null value, stacktrace: #0      ParseLiveList._loadIncludes
package:parse_server_sdk/…/utils/parse_live_list.dart:268
I/flutter (16713): #1      ParseLiveList._objectAdded
package:parse_server_sdk/…/utils/parse_live_list.dart:353
I/flutter (16713): #2      ParseLiveList._init.<anonymous closure>.<anonymous closure>.<anonymous closure>
package:parse_server_sdk/…/utils/parse_live_list.dart:174
I/flutter (16713): #3      _rootRun (dart:async/zone.dart:1346:47)
I/flutter (16713): #4      _CustomZone.run (dart:async/zone.dart:1258:19)
I/flutter (16713): #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:176:18)
I/flutter (16713): #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:674:39)
```

Inside _loadIncludes there is the line bellow that doesn't accept null values, but even removing the '!' I still got the error and couldn't find how to fix it.

`
var includedObject = object.get<ParseObject>(key)!;
`

**Comment by 2shrestha22** [comment]
I got this problem, using parseObject.fromJson() then parseObject.save() succeeds but does no write any data into server.
Returns correct/desired response but in dashboard I only found objects with objectId and other filed as not defined.
#https://github.com/parse-community/Parse-SDK-Flutter/issues/568

**Comment by 2shrestha22** [comment]
Any update on this? When SDK with null safety will get released?

**Comment by RodrigoSMarques** [comment]
> Any update on this? When SDK with null safety will get released?

Version 3.0 of April 15 supports null safety.

For some reason, pub.dev did not put the null-safety seal on it.
