### ISSUE TITLE
Refactor Singleton CoreStoreSharedPrefs and Sembast

### ISSUE THREAD

**Issue by nstrelow** [parse-community/Parse-SDK-Flutter#574]
Low Prio

A singleton is great for certain aspects.
But the singletons of CoreStore take arguments. The next time I am calling `getInstance`, but with different arguments, I get the old instance initialized with the old parameters back.

Is the `getInstance()` something a user would call multiple times?

The flow would usually be to create the store at the start of the app on parse init. As it is not created often, it would be better to have a normal constructor for CoreStore and construct it each time.
This would then also correctly initialize it each time, also when changing the parameters.

**Comment by RodrigoSMarques** [comment]
If you can contribute by submitting a PR for these changes, we would be grateful.

Wait for the version with null safety

**Comment by nstrelow** [comment]
@RodrigoSMarques I am working on null safety right now.
Check out https://github.com/nstrelow/Parse-SDK-Flutter/tree/nullsafety

**Comment by RodrigoSMarques** [comment]
I want to release a version 3.0 prepared for null safety, as soon as possible.
There is a lot to improve in the code.
We will leave these improvements to a version 3.1
