### ISSUE TITLE
Do not return something on a Future<void> function

### ISSUE THREAD

**Issue by nstrelow** [parse-community/Parse-SDK-Flutter#575]
Very low prio and very easy.

We have a lot of Future<void> function which use the return keyword.

We should remove that, as it doesn't do anything, or maybe even does something we do not want it to.

core_store implementations have a lot of those.

Basically replace:
```
Future<String?> getString(String key) async {
    return await get(key);
}
```
with:
```
Future<String?> getString(String key) async {
    await get(key);
}
```

**Comment by RodrigoSMarques** [comment]
If you can contribute by submitting a PR for these changes, we would be grateful.

Wait for the version with null safety
