### ISSUE TITLE
Parse: Cache ParseCoreData instead of recalling the consturctor

### ISSUE THREAD

**Issue by nstrelow** [parse-community/Parse-SDK-Flutter#577]
Low prio
Possibly is done throughout the framework, so if changing, maybe change everything?

Maybe this is also a fundamental design of this framework.

Have a Singleton for everything, instead of having the implementer decide on how or if to cache a specific object.

in dart/lib/parse_server_sdk.dart:

Instead of calling ParseCoreData() everytime, cache it in a class member after init.

**Comment by RodrigoSMarques** [comment]
If you can contribute by submitting a PR for these changes, we would be grateful.

Wait for the version with null safety
