### ISSUE TITLE
ParseHttp/DioClient: additionalHeaders is never used.

### ISSUE THREAD

**Issue by nstrelow** [parse-community/Parse-SDK-Flutter#578]
Prio: Medium
Easy

additionalHeaders is never used by anything. Remove it.

**Comment by RodrigoSMarques** [comment]
If it has never been used. Let's remove.

**Comment by nstrelow** [comment]
I retract my issue, as I understood how it is used now.

The idea is to make a new class inherit from ParseHttpClient.
The one can override the additionalHeaders property.

`@override additionalHeaders = {"my-custom-company-header", "value"}`

I find that very confusing, and I am not sure if somebody ever used this.
A much better alternative would be to have a property, when calling clientCreator with ParseHttpClient:
`ParseHttpClient(additionalHeaders: ...)`
