### ISSUE TITLE
ParseBase: get defaultValue is not required => Returns null when key not found

### ISSUE THREAD

**Issue by nstrelow** [parse-community/Parse-SDK-Flutter#581]
Prio medium (or do nothing)
BREAKING CHANGE: Makes defaultValue required. **OR** we leave it as nullable.

get:
When the key is not found in the objectData, then the defaultValue is returned. But the defaultValue is not required.
Thus when key not found in objectData AND defaultValue not provided, app crashes at runtime.

**Comment by RodrigoSMarques** [comment]
Leave as nullable, just like in the native SDK.

A value of null indicates that the field does not exist or has no defined value.

How to assign a default value for a date?
