### ISSUE TITLE
ParseRelation: Key is a required attribute

### ISSUE THREAD

**Issue by nstrelow** [parse-community/Parse-SDK-Flutter#583]
Prio medium
BREAKING CHANGE: If people were not specifying the key. Without it, it shouldn't work though.

**Comment by RodrigoSMarques** [comment]
ParseRelation needs a review.

AddRelation and RemoveRelation work, but retrieving the results with getQuery does not.

**Comment by RodrigoSMarques** [comment]
I refactored the ParseRelation code and set the attribute as required.
The getQuery method is also working.
Completing the tests.
