### ISSUE TITLE
Push notification

### ISSUE THREAD

**Issue by kharitonovAL** [parse-community/Parse-SDK-Flutter#584]
Hi!

Is there any work around push notifications for this SDK? Or everyone have to wrote it's own solution?

Thanks!

**Comment by RodrigoSMarques** [comment]
This has been discussed previously here:

#200 and #302

**Comment by kharitonovAL** [comment]
> This has been discussed previously here:
> 
> 
> 
> #200 and #302

Thanks @RodrigoSMarques 

I failed while trying to search for issue that contains "push...".

Closing!
