### ISSUE TITLE
[Web][Dart 2.7][Null-safety]DioClient compile error

### ISSUE THREAD

**Issue by nstrelow** [parse-community/Parse-SDK-Flutter#588]
#### Only on Flutter Web and only (probably) on Dart SDK below 2.12

For some unknown reason, the compilation for Flutter Web is failing when using null-safety (#579 Not yet merged).\
DioClient does not have to be used, for the error to occur.

```
../../Parse-SDK-Flutter/packages/dart/lib/src/network/parse_dio_client.dart:134:49: Error: The argument type 'SecurityContext?' can't be assigned to the parameter type 'SecurityContext' because 'SecurityContext?' is nullable and 'SecurityContext' isn't.
 - 'SecurityContext' is from 'dart:io'.
    httpClientAdapter = createHttpClientAdapter(securityContext);
```

This error makes no sense, because `SecuirtyContext` is defined as `SecurityContext?` (nullable) everywhere.
Somehow `createHttpClientAdapter` expects a non-nullable `SecurityContext`, but the code says otherwise.

To make the migration easier (or allow developers to not migrate their own apps), we should provide backwards compatibility. The backwards compatibility to Dart SDK 2.7 is given, except for this annoying error.

**Comment by nstrelow** [comment]
Maybe this has to do with
* SecurityContext is from dart:io
* dart:io is not supported on web

**Comment by RodrigoSMarques** [comment]
> Maybe this has to do with
> 
> * SecurityContext is from dart:io
> * dart:io is not supported on web


The problem should be here:
`dio_adapter_js.dart`

It has not been migrated

**Comment by fischerscode** [comment]
I think adding a [stub](https://github.com/fischerscode/ParseServer-OpenID-Flutter/blob/master/parseserver_openid_flutter/lib/src/openid_stub.dart) version would be a good idea, too. It makes pub.dev happy.

**Comment by RodrigoSMarques** [comment]
> I think adding a [stub](https://github.com/fischerscode/ParseServer-OpenID-Flutter/blob/master/parseserver_openid_flutter/lib/src/openid_stub.dart) version would be a good idea, too. It makes pub.dev happy.

Yes. [https://dart.dev/tools/pub/publishing#publishing-prereleases](https://dart.dev/tools/pub/publishing#publishing-prereleases)

**Comment by nstrelow** [comment]
@RodrigoSMarques AWESOME CATCH!!!

DAMN just going through the code always let me to the wrong implementation.

**Comment by nstrelow** [comment]
My web app now works. Thanks again for catching @RodrigoSMarques.

Now I can finally use the SDK as I did before 🙈 

Hurray to null-safety.
