### ISSUE TITLE
ParseObject: Object's data gets updated instead of inserting new data

### ISSUE THREAD

**Issue by keanallen** [parse-community/Parse-SDK-Flutter#593]
I have this strange experience, I wanted to save a data. It saves on the first time, but when i save again it will override/update the current data in the database.

Here is my code:
```
class ParseProvider{
    static final testObject = ParseObject('TestObject');
}
```
and in my controller: where my saving method was define

```
saveData() async {
    var _testObj = ParseProvider.testObject
         ..set('col1',  'val1')
         ..set('col2', 'val2')
         ..set('etc', '...');
    var response = await _testObj.save();
}
```
The code above will save at the first time, but when I save again it just updates/append the data in the database.

**The Fix to my issue:**
_Instead of:_ `var _testObj = ParseProvider.testObj`

_I changed it to:_ `var _testObj = ParseObject('TestObject')`

And all is well. Im just wondering what am I  doing wrong 😁

**Comment by RodrigoSMarques** [comment]
Hi @keanallen 

As you defined the object as static when it is saved for the first time, the `objectId` property is set.

As it is the same `object` (static), in the next calls of the `save` an `update` will be made and not an `insert`.

If you remove the static from the variable it should already work.

**Comment by keanallen** [comment]
OHHHH. So that's why. Thank you!
