### ISSUE TITLE
added data to ParseUser is 'undefined'

### ISSUE THREAD

**Issue by RyanBuss01** [parse-community/Parse-SDK-Flutter#594]
I'm trying to add an object to ParseUser using this code:

```
Future<void> createUserData(ParseUser user, String setDisplayname) async {
  user.set('displayname', setDisplayname);
  await user.save();
}
```

the data 'displayname' appears in the server as an array that is 'undefined' instead of the String I provided

**Comment by RodrigoSMarques** [comment]
> the data 'displayname' appears in the server as an array that is 'undefined' instead of the String I provided

try
```dart

Future<void> createUserData(ParseUser user, String setDisplayname) async {
  user.set<String>('displayname', setDisplayname);
  await user.save();
}
```

**Comment by RyanBuss01** [comment]
That doesn't seem to help I am still having the same problem

**Comment by RyanBuss01** [comment]
I partially fixed my problem my issue was in the parent function 

I originally had:

```
void doUserRegistration(String email, String password) async {
  final user = ParseUser.createUser(email, password, email);
  var response = await user.signUp();
  if (response.success) {
    await createUserData(displayName, email);
    Message.showSuccess()  // custom class
  }
}
```

so I put the function before the user.signUp function like this:

```
void doUserRegistration(String email, String password) async {
  final user = ParseUser.createUser(email, password, email);
  user.set<String>('displayname', displayName);
  var response = await user.signUp();
  if (response.success) {
    Message.showSuccess()  // custom class
  }
}
```
although this does fix my immediate problem I don't know if I can't change this variable in the future after having signed up the user or if I'm just missing something. In any case I will close this since the issue is resolved
