### ISSUE TITLE
Update package path_provider

### ISSUE THREAD

**Issue by jjunineuro** [parse-community/Parse-SDK-Flutter#597]
Hey guys,

With the publication of the version Flutter 2.0, the stable web version was released. However, when using the "device_info_plus" package it is not possible due to the "path_provider" plugin is out of date in our SDK. Can this be checked please?

`Because device_info_plus >=1.0.0 depends on device_info_plus_platform_interface ^1.0.0 which depends on plugin_platform_interface ^2.0.0, device_info_plus >=1.0.0 requires plugin_platform_interface ^2.0.0.
And because path_provider >=1.6.4 <2.0.0-nullsafety depends on path_provider_platform_interface ^1.0.1 which depends on plugin_platform_interface ^1.0.1, device_info_plus >=1.0.0 is incompatible with path_provider >=1.6.4 <2.0.0-nullsafety.
And because parse_server_sdk_flutter 2.1.0 depends on path_provider ^1.6.27 and no versions of parse_server_sdk_flutter match >2.1.0 <3.0.0, device_info_plus >=1.0.0 is incompatible with parse_server_sdk_flutter ^2.1.0.
So, because office depends on both parse_server_sdk_flutter ^2.1.0 and device_info_plus ^1.0.0, version solving failed.
pub get failed (1; So, because office depends on both parse_server_sdk_flutter ^2.1.0 and device_info_plus ^1.0.0, version solving failed.)`

**Comment by RodrigoSMarques** [comment]
Include in pubspec.yaml

``dart
dependency_overrides:
  plugin_platform_interface: ^2.0.0
```

**Comment by jjunineuro** [comment]
Thank you!
