### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by yp19** [parse-community/Parse-SDK-Flutter#598]

**Comment by RodrigoSMarques** [comment]
There is a fixed issue about this problem.

But you can check here:

#541 a #573

**Comment by keanallen** [comment]
Currently im using `parse_server_sdk_flutter`
What's the difference between `parse_server_sdk`?

**Comment by RodrigoSMarques** [comment]
`parse_server_sdk` It is a package that uses 100% dart code, without depending on plugins that are linked to the operating system and with this it can run on all platforms.
The parse_server_sdk_flutter package currently supports only Mobile and Web.

**Comment by keanallen** [comment]
So, i will not run into any problem if I switched from flutter parser
server sdk to parse server sdk? Because Im 80% done with our project now.

**Comment by RodrigoSMarques** [comment]
> So, i will not run into any problem if I switched from flutter parser server sdk to parse server sdk? Because Im 80% done with our project now.
> […](#)

If your project is mobile and web, you must use the package parse_server_sdk_flutter

**Comment by keanallen** [comment]
Ohhh ok. Thanks man!

**Comment by RodrigoSMarques** [comment]
April 15th version 3.0 supports null safety
