### ISSUE TITLE
Error when I try to transform a response.result in a Object

### ISSUE THREAD

**Issue by gustavopv94** [parse-community/Parse-SDK-Flutter#600]
Hello guys, 

I have two Object (Subject and Content)
The Subject object has the attributes:

`String id;
String title;
DateTime createdAt;
User user;`

The Content object has the attributes:
```
String id;
String title;
DateTime createdAt;
Subject subject;
User user;
```
i have a save method to save the content object

```
`Future<Content> save(Content content) async{
  try{
    final parseUser = await ParseUser.currentUser();
    final contentObject = ParseObject(kContentTable);
 
    final parseAcl = ParseACL(owner: parseUser);
    parseAcl.setPublicReadAccess(allowed: false);
    parseAcl.setPublicWriteAccess(allowed: false);
    contentObject.setACL(parseAcl);
 
    contentObject.set<String>(kContentTitle, content.title);
    
    contentObject.set<ParseObject>(kContentSubject, ParseObject(kSubjectTable)
      ..set(kSubjectId, content.subject.id));
 
    contentObject.set<ParseUser>(kSubjectOwner, parseUser);
 
    final response = await contentObject.save();
 
    if(response.success){
      return mapParseToContent(response.result);
    }else{
      return Future.error(ParseErrors.getDescription(response.error.code));
    }
 
  }catch(e){
    return Future.error('Falha ao salvar conteúdo!');
  }
}`
```

So if it succeeds, I would like to return a Content Object. And for that there is the map method:

```
`Content mapParseToContent(ParseObject parseObject){
  return Content(
      id: parseObject.objectId,
      title: parseObject.get(kContentTitle),
      createdAt: parseObject.get(kContentCreatedAt),
      subject: SubjectRepository().mapParseToSubject(parseObject.get<ParseObject>(kContentSubject)),
      user: UserRepository().mapParseToUser(parseObject.get<ParseUser>(kContentOwner))
  );
}`
```

As the Subject object is a Pointer, I need to make a map of this pointer, and for that there is the method:

```
`Subject mapParseToSubject(ParseObject parseObject){
  return Subject(
    id: parseObject.objectId,
    title: parseObject.get(kSubjectTitle),
    createdAt: parseObject.get(kSubjectCreatedAt),
    contents: parseObject.get(kSubjectContents),
    user: UserRepository().mapParseToUser(parseObject.get<ParseUser>(kSubjectOwner))
  );
}`
```

The save method succeeds and returns:
Payload: {"className":"Content","objectId":"a19rf06PxP","createdAt":"2021-04-19T00:49:38.056Z","ACL":{"w2ZS5l9rI1":{"read":true,"write":true}},"title":"123","subject":{"__type":"Pointer","className":"Subject","objectId":"ML8CudfbEH"},"topics":["12"],"numberOfReview":0,"owner":{"__type":"Pointer","className":"_User","objectId":"w2ZS5l9rI1"}}

but when trying to map the subject an error happens.
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Failed to save content!

Does anyone know what problem this is?

**Comment by Mabenan** [comment]
I think it is better to let your Objects extend ParseObject and implement properties to hide the get and set methods.

so it would look like this

`
class Content extends  ParseObject {
 Content() : super("Content");
Content.clone() : this();

  @override
  clone(Map map) => Content.clone()..fromJson(map);

String get title() => get<String>("Title");
set title(String title) => set<String>("Title", title);
}
` 

Then after you have registered the class in the Parse.initialized like this
`
Parse().initialize(
...
 registeredSubClassMap: {"Content":() => Content()}
...
)
`
You can simply cast response.result to Content;
The same goes for Subject

**Comment by mtgnoah** [comment]
> You can simply cast response.result to Content;
> The same goes for Subject
So for casting you just map the response to that model? I'm trying something similar in issue #617 and it is having a lot of issues currently with it saying the response is null when the cloud code is returning something.
