### ISSUE TITLE
Web support Status Code -1

### ISSUE THREAD

**Issue by MaIronCool** [parse-community/Parse-SDK-Flutter#634]
Start parse-server
`parse-server --databaseURI postgres://postgres:123@localhost:5432/postgres --serverURL http://localhost:1337/parse --appId myAppId --masterKey mymasterkey --allowOrigin * --allowHeaders x-parse-installation-id,x-parse-application-id,x-parse-client-key`
In android studio - flutter run -d chrome (Web mode)

2. Dart code 
```
await Parse().initialize(keyParseApplicationId, keyParseServerUrl,
 clientKey: keyParseClientKey,
        autoSendSessionId: true,
        debug: true,
        coreStore: await CoreStoreSharedPrefsImp.getInstance());
final ParseResponse response = await Parse().healthCheck();

```

Then get error - on Android works fine:
-- Parse Request
curl -X GET -H 'X-Parse-Application-Id: myAppId' -H 'X-Parse-Client-Key: mymasterkey' http://localhost:1337/parse/health

 http://localhost:1337/parse/health
╰--
╭-- Parse Response
Class: parseBase
Function: ParseApiRQ.healthCheck
Status Code: -1
Type: UnknownError
Exception: XMLHttpRequest error.
╰--_

**Comment by MaIronCool** [comment]
Wrong IP adress

**Comment by rameshkec85** [comment]
@MaIronCool Hi, How to fix this ? Without masterkey, web is not working. Can you help me on this?
