### ISSUE TITLE
Can't configure additionalHeaders in ParseHTTPClient anymore.

### ISSUE THREAD

**Issue by Moomba42** [parse-community/Parse-SDK-Flutter#635]
I'm unable to set additionalHeaders on the ParseHTTPClient class anymore.
Previously this field was publicly accessible, but now it has been moved to a private class which is used in a private field.
This bug prevents me from migrating to the current version of the library.

**Affected Versions**
\>=2.1.0

**Caused by**
Added ParseClient to abstract dio and http (#495)
Commit e37236fa15c90e54e36ee19069c01d8ea0ce9c10

**Proposed Solution**
Expose the additionalHeaders field from the _ParseHTTPClient class outside of the ParseHTTPClient class using a getter/setter.

I will create a PR for this and add it to this issue.

**Comment by Moomba42** [comment]
Since the PR is merged and working, im closing this issue. Thanks.

**Comment by rs5173** [comment]
This solution cannot dynamically add Headers. Perhaps we can provide an interceptor when ClientCreator is initialized so that users can customize Request and Response.

Of course, you can also directly inherit ParseClient or ParseDioClient, and then add your own Headers in all request methods
