### ISSUE TITLE
Can I fetch objects from multiple tables in one parse query using this library?

### ISSUE THREAD

**Issue by perilousGourd** [parse-community/Parse-SDK-Flutter#643]
Can I fetch objects from multiple tables in one parse query/request using this library?
Something similar to what I understand a union would achieve in SQL?

<details>
<summary>
<b>Context / use case for clarity</b>
</summary>

In a note-taking style app I'm writing, a series of objects may appear sequentially in a 'note', e.g. a question object, an answer object, an exposition object, a sketch object, another exposition object etc.

The note table has a column containing an array of objectIds, which can point to rows in any of the other tables.

Upon loading a note object, I want to acquire all objects it 'contains' in as few requests as possible.

What I envisaged:

`QueryBuilder queryBuilder = QueryBuilder<ParseObject>(ParseObject(['Question', 'Answer', 'Sketch']))..whereContainedIn('objectId', listOfObjectIds);`
where ParseObject() constructor contains a list of possible classes, rather than one, or

`QueryBuilder queryBuilder = QueryBuilder<ParseObject>(ParseObject())..whereContainedIn('objectId', listOfObjectIds);`
where ParseObject() is an undifferentiated / non-specific ParseObject, and the query would return json that I could parse into ParseObjects of appropriate type (Question, Answer, Sketch etc) in-app.
</details>

**Comment by fischerscode** [comment]
I think the SDK does not support this and maybe the Parse server doesn't either.

In case you want to reduce the number of requests the client has to send, using a cloud function might work for you.
The other option would be to fetch the classes separately and then merge the list at the client.
Personally I would go for the merge strategy, as it would avoid unnecessary stress on your server.

**Comment by perilousGourd** [comment]
Thanks for the insight! I'm going with separate fetches and merging.
I'm content to close, with the assumption that if someone encounters this and disagrees, or if something changes, they'll reopen?
