### ISSUE TITLE
Currentuser null even after loggin

### ISSUE THREAD

**Issue by hemanthkb97** [parse-community/Parse-SDK-Flutter#651]
main.dart

await Parse().initialize(
    appId,
    "https://parseapi.back4app.com/",
    clientKey: _clientKey,
    debug: true,
  );

loggin page

login(String username, String password) async {
    ParseUser user = ParseUser(username, password, null);
    var res = await user.login();
    if (res.success) {
      user.getUpdatedUser();
      setState(() {
        loading = false;
      });
      var result = await ParseUser.currentUser();
      inspect(result);
    } else {
      setState(() {
        loading = false;
      });
      showSimpleNotification(Text(res.error!.message), background: Colors.red);
    }
debug log---

I/flutter (15060): ╭-- Parse Response
I/flutter (15060): Class: _User
I/flutter (15060): Function: ParseApiRQ.login
I/flutter (15060): Status Code: 200
I/flutter (15060): Payload: {"className":"_User","objectId":"nABM5alZkZ","createdAt":"2021-06-29T18:43:11.954Z","updatedAt":"2021-06-30T09:34:15.101Z","username":"hemanthkumar","email":"_email","emailVerified":true,"ACL":{"*":{"read":true,"write":false},"nABM5alZkZ":{"read":true,"write":true}},"sessionToken":"r:0f1134d62240c233b080ffa5427221cd"}
I/flutter (15060): ╰--
I/flutter (15060):
I/flutter (15060): ╭-- Parse Request
I/flutter (15060): curl -X GET -H 'X-Parse-Session-Token: r:0f1134d62240c233b080ffa5427221cd' -H 'user-agent: Flutter Parse SDK 3.1.0' -H 'X-Parse-Application-Id: apid' -H 'X-Parse-Client-Key: _clientkey' https://parseapi.back4app.com/users/me
I/flutter (15060):
I/flutter (15060):  https://parseapi.back4app.com/users/me

splashscreen
var result = await ParseUser.currentUser();
    inspect(await ParseUser.currentUser());
    inspect(result);
    if (result == null) {
      Navigator.pushAndRemoveUntil(
          context,
          PageRouteBuilder(
              pageBuilder: (context, animation, anotherAnimation) {
                return Welcomepage();
              },
              transitionDuration: Duration(milliseconds: 600),
              transitionsBuilder:
                  (context, animation, anotherAnimation, child) {
                return SlideTransition(
                  position:
                      Tween(begin: Offset(0.0, 1.0), end: Offset(0.0, 0.0))
                          .animate(animation),
                  child: child,
                );
              }),
          (route) => false);
    } else {
      ParseUser user = result as ParseUser;
      inspect(user);
}

pubspec.yaml
parse_server_sdk: ^3.1.0

i get current user null whenever i reload app.

**Comment by hemanthkb97** [comment]
my bad 
because parse_server_sdk_flutter 3.1.0  this didt had null safety tag i thought i need to use dart package now its working :)

**Comment by Faari7** [comment]
I am facing the same issue, could you please tell me how did you solve it?
