### ISSUE TITLE
Subclassing ParseUser

### ISSUE THREAD

**Issue by byroncoetsee** [parse-community/Parse-SDK-Flutter#656]
In the iOS version of the SDK, one can subclass `PFUser`, register the subclass in `AppDelegate` and from then on, one can call upon the subclass as if it were `PFUser`... This means you can add extra attributes to the User object and use something like `PFUser.currentUser().name` instead of having to rely on key/value type functions to get a value out... 

TL;DR - I've added an extra column to my _User class on Parse... How do I now (in Flutter) do something like `User.currentUser().name` instead of `ParseUser.currentUser()['name']`

**Comment by hemanthkb97** [comment]
use,
user= await ParseUser.currentUser;
user.set(key,value)
user.save();

**Comment by byroncoetsee** [comment]
Thanks but I specifically said `instead of having to rely on key/value type functions to get a value out`
You've also missed the point. My question is around getting values out and subclassing ParseUser - not saving.

**Comment by RodrigoSMarques** [comment]
ParseUser is a ParseObject.

The way to retrieve is the same as for ParseObject

Try:

```dart
final ParseUser currentUser = await ParseUser.currentUser() as ParseUser;

print(currentUser.get<String>('name'));
```

**Comment by byroncoetsee** [comment]
Casting with `as ParseUser` makes no difference as the original object is of type `ParseUser`.
I'd love to answer the question of "Can I subclass ParseUser" so I can create a computed property (which uses key/value things) to then be able to use `.name` instead of `.get<String>('name')` every time.

**Comment by phillwiggins** [comment]
Do you mean like the example here?

https://github.com/parse-community/Parse-SDK-Flutter/blob/master/packages/flutter/example/lib/data/model/user.dart

**Comment by byroncoetsee** [comment]
Oh that looks promising! Thank you - will give it a try a bit later and get back to you. Thanks so much Phill.

**Comment by byroncoetsee** [comment]
Ok so I've tried implementing almost exactly what they have there, only with a single attr (`name`).
The issue I'm now having is I can't actually use a piece of their code [here](https://github.com/parse-community/Parse-SDK-Flutter/blob/f40cb527ac041c87a5c17904d66f4b936745c484/packages/flutter/example/lib/data/repositories/user/provider_api_user.dart#L15)

When trying to implement 
```
Future<User> currentUser() {
    return ParseUser.currentUser();
 }
```
It tells me `A value of type 'Future<dynamic>' can't be returned from the method 'currentUser' because it has a return type of 'Future<User>'` which does make sense I suppose. I'm not very experienced in Dart at all but have tried wrapping, casting, awaiting and a bunch of other things but to no avail. Kinda weird that I'm getting an error on code which clearly worked for them 😕 

Any further advice? I appreciate your time 🙏🏼

**Comment by byroncoetsee** [comment]
Finally figured it out with the help of @davimacedo 

As I suspected, one has to register the subclass. I just couldn't find any info on it.

```
await Parse().initialize(
      ...,
      parseUserConstructor: (username, password, emailAddress, {client, debug, sessionToken}) => CustomUser(username, password, emailAddress));
```
