### ISSUE TITLE
Remove function in Parse-sdk-flutter

### ISSUE THREAD

**Issue by dungnc** [parse-community/Parse-SDK-Flutter#658]
I have a ParseObject.
ParseObject group.
group["date"] is a DateTime.
I can not remove "date" in group.
I tried change ParseObject to Json then remove and save() but It didn't work.
Help me.

**Comment by RodrigoSMarques** [comment]
Try
```dart
group.unset('date');
await group.save();
```

**Comment by dungnc** [comment]
Oh it work. Thank you so much.
