### ISSUE TITLE
Permission denied, user needs to be authenticated.

### ISSUE THREAD

**Issue by keanallen** [parse-community/Parse-SDK-Flutter#665]
This error occurs when executing cloud functions. The error start to show after we have set Permissions on the backend. Even though the app user is logged in.

```
Class: seenByProvider
Function: ParseApiRQ.execute
Status Code: 101
Type: ObjectNotFound
Error: Permission denied, user needs to be authenticated.
```

**Comment by RodrigoSMarques** [comment]
You must have configured your class's CLP to allow only authenticated users access.

The problem is described in the message. User must login first.

**Comment by keanallen** [comment]
> You must have configured your class's CLP to allow only authenticated users access.
> 
> The problem is described in the message. User must login first.

Yes, we have set in that way. Even though the user is logged in, the error is still the same. But in other cloud functions, it works fine. Any idea why?

**Comment by RodrigoSMarques** [comment]
Which version are you using?

In older versions, you needed to set the `autoSendSessionId` parameter in `Parse().initialize` to `true`.

In newer versions the default value is `true`.

You can check?

**Comment by keanallen** [comment]
> Which version are you using?
> 
> In older versions, you needed to set the `autoSendSessionId` parameter in `Parse().initialize` to `true`.
> 
> In newer versions the default value is `true`.
> 
> You can check?

I am currently in version `3.0.0` and I did declare the `autoSendSessionId:true` in `main.dart`

**Comment by keanallen** [comment]
After googling, finally found a solution. In parse cloud code function we should pass a paramater:
```
{sessionToken: request.user.getSessionToken()}
```

Example:
```
// When saving an object
await yourObject.save(null, {sessionToken: request.user.getSessionToken()} );

/// When fetching records
await userQuery.find({sessionToken: request.user.getSessionToken()});
```

**Comment by RodrigoSMarques** [comment]
> After googling, finally found a solution. In parse cloud code function we should pass a paramater:
> 
> ```
> {sessionToken: request.user.getSessionToken()}
> ```
> 
> Example:
> 
> ```
> // When saving an object
> await yourObject.save(null, {sessionToken: request.user.getSessionToken()} );
> 
> /// When fetching records
> await userQuery.find({sessionToken: request.user.getSessionToken()});
> ```

I never needed this scenario.

Good to know this.

**Comment by kennethsolomon** [comment]
> After googling, finally found a solution. In parse cloud code function we should pass a paramater:
> 
> ```
> {sessionToken: request.user.getSessionToken()}
> ```
> 
> Example:
> 
> ```
> // When saving an object
> await yourObject.save(null, {sessionToken: request.user.getSessionToken()} );
> 
> /// When fetching records
> await userQuery.find({sessionToken: request.user.getSessionToken()});
> ```

Thank you so much !!
