### ISSUE TITLE
Facebook auth is invalid for this user

### ISSUE THREAD

**Issue by keanallen** [parse-community/Parse-SDK-Flutter#669]
Why I can't even login to facebook, even though I did all the steps [mentioned here](https://www.back4app.com/docs/flutter/parse-sdk/users/flutter-facebook-login).

Whenever I tried to login using facebook, it gives me an error:
```Facebook auth is invalid for this user```

```
final Map<String, dynamic> authData = <String, dynamic>{};
      authData['id'] = accessToken.userId;
      authData['token'] = accessToken.token;
      authData['expiration_date'] = accessToken.expires.toString();
     

      final userData = await FacebookAuth.instance.getUserData();
      //Make sign in with Facebook
      final parseResponse = await ParseUser.loginWith('facebook', authData);

       if(parseResponse.success){
          // success 
        }else{
        // This error will be thrown
         print(parseResponse.error);
        }

```
Ive also tried to directly add the facebook authData (to User class' authData field) that I get from facebook and same error.

I have already added the `Facebook App ID` in the back4app Server Settings. And I think the issue is on the back4apps end

**Comment by RodrigoSMarques** [comment]
I have two projects set up with Facebook in Back4app working (including the one in the guide)

Delete Facebook App Id and add again.

Retest.

**Comment by keanallen** [comment]
Finally found the answer:

`authData` must be replace with `facebook()` object, it is an object declared in parse package.

```
loginWith('facebook', facebook(acessToken, userId, expiration));
```

**Comment by RodrigoSMarques** [comment]
That's good. 

But I don't think that's the problem.

```dart
      final parseResponse = await ParseUser.loginWith(
          'facebook', facebook(accessToken.token, accessToken.userId, accessToken.expires));


Map<String, dynamic> facebook(String token, String id, DateTime expires) {
  return <String, dynamic>{
    'access_token': token,
    'id': id,
    'expiration_date': expires.toString()
  };
}
```

The `Facebook` function does the same as this code:
```dart
      final Map<String, dynamic> authData = <String, dynamic>{};
      authData['id'] = accessToken.userId;
      authData['access_token'] = accessToken.token;
      authData['expiration_date'] = accessToken.expires.toString();
```

**Comment by keanallen** [comment]
Yes. The problem might be the key of the map.
