### ISSUE TITLE
Dispose of ParseObjects created by LiveList

### ISSUE THREAD

**Issue by Mabenan** [parse-community/Parse-SDK-Flutter#671]
Not 100% sure if I need to make something different but at the moment the dispose method of the ParseObjects created by ParseLiveListWidget is not called. I've just taken the LiveList Example and changed  the ParseObject Type to a extension of ParseObject and override the dispose method. Then call the Widget and after that navigate with pushReplacementNamed. When you set a breakpoint in the dispose methods of LiveList and ParseObject/SubObject you see that only the dispose method of the LiveList is called. So I see no point where I (as framework user) have to add some coding to get the dispose called.

I think the framework needs to dispose the object here:
https://github.com/parse-community/Parse-SDK-Flutter/blob/8548476baa771e89f6fdfcfa4813af7cb062ce40/packages/dart/lib/src/utils/parse_live_list.dart#L670

Because this should be the object which holds the ParseObject warm.

**Comment by mbfakourii** [comment]
This function is used in different places in the code, it is better not to delete it

**Comment by mtrezza** [comment]
Can we close this?

**Comment by mbfakourii** [comment]
> Can we close this?

Let me check more

**Comment by mbfakourii** [comment]
The ```dispose``` function is used in different places and I suggest not to delete it

**Comment by mtrezza** [comment]
Do you suggest this issue to be closed?

**Comment by mbfakourii** [comment]
Yes, I think it should be closed
