### ISSUE TITLE
problem in ParseWebFile

### ISSUE THREAD

**Issue by Gustavo-alves-fernandes** [parse-community/Parse-SDK-Flutter#674]
Nn the package parse server_sdk I'm trying to upload an image with ParseWebFile, however **file.name** it gives me the following error **Error: Unexpected null `value**```

`//A short example for storing a selected picture
//libraries: image_picker (https://pub.dev/packages/image_picker), image_picker_for_web (https://pub.dev/packages/image_picker_for_web)
PickedFile pickedFile = await ImagePicker().getImage(source: ImageSource.gallery);
ParseFileBase parseFile;
if (kIsWeb) {
  //Seems weird, but this lets you get the data from the selected file as an Uint8List very easily. 
  ParseWebFile file = ParseWebFile(null, name: null, url: pickedFile.path);
  await file.download();
  parseFile = ParseWebFile(file.file, name: **file.name**); 
} else {
  parseFile = ParseFile(File(pickedFile.path));
}
someParseObject.set("image", parseFile);
//This saves the ParseObject as well as all of its children, and the ParseFileBase is such a child. 
await someParseObject.save();`

**Comment by RodrigoSMarques** [comment]
In Flutter Web the filename is required in ParseWebFile.
ImagePicker for Web does not provide the filename.

```dart
PickedFile? pickedFile;
pickedFile  =
                    await ImagePicker().getImage(source: ImageSource.gallery);
     if (kIsWeb) {
                            //Flutter Web
                            parseFile = ParseWebFile(
                                await pickedFile!.readAsBytes(),
                                name: 'image.jpg'); //Name for file is required
                          } else {
                            //Flutter Mobile/Desktop
                            parseFile = ParseFile(File(pickedFile!.path));
                          }
````

**Comment by Gustavo-alves-fernandes** [comment]
> Nn the package parse server_sdk I'm trying to upload an image with ParseWebFile, however **file.name** it gives me the following error **Error: Unexpected null `value**```
> 
> `//A short example for storing a selected picture //libraries: image_picker (https://pub.dev/packages/image_picker), image_picker_for_web (https://pub.dev/packages/image_picker_for_web) PickedFile pickedFile = await ImagePicker().getImage(source: ImageSource.gallery); ParseFileBase parseFile; if (kIsWeb) { //Seems weird, but this lets you get the data from the selected file as an Uint8List very easily. ParseWebFile file = ParseWebFile(null, name: null, url: pickedFile.path); await file.download(); parseFile = ParseWebFile(file.file, name: **file.name**); } else { parseFile = ParseFile(File(pickedFile.path)); } someParseObject.set("image", parseFile); //This saves the ParseObject as well as all of its children, and the ParseFileBase is such a child. await someParseObject.save();`
