### ISSUE TITLE
relation.remove ？There seems to be a problem

### ISSUE THREAD

**Issue by jijkbird** [parse-community/Parse-SDK-Flutter#686]
### **prase flutter sdk 3.1.0**

[✓] Flutter (Channel stable, 2.5.0, on macOS 12.0.1 21A559 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
[✓] VS Code (version 1.61.2)
[✓] Connected device (3 available)

![WX20211029-224706](https://user-images.githubusercontent.com/20245625/139455949-ca6ad5a8-218f-4011-a8c6-cb4102920e23.png)
![WX20211029-225050](https://user-images.githubusercontent.com/20245625/139456255-93612ddc-a305-4bc8-97ca-e43ced0bf18e.png)

**Comment by LMBernardo** [comment]
May I ask why this was closed? I'm having this exact same problem but with a normal (non-ParseUser) ParseObject.
