### ISSUE TITLE
Handshake Exception

### ISSUE THREAD

**Issue by JTPenn-EG** [parse-community/Parse-SDK-Flutter#690]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description

Parse servers powered with nginx and has a Let's Encrypt SSL certificate will return a handshake exception on older android phones
I've noticed this behavior on more than 5 of my users (from ~200 user total), all they have in common is that they're running older android versions on older devices (Android 7 and lower)
I myself grabbed an old device (android 6) and experienced the issue myself.
Note: I've confirmed that the SSL certificate itself is valid and is not expired and has no problems in it

### Steps to reproduce

--

### Actual Outcome

```
Message: HandshakeException: Handshake error in client (OS Error:
CERTIFICATE_VERIFY_FAILED: certificate is not yet valid(handshake.cc:359))
```

### Expected Outcome

--

### Environment

Parse Flutter SDK
- SDK version: `3.1.0`
- Operating system version: `Android 7 and lower`

Server
- Parse Server version: `^3.3.1`

**Comment by mtrezza** [comment]
You could compare the supported TLS versions of your sever vs. client device. These are OS specific, so an older Android phone may not support a TLS version that is required by the server. Anything below TLS 1.2 is usually not recommended anymore today.

**Comment by qqmikey** [comment]
You get a **certificate not yet valid** error if the certificate issue time is later than the local time on your phone
