### ISSUE TITLE
ParseACL.setRoleReadAccess() function listed in doc but missing in SDK

### ISSUE THREAD

**Issue by Viorae** [parse-community/Parse-SDK-Flutter#702]

**Comment by RodrigoSMarques** [comment]
What documentation? 

Is this function not available in the Flutter SDK.

**Comment by Viorae** [comment]
I'm confused now. I remember I read the version of API reference with this function but the version linked in pub.dev doesn't have it. So is there any way of using Flutter SDK to add ACL for roles?

**Comment by RodrigoSMarques** [comment]
In the API it exists, but it was not implemented in the Flutter package.

Check this issue here #247

**Comment by Viorae** [comment]
Thanks! The solution listed at bottom is a better way of handling this I think.
