### ISSUE TITLE
Single Sign On not working properly

### ISSUE THREAD

**Issue by CodeCakePie** [parse-community/Parse-SDK-Flutter#703]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
I have created a Flutter Cross Platform App (android/ios) and I want to login the user via Google.

The problem starts after hot reloading the app. ParseUser.currentUser() always returns null, even if I was logged in.

### Steps to reproduce
I have created a AuthenticationModel with the Provider Package which will take care of the authentication state of the application.

```dart
import 'package:flutter/foundation.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:parse_server_sdk_flutter/parse_server_sdk.dart';

enum AuthenticationState { pending, authenticated, unauthenticated }

class AuthenticationModel extends ChangeNotifier {
  final GoogleSignIn _googleSignIn = GoogleSignIn(
    scopes: ['email'],
  );

  AuthenticationState state = AuthenticationState.pending;
  ParseUser? user;

  Future<void> initialize() async {
    user = await ParseUser.currentUser() as ParseUser?;

    print(user.toString());

    if (user != null) {
      state = AuthenticationState.authenticated;
    } else {
      state = AuthenticationState.unauthenticated;
    }

    notifyListeners();
  }

  Future<void> signInGoogle() async {
    state = AuthenticationState.pending;
    notifyListeners();
    GoogleSignInAccount? account = await _googleSignIn.signIn();
    if (account == null) {
      throw Exception('Account is not set');
    }
    GoogleSignInAuthentication authentication = await account.authentication;

    ParseResponse response = await ParseUser.loginWith(
        'google',
        google(authentication.accessToken!, _googleSignIn.currentUser!.id,
            authentication.idToken!),
        username: account.displayName,
        email: account.email);

    if (response.success) {
      state = AuthenticationState.authenticated;
    } else {
      state = AuthenticationState.unauthenticated;
    }

    notifyListeners();
  }

  Future<void> logout() async {
    ParseUser? user = await ParseUser.currentUser();
    user?.logout();
  }
}

```

The main method looks like this:

```dart
import 'dart:io';

import 'package:festl/models/authentication.dart';
import 'package:festl/screens/authenticate.dart';
import 'package:festl/screens/home.dart';
import 'package:flutter/material.dart';
import 'package:parse_server_sdk/parse_server_sdk.dart';
import 'package:provider/provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  const keyApplicationId = 'yourappid';
  String keyParseServerUrl = Platform.isIOS
      ? 'http://localhost:1337/parse'
      : 'http://10.0.2.2:1337/parse';

  await Parse().initialize(keyApplicationId, keyParseServerUrl, debug: true);

  AuthenticationModel _authenticationModel = AuthenticationModel();
  await _authenticationModel.initialize();

  runApp(ChangeNotifierProvider(
    create: (context) => _authenticationModel,
    child: const MyApp(),
  ));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Startup Name Generator',
      theme: ThemeData(
        brightness: Brightness.dark,
        androidOverscrollIndicator: AndroidOverscrollIndicator.stretch,
        fontFamily: 'Montserrat',
        textTheme: const TextTheme(
          headline1: TextStyle(
              fontSize: 64, fontWeight: FontWeight.w800, color: Colors.white),
        ),
      ),
      home: Consumer<AuthenticationModel>(
        builder: (context, authentication, child) {
          return authentication.state == AuthenticationState.authenticated
              ? const Home()
              : const Authenticate();
        },
      ),
    );
  }
}
```

### Actual Outcome
ParseUser.currentUser() returns null, even though the user logged in via Google

### Expected Outcome
ParseUser.currentUser() should not be null if a hot reload is performed in an logged in state.

### Environment

Parse Flutter SDK
- SDK version: `3.1.0`
- Operating system version: `macOS Monterey Beta 2`

Server
- Parse Server version: `4.0`

### Logs

**Comment by CodeCakePie** [comment]
One more thing:

Flutter Version: `2.10.1`

**Comment by CodeCakePie** [comment]
Another thing I found:

`Parse().hasParseBeenInitialized()` always returns false, even if i check it right after `await Parse().initialize(...)`

**Comment by RodrigoSMarques** [comment]
Does the problem only happen on Hot Reload?

**Comment by CodeCakePie** [comment]
It happens if i want to access the ParseUser.currentUser on app startup.

If the user is actively logging in, it is working, but i want have a single-sign-on like in this [example](https://www.back4app.com/docs/flutter/parse-sdk/users/flutter-facebook-login)

**Comment by RodrigoSMarques** [comment]
The import in `main` is wrong.

Change:

```dart
   import 'package:parse_server_sdk/parse_server_sdk.dart';
```

to

```dart
import 'package:parse_server_sdk_flutter/parse_server_sdk.dart';
```

Do the test.

**Comment by CodeCakePie** [comment]
Thank you very much, it is working now!

But I still have to complain about the missing documentation about that. I was searching and searching...

It would be nice to have something like this at the top of the readme:

**For Flutter development make sure to `import 'package:parse_server_sdk_flutter/parse_server_sdk.dart';`**

Or even better hide the `parse_server_sdk` from the `parse_server_sdk_flutter` package (but i am very new to dart and i have no idea if this is even possible 😄 )

**Comment by RodrigoSMarques** [comment]
I noted your suggestion to include this in the documentation, but in pub.dev

![Captura de Tela 2022-02-17 às 09 45 29](https://user-images.githubusercontent.com/17687286/154484746-993a99b2-60b4-4e47-804b-85b6816e58e0.png)
