### ISSUE TITLE
type 'Null' is not a subtype of type 'int'

### ISSUE THREAD

**Issue by LabN36** [parse-community/Parse-SDK-Flutter#705]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description

Getting `type 'Null' is not a subtype of type 'int'` error from running `ParseUser.getCurrentUserFromServer`

### Steps to reproduce

```
import 'package:parse_server_sdk/parse_server_sdk.dart';

void main() {
  print('[Main]');
  initParse();
}

void initParse() async {
  try {
    Parse parse = await Parse().initialize(
      'myAppId', 'http://192.168.1.2:1337/parse',
      debug: true,
      autoSendSessionId: true,
      // clientKey: 'clientKey'  <- here i'm not passing clientKey, it's working find when i pass clientKey
    );
    print('[Parse Inilialized]');
  } catch (e) {
    print('[Parse Init Catch] $e');
  }
  try {
    print('[getCurrentUserFromServer]');
    ParseResponse? res =
        await ParseUser.getCurrentUserFromServer('token', debug: true);
    print(res!.statusCode);
    print(res.error);
  } catch (e) {
    print('[getCurrentUserFromServer] Catch');
    print(e);
  }
}

```

### Actual Outcome

it's throwing following error on the catch block 
**type 'Null' is not a subtype of type 'int'**

### Expected Outcome

`I believe instead of throwing an error we should get this as a parseResponse's error field`

This is working fine when i tried with `clientKey` but ideally it should work, I'm not sure what could be the reason of throwing an error.

It also throws an error when we try the wrong `clientKey`, shouldn't it should try to establish a connection with parser server at the initializationStage ? AFAIK parse server doesn't have any such API. but still how should we handle such behaviour in production(well it's kind of foolish knowing that the code will break if we don't pass clientKey or pass wrong key)

I tried debugging the package code and found out that it's throwing an error at `json.Decode()` in `parse_error_response.dart` file.

ultimately this method `getCurrentUserFromServer` calls the API `http://192.168.1.2:1337/parse/users/me` which give  as a `{"error":"unauthorized"}` response

can anyone let me know the reason behind this ?

### Environment

I've tried parse_server_sdk 3.1.0

Parse Flutter SDK
Although it's not dependent of flutter as I've just tried running a simple dart code.
- SDK version: `Flutter (Channel stable, 2.8.1, on macOS 11.0.1 20B50 darwin-x64, locale en-GB)`
- Operating system version: `macos`

Server
- Parse Server version: `^4.10.4`

### Logs

```
[Main]
[Parse Inilialized]
[getCurrentUserFromServer]
╭-- Parse Request
curl -X GET -H 'X-Parse-Session-Token: token' -H 'user-agent: Flutter Parse SDK 3.1.0' -H 'X-Parse-Application-Id: myAppId' http://192.168.1.2:1337/parse/users/me

 http://192.168.1.2:1337/parse/users/me
╰--
[getCurrentUserFromServer] Catch
type 'Null' is not a subtype of type 'int'

```

**Comment by RodrigoSMarques** [comment]
You cannot call `ParseUser.getCurrentUserFromServer` directly.

You need to retrieve `currentUser` first, to get the `sessionToken`.

```dart
      ParseUser currentUser = await ParseUser.currentUser() as ParseUser;
      if (currentUser != null) {
        print('currentUser: $currentUser');

        final ParseResponse parseResponse =
        await ParseUser.getCurrentUserFromServer(
            currentUser.sessionToken);

        if (parseResponse.success) {
          print('currentUserFromServer : $currentUser');
          currentUser = parseResponse.result as ParseUser;
          return ApiResponse.success(result: User.fromParse(currentUser));
        } else {
          await currentUser.logout();
        }
      }
```
