### ISSUE TITLE
ParseUser login & signUp errors fail on prase server >= 4.2.0

### ISSUE THREAD

**Issue by rwblackburn** [parse-community/Parse-SDK-Flutter#710]
### Issue Description

With the latest version of Dart/Flutter the ParseUser no longer provides proper messages when `login` fails or `signUp` fails. 

```
Exception: FormatException: Unexpected character (at character 1)
<!DOCTYPE html>
```

### Steps to reproduce
Create a script that calls:
```
      final user = ParseUser.createUser(username, password, email);
      final ParseResponse response = await user.signUp();
      if (response.success) {
        _handleSaveProfile(response.result);
      } else {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text(response.error!.message),
          backgroundColor: Theme.of(context).colorScheme.error,
        ));
      }
```
Then try to call this using a username/email already in the DB.

### Actual Outcome
The `response.error!.message` is:
```
Exception: FormatException: Unexpected character (at character 1)
<!DOCTYPE html>
```

### Expected Outcome
The `response.error!.message` used to be a message explain the registration failed due to email already being registered.

### Environment

 - Flutter: 2.10.3
 - Dart: 2.16.1 • DevTools 2.9.2
 - Parse Flutter SDK: 3.1.0
 - Parse Server version:  4.5.0

**Comment by rwblackburn** [comment]
Tried it w/Parse Server v5.0.0 too, same thing

**Comment by rwblackburn** [comment]
If I downgrade parse platform server to v4.1.0 it works again. Between v4.1.0 and 4.2.0 it looks like Parse Platform switched from a JSON response to a HTML response

**Comment by mtrezza** [comment]
@rwblackburn could you pin down the commit that made that change in Parse Server?

**Comment by rwblackburn** [comment]
@mtrezza  - I've looked through the release diff and don't see what would have caused this. Perhaps I am just missing it. 

Might be worth double-checking if we are the only ones that see this? On parse v4.1.0 the responses for login failures are in JSON and in v4.2.0+, they are in HTML. Can someone outside my team confirm they see this? If it's only us we can look deeper at our side of things and we can close this issue. If this is indeed a change in Parse Server at some point, I would think we'd need to update the Flutter SDK to accommodate the possibility of both a JSON & HTML responses?

**Comment by RodrigoSMarques** [comment]
I'm using it in two projects with version 4.5 and the answer is returned correctly in JSON, as I've never had any problems.

I'll do a new test and then post the result.

There is an option in the SDK at startup (debug=true) where it will display the curl command and the entire connection log.

Check that there is no other error.

**Comment by mtrezza** [comment]
I'm changing this to type question, as it was not reproducible so far.

**Comment by rwblackburn** [comment]
That is very helpful @RodrigoSMarques  . Thank you. We will dig further and see if we can establish why we are getting HTML responses instead of JSON ones. I'll add our findings here.

**Comment by rwblackburn** [comment]
Found the issue. 

This setting was left on in the Parse Server config:
```
enableExpressErrorHandler: true,
```

Turning this off fixes the issue. This will close this ticket as resolved. I appreciate the help on this. Thank you.
