### ISSUE TITLE
Old version of connectivity_plus package

### ISSUE THREAD

**Issue by endmr11** [parse-community/Parse-SDK-Flutter#717]
Can you update the connectivity_plus package you used in your package?

**Comment by RodrigoSMarques** [comment]
The package is in the process of being updated and will be released in the next few days.

Please test and get back if it's ok.

In `pubspec.yaml`, make the changes below.

```dart
  #parse_server_sdk_flutter: ^3.1.0
  parse_server_sdk_flutter:
    git:
      url: https://github.com/RodrigoSMarques/Parse-SDK-Flutter.git
      ref: development
      path: packages/flutter

**Comment by gadgetreviews** [comment]
Is it safe to use a dependency_override like this one?
```
dependency_overrides:
  connectivity_plus: ^2.3.0
```

**Comment by mbfakourii** [comment]
The problem seems to be solved

**Comment by mtrezza** [comment]
Solved via https://github.com/parse-community/Parse-SDK-Flutter/pull/738
