### ISSUE TITLE
Security review of 3rd party services

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Flutter#718]
We are doing our annual security review of 3rd party services. The goal is to remove permissions of services that are no longer used in this repository's CI workflow.

Services that need to be reviewed:

- [x] Travis CI for Open Source -> not used
- [x] Coveralls -> not used
- [x] StyleCI -> not used
- [x] Travis CI -> not used
- [x] AppVeyor -> not used
- [x] AppVeyor CI -> not used
- [x] CircleCI -> not used
- [x] Code Climate -> not used
- [x] Packagist -> not used

**Comment by fischerscode** [comment]
Using GitHub Actions, instead of travis, for testing might be an idea.

Is this repo even using any of those services (apart from travis)?

**Comment by mtrezza** [comment]
Eventually we want to switch to GH Actions in every repository. It's just the PR that's missing.

**Comment by fischerscode** [comment]
@mtrezza That might be the issue...
https://github.com/fischerscode/action-test-2/pull/1

**Comment by mtrezza** [comment]
As far as I see, none of the services is used anymore in this repo. Would you agree, @fischerscode?

**Comment by fischerscode** [comment]
I do agree.

We could consider creating coverage reports and uploading them to Coveralls.
dart test/flutter test support creating them.

**Comment by mtrezza** [comment]
Good idea; instead of Coveralls, could we use [Codecov](https://about.codecov.io/)?

**Comment by fischerscode** [comment]
Sure, the visualization should not be the hard part. More the fact, that we will get a output for each package.
