### ISSUE TITLE
Fixing the failing tests

### ISSUE THREAD

**Issue by fischerscode** [parse-community/Parse-SDK-Flutter#725]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

~~- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). ~~

### Issue Description
Currently the tests are failing.

We have to:
- [x] #722 
- [x] #728 
- [x] #729

### Steps to reproduce
n/a

### Actual Outcome
n/a

### Expected Outcome
n/a

### Environment
GitHub Ci

### Logs
n/a

**Comment by mtrezza** [comment]
Could you please open an issue per PR? We have this requirement because sometimes there are discussions around individual changes, also maybe at a later point in time, and we want to keep them separated by issue.

**Comment by fischerscode** [comment]
I'll link the issues in the list.

**Comment by mtrezza** [comment]
Got it, you opened this a sort of roadmap for issues to fix, not to reference PRs.

**Comment by fischerscode** [comment]
Well, you did not...
At first, I thought about linking the PRs to this issue and decided to use this one as a roadmap after I read your comment.

**Comment by mtrezza** [comment]
You are on a roll! Amazing how many things we got done in the last 24h.

**Comment by mtrezza** [comment]
Closing as all tests pass.
