### ISSUE TITLE
Add code coverage to CI

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Flutter#732]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Current Limitation
Currently there is no code coverage report in the CI.

### Feature / Enhancement Description
Add code coverage report to CI. Preferably use Codecov.

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by fischerscode** [comment]
Coverage should be created even if tests fail.

**Comment by mtrezza** [comment]
Closing via #737
