### ISSUE TITLE
Fixing the analyzer infos

### ISSUE THREAD

**Issue by fischerscode** [parse-community/Parse-SDK-Flutter#733]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
Currently the dart and the flutter package have many analyzer infos.
It's a good practice to fix them.

Some require breaking changes. Those should wait for the next major release.

### Steps to reproduce
`flutter analyze package/flutter`
`dart analyze package/dart`

### Actual Outcome
n/a

### Expected Outcome
n/a

### Environment
n/a

### Logs
n/a

**Comment by mbfakourii** [comment]
It seems to be resolved in [#757](https://github.com/parse-community/Parse-SDK-Flutter/pull/757)

**Comment by mtrezza** [comment]
Reopened for #810
