### ISSUE TITLE
when call user.verificationEmailRequest() , result is failure

### ISSUE THREAD

**Issue by fee-studio** [parse-community/Parse-SDK-Flutter#752]
when i call user.verificationEmailRequest()

result is failure and message is `An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality.`

**Comment by mtrezza** [comment]
I'm closing this as it does not use the issue template provided when creating an issue and therefore lacks essential information required to investigate the issue. Please edit your initial post using the issue template and we can re-open this issue.
