### ISSUE TITLE
Polygon property returned as Null for the Flutter SDK

### ISSUE THREAD

**Issue by alexvenom** [parse-community/Parse-SDK-Flutter#779]
### Issue Description
For any given Class containing a Polygon type property correctly set with GeoPoints, when queried through the Flutter SDK the property will be retrieved as null. Other SDKs will retrieve the property correctly displaying all GeoPoints that form the Polygon.

### Steps to reproduce
- Create a Class with a Polygon property
- Add valid GeoPoints to the Polygon property (at least 3 GeoPoints)
- Query the created Class using the Flutter SDK
- Observe the Polygon property is returned as null

### Actual Outcome
Actual print of the ParseObject containing a valid Polygon property named "square", returned as Null by the Flutter SDK:
```
{"className":"Georef","objectId":"HjR3l1cHV4","createdAt":"2022-07-25T17:04:15.276Z","updatedAt":"2022-07-25T17:29:33.128Z","square":null,"name":"Test"}
```

Here the output of the same object using the JS SDK:
```
{"square":{"__type":"Polygon","coordinates":[[0,0],[0,1],[1,1],[1,0],[0,0]]},"createdAt":"2022-07-25T17:04:15.276Z","updatedAt":"2022-07-25T17:29:33.128Z","name":"Test","objectId":"HjR3l1cHV4"}
```

### Expected Outcome
The "square" property on the output above should contain a List<ParseGeoPoint> or similar data representing the Polygon

### Environment
- iOS 14.1
- Parse Server 4.5.0
- XCode 13.3
- Mac OS 12.3.1
- Flutter 3.0.5

Parse Flutter SDK
- SDK version: `3.1.3`
- Operating system version: `Mac OS 12.3.1`
- iOS system version: `14.1`

Server
- Parse Server version: `4.5.0`

**Comment by mtrezza** [comment]
@alexvenom Could you please post a sample code to reproduce the issue? Otherwise we'll have to go ahead and cose this.

**Comment by mtrezza** [comment]
I'll go ahead and close this as it wasn't reproducible. @alexvenom We can reopen this issue if you could post a sample code to reproduce it.
