### ISSUE TITLE
Parse on Dart VM

### ISSUE THREAD

**Issue by rizalkotlin** [parse-community/Parse-SDK-Flutter#78]
Since there is no dependency for specific Flutter feature, why this library use Flutter SDK?
It can be more useful when this parse SDK can be used on dart vm or console app as well

**Comment by phillwiggins** [comment]
The specific dependencies current are shared_preferences. Until we can
think of a better solution to local persistence, it will be Flutter based.

I'm fairly new to Flutter & Dart, so if you have any ideas or solutions,
please let me know as a pure Dart based library would be so much better.

Thanks

**Comment by putraxor** [comment]
@rizalkotlin I have my own implementation for shared_preference and path_provider 
https://github.com/putraxor/flutter_parse_sdk
but I haven't tested it on Flutter Mobile

take a look at [shared_preferences.dart](https://github.com/putraxor/flutter_parse_sdk/blob/master/lib/src/utils/shared_preferences.dart) and [path_provider.dart ](https://github.com/putraxor/flutter_parse_sdk/blob/master/lib/src/utils/path_provider.dart)

**Comment by chrbayer** [comment]
The storage is not an integral part of the communication to the parse server, I think the best way would be to remove the dependency to any kind of storage and just provide some "BaseStorage" class which simply defines the interface and does not store and retrieve anything. For some applications this is good enough. If needed, for Flatter or for a command line application this class can be extended to handle the actual storage.

**Comment by matskosan** [comment]
It would be so nice to have Parse-SDK-Flutter to be based on Parse-SDK-Dart so that we can use the latter on all platforms supported by Dart...

**Comment by maaeps** [comment]
I found this issue today.
I think the ideas of @chrbayer and @hyperrecursive sound like a good solution.
Some days ago, I have tried to remove all flutter dependencies, and we would have to do something like @chrbayer's idea for [quite a amount of used packages](https://github.com/AdvancedProjects/Parse-SDK-Dart/commit/d416d845ec98fe15a43e7044e743eeaab54769c3).

@phillwiggins 
I am considering doing this as soon as I find some time. Would this be merged? Then everyone could just fork this repo and delete everything that is flutter related in order to create a dart package.

**Comment by phillwiggins** [comment]
I'm more than happy to have this a pure Dart library. As long as we find the best solution for storage etc that plays nicely on all platforms, then it would completely make sense. 

I will release 1.0.27 today and make a new branch called release/1.0.28. If you create a PR for that branch, I will merge it and test it fully heavily. 

Sounds like a great idea.

**Comment by fischerscode** [comment]
I am closing this, as [parse_server_sdk](https://pub.dev/packages/parse_server_sdk) can now be used in dart projects.
