### ISSUE TITLE
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'ParseRelation<ParseObject>?' in type cast

### ISSUE THREAD

**Issue by jijkbird** [parse-community/Parse-SDK-Flutter#782]
parse_server_sdk_flutter: ^3.1.3

 return await Get.find<GlobalData>().user!.getRelation("guanzhu").getQuery().find()

this line error

**Comment by mtrezza** [comment]
To report an issue, please use the issue template provided when you create an issue. The template asks for essential information which helps us to investigate the issue.
