### ISSUE TITLE
Change parse local database (sembast) path in IOS to LibraryDirectory rather then ApplicationDocumentsDirectory.

### ISSUE THREAD

**Issue by Nidal-Bakir** [parse-community/Parse-SDK-Flutter#791]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Current Limitation
The database (sembast) file "parse.db" can be viewed by the regular user and can be deleted.
that's not good in some cases where the app will store some images, videos, and documents in the app directory, so the user will open the app directory to browse these files and see the "parse.db" database file!!
Or in some cases where the user suddenly decided to delete the app directory the (sembast) "parse.db" file will be deleted and the user will open the app to be surprised that his login and any saved data in the database were deleted.

### Feature / Enhancement Description
I suggest using LibraryDirectory as a path for the database file in IOS.
Rather than the ApplicationDocumentsDirectory path.

We can do something like this:
``` dart
class CoreStoreDirectory {
  Future<String> getDatabaseDirectory() async {
     if (Platform.isIOS) {
        return (await getLibraryDirectory()).path;
    } else {
        return (await getApplicationDocumentsDirectory()).path;
    }
  }
```

here:
https://github.com/parse-community/Parse-SDK-Flutter/blob/14be107e602f30db8f278aceeba3a8ae9b022e86/packages/flutter/lib/src/storage/core_store_directory_io.dart#L3-L6

### Example Use Case

![Selection_091](https://user-images.githubusercontent.com/29513372/193069731-670836a7-99a0-4d9c-bf9d-313770f2ba9e.png)

**Comment by mtrezza** [comment]
Moving the DB file path makes this is a breaking change. Can we add a simple migration algorithm that looks for the existing file at the old path and move it to the new path if it exists?

**Comment by Nidal-Bakir** [comment]
@mtrezza yes, I am well aware of this! I point it out in my PR description [here](https://github.com/parse-community/Parse-SDK-Flutter/pull/826#issue-1599228874)

### First solution:
This solution will return the old path (ApplicationDocumentsDirectory) if a database file exists in it. otherwise, it will return the new path (LibraryDirectory).

> This is a breaking change for **_ios_** platform because the SDK now will look for the "parse.db" in the `LibraryDirectory` rather than the `ApplicationDocumentsDirectory`.
>
> 
> We can support the old directory path by doing something like:
> ``` dart
>   Future<String> getDatabaseDirectory() async {
>     if (Platform.isIOS) {
>       if(await _isDatabaseFileExistsInOldPath()){
>         return (await path_provider.getApplicationDocumentsDirectory()).path;
>       }
>       return (await path_provider.getLibraryDirectory()).path;
>     } else {
>       return (await path_provider.getApplicationDocumentsDirectory()).path;
>     }
>   }
> 
>   Future<bool> _isDatabaseFileExistsInOldPath() async {
>     final oldIosDatabaseDirPath =
>         (await path_provider.getApplicationDocumentsDirectory()).path;
>     final oldDatabaseFile =
>         path.join('$oldIosDatabaseDirPath/parse', 'parse.db');
> 
>     if (await File(oldDatabaseFile).exists()) {
>       return true;
>     }
>     return false;
>   }
> ```


### copy solution:
```dart 
  Future<String> getDatabaseDirectory() async {
    if (Platform.isIOS) {
      final dbFile = await _getDBFileIfExistsInAppDocDir();

      if (dbFile != null) {
        await _moveDatabaseFileToLibraryDirectory(dbFile);
      }

      return (await path_provider.getLibraryDirectory()).path;
    }

    return (await path_provider.getApplicationDocumentsDirectory()).path;
  }

  Future<File?> _getDBFileIfExistsInAppDocDir() async {
    final appDocDirPath =
        (await path_provider.getApplicationDocumentsDirectory()).path;

    final databaseFilePath = path.join(
      appDocDirPath,
      'parse',
      'parse.db',
    );

    final dbFile = File(databaseFilePath);

    if (await dbFile.exists()) {
      return dbFile;
    }

    return null;
  }

  Future<void> _moveDatabaseFileToLibraryDirectory(
    File databaseFileToMove,
  ) async {
    final libraryDirectoryPath =
        (await path_provider.getLibraryDirectory()).path;

    final libraryDirectoryDatabaseFilePath = path.join(
      libraryDirectoryPath,
      'parse',
      'parse.db',
    );

    await databaseFileToMove.copy(libraryDirectoryDatabaseFilePath);
    await databaseFileToMove.delete();
  }
```

**Comment by Nidal-Bakir** [comment]
Currently, I do not have access to any mac device, so I can not test this!
It will be helpful if anyone can test the code.
thanks.

**Comment by mtrezza** [comment]
I think the "copy" solution makes most sense. It essentially migrates existing clients over time to move their DB file. In the future (some years from now), we can then remove that migration algorithm.

**Comment by Nidal-Bakir** [comment]
@mtrezza I agree with you the "copy" solution is the right thing to do.

> Do you think you could write a test for a function that moves the file? Then the OS wouldn't matter. You would just place a dummy file, call the function and see it being moved to a new location. Maybe you could mock the paths if necessary.

working on it!

**Comment by Nidal-Bakir** [comment]
@mtrezza 
Done!
Can you review the PR?
