### ISSUE TITLE
getRelation with error: Invalid Relation key name

### ISSUE THREAD

**Issue by catalunha** [parse-community/Parse-SDK-Flutter#801]
### New Issue Checklist
- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [ x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [ x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
I tested the following code. All very well.
```dart
    log('addRelation 01');
    final parseObjectBook01 = ParseObject(BookEntity.className);
    parseObjectBook01.objectId = 'aeOTTuGO7r';
    final parseObjectAuthor01 = ParseObject(AuthorEntity.className);
    parseObjectAuthor01.objectId = 'fK4I00NlBy';
    parseObjectBook01.addRelation('typeRelationAuthor', [parseObjectAuthor01]);
    await parseObjectBook01.save();
```
But this code. It generates error. Informed below.
```dart
    log('addRelation 01a');
    final parseObjectBook01 = ParseObject(BookEntity.className);
    parseObjectBook01.objectId = 'aeOTTuGO7r';
    var parseRelationBook = parseObjectBook01.getRelation('typeRelationAuthor');
    final parseObjectAuthor01 = ParseObject(AuthorEntity.className);
    parseObjectAuthor01.objectId = 'fK4I00NlBy';
    parseRelationBook.add(parseObjectAuthor01);
    await parseObjectBook01.save();
```
![image](https://user-images.githubusercontent.com/19995819/204113183-fd8e16b0-13e6-453f-b13c-940b0aa984bf.png)
Exactly on this line: 
`var parseRelationBook = parseObjectBook01.getRelation('typeRelationAuthor');
`
![image](https://user-images.githubusercontent.com/19995819/204113226-404f1c90-842c-4fbc-8960-1b6b8b58f3cb.png)

### Steps to reproduce
Create a pure standard Dart project with VSCode
Create a basic project in back4app and write down the appId and clientKey.
Copy the code above to your Dart project and enter the correct appId and clientKey and then a wrong value.
Run the Dart project with:
$ dart bin/learning_about_b4a_dart.dart 

### Actual Outcome
Error

### Expected Outcome
May the result be the same. In both codes

### Environment
Parse Flutter SDK
- SDK version: parse_server_sdk_flutter: ^3.1.3
- Operating system version: Description:	Pop!_OS 22.04 LTS

Server
- Parse Server version: `4.5.0`

### Logs
Connecting to VM Service at http://127.0.0.1:35555/jjn-YZQ6Y-s=/
[log] Back4app Connected.
[log] addRelation 01a
Unhandled exception:
Invalid Relation key name
#0      new ParseRelation
package:parse_server_sdk/…/objects/parse_relation.dart:7
#1      ParseObject.getRelation
package:parse_server_sdk/…/objects/parse_object.dart:313
#2      BookAddData.addRelations2
package:learning_about_b4a_dart/…/book/book_add_data.dart:108
#3      main
bin/learning_about_b4a_dart.dart:81
<asynchronous suspension>

Exited (255)

**Comment by catalunha** [comment]
Congratulations and thanks @mtrezza ,
I wish I had more knowledge to solve issues and not just create them.
I'm struggling here.

**Comment by mbfakourii** [comment]
You have created an empty parseObject and you are trying to get the value but your key does not exist in the empty ParseObject! I suggest first featch and next try getRelation. like this

```dart
var parseObjectBook01 = ParseObject(BookEntity.className);
parseObjectBook01.objectId = 'aeOTTuGO7r';
parseObjectBook01 = await parseObjectBook01.fetch(); // <--------
var parseRelationBook = parseObjectBook01.getRelation('typeRelationAuthor');
```

**Comment by catalunha** [comment]
It is true @mbfakourii 
Sorry for the inconvenience and thanks for the help.
I thought that only for addition it made association and allowed addition.

**Comment by catalunha** [comment]
Final code follows.
```dart
  static addRelations() async {
    log('addRelation 01');
    //The downside of this approach is that it fetches the data.
    var parseObjectBook01 = ParseObject(BookEntity.className);
    parseObjectBook01.objectId = 'aeOTTuGO7r';
    parseObjectBook01 = await parseObjectBook01.fetch();
    var parseRelationBook = parseObjectBook01.getRelation('typeRelationAuthor');
    print(parseRelationBook.toJson());
    print(parseRelationBook.toString());
    final parseObjectAuthor01 = ParseObject(AuthorEntity.className);
    parseObjectAuthor01.objectId = 'fK4I00NlBy';
    parseRelationBook.add(parseObjectAuthor01);
    await parseObjectBook01.save();

    log('addRelation 02');
    final parseObjectBook02 = ParseObject(BookEntity.className);
    parseObjectBook02.objectId = 'gkotvO6IKI';
    final parseObjectAuthor02 = ParseObject(AuthorEntity.className);
    parseObjectAuthor02.objectId = 'ETwKYOAMh2';
    parseObjectBook02.addRelation(
        'typeRelationAuthor', [parseObjectAuthor01, parseObjectAuthor02]);
    await parseObjectBook02.save();
  }
  ```
