### ISSUE TITLE
type 'Null' is not a subtype of type 'int' when saving an Object with "relation"

### ISSUE THREAD

**Issue by keanallen** [parse-community/Parse-SDK-Flutter#804]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description

When I try to save an object that has a relation, it throws an error saying ```Unhandled Exception: type 'Null' is not a subtype of type 'int'```

### Code:
```dart

    // create current user pointer
    var currentUser = await ParseUser.currentUser();
   

    ParseObject calendarMeetings = ParseObject("CalendarMeetings");
    
    // attendeeIds: List of objectIds

    // loop thru relation and add
    List<ParseObject> relation = [];
    for (var i = 0; i < attendeeIds.length; i++) {
      var obj = ParseObject("_User")..set("objectId", attendeeIds[i]);
      relation.add(obj);
    }

    // Also, add the current user to the relation
    relation.add(currentUser);

    calendarMeetings
      ..set('start', from)
      ..set('end', to)
      ..set('color', tileColor)
      ..set('label', title)
      ..set('description', description)
      ..set('link', link)
      ..set('repeat', repeat)
      ..set('createdBy', currentUser);
    
   // add the relation
    calendarMeetings.addRelation('attendees', relation);


    var response = await calendarMeetings.save();
    return response.success;

```

### Steps to reproduce

Try to do the code above

### Actual Outcome

An error, failed in saving object. This works before, but now it gives me an error

### Expected Outcome

Should successfully save the data!

### Environment

Flutter Version: `Channel stable, 3.3.9`

Parse Flutter SDK
- SDK version: `3.1.3`
- Operating system version: `Windows 11 x64`

Server
- Parse Server version: `5.2.5`

### Logs

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'int'
#0      _ParseResponseBuilder._handleSuccess
package:parse_server_sdk/…/response/parse_response_builder.dart:76
#1      _ParseResponseBuilder.handleResponse
package:parse_server_sdk/…/response/parse_response_builder.dart:29
#2      handleResponse
package:parse_server_sdk/…/response/parse_response_utils.dart:8
#3      batchRequest
package:parse_server_sdk/…/utils/parse_utils.dart:82
<asynchronous suspension>
#4      ParseObject._saveChildren
package:parse_server_sdk/…/objects/parse_object.dart:172
<asynchronous suspension>
#5      ParseObject.save
package:parse_server_sdk/…/objects/parse_object.dart:99
<asynchronous suspension>
#6      CalendarProvider.saveMeeting
package:echat/…/providers/calendar_provider.dart:114
<asynchronous suspension>
```

**Comment by mbfakourii** [comment]
try ```List<dynamic> relation = [];```
and use string for objectId
```var obj = ParseObject("_User")..set("objectId", "dfgdfwxsfc");```

What type of ```attendeeIds``` are they?

**Comment by keanallen** [comment]
Hi, I already tried:

`List<dynamic> relation = [];` 
and still the same.

`AttendeIds` is an array of objectId of the user:

```
["jsfjds8","asdfsf","sdfasf"]
```

**Comment by mbfakourii** [comment]
None of these items are null? Because your code worked for me.
```
 calendarMeetings
      ..set('start', from)
      ..set('end', to)
      ..set('color', tileColor)
      ..set('label', title)
      ..set('description', description)
      ..set('link', link)
      ..set('repeat', repeat)
      ..set('createdBy', currentUser);
```

**Comment by keanallen** [comment]
Ok. Wait. I'll double check again.

**Comment by keanallen** [comment]
> None of these items are null? Because your code worked for me.
> 
> ```
>  calendarMeetings
>       ..set('start', from)
>       ..set('end', to)
>       ..set('color', tileColor)
>       ..set('label', title)
>       ..set('description', description)
>       ..set('link', link)
>       ..set('repeat', repeat)
>       ..set('createdBy', currentUser);
> ```

Hi, I can confirm that these variables are not null.

![image](https://user-images.githubusercontent.com/45480782/206644405-371acbf6-9141-4f34-b055-c95036bb7f80.png)

Here is the relation value:
```json
[
  {
    "className": "_User",
    "objectId": "7rYsDYWY93"
  },
  {
    "className": "_User",
    "objectId": "1RSajjAKo1"
  }
]
```

**Comment by keanallen** [comment]
I think it works now!

I just need to add `toPointer()`!

```dart
    
    List relation = [];

    for (var i = 0; i < attendeeIds.length; i++) {
      var obj = ParseObject("_User")..set("objectId", attendeeIds[i]);
      relation.add(obj.toPointer());
    }
```
