### ISSUE TITLE
Cancel upload and add Progress Callback befor internally save

### ISSUE THREAD

**Issue by mbfakourii** [parse-community/Parse-SDK-Flutter#807]
### New Feature / Enhancement Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Current Limitation
It is not possible to stop the upload.
It is also not possible to give Progress Callback file to Parse before internally saving

### Feature / Enhancement Description
I suggest that this possibility exists because it is very important, especially to cancel the upload

### Example Use Case
```dart
ParseFile file=...;

file.cancel("reason");
```
and 
```dart
ParseFile file=...;

file.progressCallback((count, total) {
  print("total=$total | count=$count");
});

file.save();
```

### Alternatives / Workarounds
Currently, these tasks are not possible

**Comment by mtrezza** [comment]
Did you model this after other Parse SDKs, in case they support this feature yet? Because we want the method names and approaches be similar as much as possible.

**Comment by mbfakourii** [comment]
> Did you model this after other Parse SDKs, in case they support this feature yet? Because we want the method names, behavior and approaches to be similar as much as possible.

for cacel upload and download, yes in [Parse SDK Android](https://github.com/parse-community/Parse-SDK-Android/blob/50a4e30da2f4ed07a88d36476e85271cd00854f5/parse/src/main/java/com/parse/ParseFile.java#L630) 

and [Parse SDK IOS](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/3c6906f9cf90805951c6d8ad9eba4c80a6a7ecd8/Parse/Parse/PFFileObject.h#L373)

Regarding the second case, if we don't request a callback first, we can't manage the upload progress.
Similar item is available in [Parse SDK Android](https://github.com/parse-community/Parse-SDK-Android/blob/50a4e30da2f4ed07a88d36476e85271cd00854f5/parse/src/main/java/com/parse/ParseFile.java#L303).

**Comment by mtrezza** [comment]
Is it even possible that a file upload and download are in progress at the same time? If not, maybe instead of separate `file.cancelDownload("reason");` and `file.cancelUpload("reason");` we can just have a generic `file.cancel("reason");`? That would then be the same syntax as in the other Parse SDKs.

**Comment by mbfakourii** [comment]
> Is it even possible that a file upload and download are in progress at the same time? Either a file needs to uploaded or downloaded. Maybe instead of separate `file.cancelDownload("reason");` and `file.cancelUpload("reason");` we can just have a generic `file.cancel("reason");`? That would then be the same syntax as in the other Parse SDKs.
> 
> The same for the `progress` callback. I see in the 2 SDKs that you mentioned, the callback is actually a handler that is passed when calling `save`:
> 
> Android SDK:
> 
> ```java
> ParseFile file = new ParseFile("resume.txt", data);
> 
> file.saveInBackground(new SaveCallback() {
>   public void done(ParseException e) {
>     // Handle success or failure here ...
>   }
> }, new ProgressCallback() {
>   public void done(Integer percentDone) {
>     // Update your progress spinner here. percentDone will be between 0 and 100.
>   }
> });
> ```
> 
> Apple SDK:
> 
> ```objc
> PFFileObject *file = [PFFileObject fileObjectWithName:@"resume.txt" data:data];
> [file saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
>   // Handle success or failure here ...
> } progressBlock:^(int percentDone) {
>   // Update your progress spinner here. percentDone will be between 0 and 100.
> }];
> ```
> 
> This way there is no ambiguity as the handler is part of the `save` method. Would a similar pattern make sense for Flutter?

In the case of cancel, a function can be written
But in the case of addUploadProgressCallback, no, what is in the Android SDK, the upload process starts with the saveInBackground call, but with the addUploadProgressCallback function, you can start the upload with ProgressCallback at any time. This topic is used a lot in object storage, for example

```dart
ParseObject object=ParseObject("book");

ParseFile file=...;
file.addUploadProgressCallback((count, total) {
  print("total=$total | count=$count");
});

object.img = file;

object.save();
```

**Comment by mtrezza** [comment]
Got it, then maybe we can simplify the name at least. Would it make sense to add it as a property, so it be set like this?

```
progressCallback(count, total) {
  print("total=$total | count=$count");
}

file.progressCallback = progressCallback;
```

**Comment by mbfakourii** [comment]
> 

changed
```dart
ParseFile file=...;

file.progressCallback((count, total) {
  print("total=$total | count=$count");
});

file.save();
```
and now it works for both download and upload

**Comment by mtrezza** [comment]
Amazing!
