### ISSUE TITLE
feature "Add include option to getObject in  3.1.7"  with error for me

### ISSUE THREAD

**Issue by catalunha** [parse-community/Parse-SDK-Flutter#813]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
Congratulations and thank you @mbfakourii  for your contributions.

I have a test project that can be accessed here:
https://github.com/catalunha/learning_about_b4a_dart
Updating to parse_server_sdk: ^3.1.8 exclusively to test the Add include option to getObject feature I got an error.
See the output with the standard getObject, without include. Everything works normally.
```
await ParseObject(AuthorEntity.className).getObject(objectId);

╭-- Parse Request
curl -X GET -H 'user-agent: Flutter Parse SDK 3.1.8' -H 'X-Parse-Application-Id: 123' -H 'X-Parse-Client-Key: 123' https://parseapi.back4app.com/classes/Author/wumssuy5eQ

 https://parseapi.back4app.com/classes/Author/wumssuy5eQ
╰--
╭-- Parse Response
Class: Author
Function: ParseApiRQ.get
Status Code: 200
Payload: {"className":"Author","objectId":"wumssuy5eQ","createdAt":"2022-12-24T09:54:13.421Z","updatedAt":"2022-12-24T09:54:13.421Z","typeString":"Author01","typeBoolean":true,"typeNumber":1,"typeDateTime":{"__type":"Date","iso":"2022-12-24T09:54:00.000Z"},"typeArray":["a","1"],"typePointerGenre":{"__type":"Pointer","className":"Genre","objectId":"KinHJTTxv5"}}
╰-- 
```
See output with getObject and include. Note the error it returned to me.
```
await ParseObject(AuthorEntity.className).getObject(objectId, include: ['typePointerGenre']);

╭-- Parse Request
curl -X GET -H 'user-agent: Flutter Parse SDK 3.1.8' -H 'X-Parse-Application-Id: 123' -H 'X-Parse-Client-Key: 123' https://parseapi.back4app.com/classes/Author/wumssuy5eQ%3Finclude=typePointerGenre

 https://parseapi.back4app.com/classes/Author/wumssuy5eQ?include=typePointerGenre
╰--
╭-- Parse Response
Class: Author
Function: ParseApiRQ.get
Status Code: 101
Type: ObjectNotFound
Error: Object not found.
╰-- 
```
I found it strange because everything should work correctly with the feature, and I decided to report it here.

Am I doing something wrong?

### Environment
Dart version:
- Dart SDK version: 2.18.4 (stable) (Tue Nov 1 15:15:07 2022 +0000) on "linux_x64"

Dart project pubspec.yaml:
-  parse_server_sdk: ^3.1.8

Parse Version in back4app
- 4.5.0

Database Version  in back4app
- mongodb 3.6

Operating system version: 
- Linux PopOS

**Comment by mbfakourii** [comment]
@catalunha Thanks for checking
