### ISSUE TITLE
feature "progress callback for ParseFile" not work for me

### ISSUE THREAD

**Issue by catalunha** [parse-community/Parse-SDK-Flutter#815]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
Congratulations and thank you @mbfakourii for your contributions.

I have a test project that can be accessed here:
https://github.com/catalunha/learning_about_b4a_dart

Updating to parse_server_sdk: ^3.1.9 exclusively to test the:
- Add upload / download cancel and progress callback for ParseFile ([#807](https://github.com/parse-community/Parse-SDK-Flutter/issues/807))

Using the default save(). Everything works normally. Image uploaded to the back4app database.
```
    ParseFile? parseFile = ParseFile(File("./anyImageFile.png"));
    final ParseResponse parseResponse = await parseFile.save();
```
Using upload(). Everything works normally. Image uploaded to the back4app database.

**But, not see progressCallback.**
```
    ParseFile? parseFile = ParseFile(File("./anyImageFile.png"));
    final ParseResponse parseResponse = await parseFile.upload(progressCallback: (int count, int total) => print("$count of $total"));
```
I found it strange because everything should work correctly with the feature, and I decided to report it here.

Am I doing something wrong?

### Environment
Dart version:  Dart SDK version: 2.18.4 (stable) (Tue Nov 1 15:15:07 2022 +0000) on "linux_x64"
Dart project pubspec.yaml: parse_server_sdk: ^3.1.8
Parse Version in back4app: 4.5.0
Database Version  in back4app: mongodb 3.6
Operating system version:  Linux PopOS

**Comment by RodrigoSMarques** [comment]
You have to use the ParseDioClient.
Configuration is done at Parse startup: 

[https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/flutter#network-client](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/flutter#network-client)

**Comment by catalunha** [comment]
Thanks. I suspected.
I suggest including this in the documentation.
I'll do more thorough testing with DIO at another time.
Thanks.

**Comment by mbfakourii** [comment]
Thank you @RodrigoSMarques
@catalunha I tested your code and it works with dio.

**Comment by catalunha** [comment]
Thanks. I also tested with dio. all very well
