### ISSUE TITLE
why parse_server_sdk updated and parse_server_sdk_flutter not updated

### ISSUE THREAD

**Issue by catalunha** [parse-community/Parse-SDK-Flutter#816]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
I'm making an effort to study parse_server_sdk in search of a clearer understanding to contribute to an issue.
But for now I'm just going to raise one more issue. My contribution is for the next moment. Sorry.

Why was parse_server_sdk 3.1.3 updated to 3.1.9 and this was not updated in parse_server_sdk_flutter: 3.1.3 ?

Because they are the same code base for parse.

**Comment by RodrigoSMarques** [comment]
`parse_server_sdk` is the basis of the SDK.

`parse_server_sdk_flutter` internally uses [`parse_server_sdk`](https://github.com/parse-community/Parse-SDK-Flutter/blob/cd6b544310c477f6994dff28233c23cd423e49f0/packages/flutter/pubspec.yaml#L13).

Improvements can be made to parse_server_sdk, without having to update parse_server_sdk_flutter, as it uses semantic versioning.

`parse_server_sdk` is pure dart, without references to platform (mobile, web, desktop).
`parse_server_sdk_flutter, uses plugins to be used on platforms.

**Comment by RodrigoSMarques** [comment]
@mtrezza 

Since this issue is open, I'll make a comment.

I noticed that some improvements were made available in the SDK and classified in the changelog as a bugfix e not a feature.

There was a version increment in the patch and not in minor.

If there is a version increase in the minor of `parse_server_sdk`, remember that you have to update the version in `parse_server_sdk_flutter`.

**Comment by catalunha** [comment]
Thanks @RodrigoSMarques 
I verified that all implementations of parse_server_sdk 3.1.3 to 3.1.9 also reflected in parse_server_sdk_flutter 3.1.3 without any version changes.

I understand your explanation and agree with it.

However, the constant update of the parse_server_sdk (Published 19 hours ago) encourages the community to use the Parse Serve solution on Dart/Flutter. And the lack of an update on parse_server_sdk_flutter (Published 5 months ago) somewhat bothers some users.

It would be interesting to put a reminder about this and link to parse_server_sdk at the beginning of the parse_server_sdk_flutter documentation. I believe it would help with the overall marketing of the products.

**Comment by catalunha** [comment]
Important alert @RodrigoSMarques 
Considering what is available at https://semver.org/
Here are some observations under your careful analysis.
Accessing: https://pub.dev/packages/parse_server_sdk/changelog
current changelog | recommended changelog | Comments
---|---|---
[3.1.5](https://pub.dev/packages/parse_server_sdk/changelog#315httpsgithubcomparse-communityparse-sdk-fluttercomparedart-314dart-315-2022-12-16) | 3.2.0 | A feature. Add upload / download cancel and progress callback for ParseFile
[3.1.6](https://pub.dev/packages/parse_server_sdk/changelog#316httpsgithubcomparse-communityparse-sdk-fluttercomparedart-315dart-316-2022-12-21) | 3.3.0 | A feature. Add and, nor operators in QueryBuilder
[3.1.7](https://pub.dev/packages/parse_server_sdk/changelog#317httpsgithubcomparse-communityparse-sdk-fluttercomparedart-316dart-317-2022-12-22) | 3.4.0 | A feature. Add include option to getObject and fetch
[3.1.8](https://pub.dev/packages/parse_server_sdk/changelog#318httpsgithubcomparse-communityparse-sdk-fluttercomparedart-317dart-318-2022-12-23) | 3.4.1 | It was a fix. The ParseObject.toJson() already existed but it is not working.
[3.1.9](https://pub.dev/packages/parse_server_sdk/changelog#319httpsgithubcomparse-communityparse-sdk-fluttercomparedart-318dart-319-2022-12-25) | 3.4.2 | It was a fix. The include option to getObject feature has been released but is not working.

Your last sentence: "If there is a version increase in the minor of parse_server_sdk, remember that you have to update the version in parse_server_sdk_flutter."

Refers to a minor update of parse_server_sdk will also reflect a minor update to parse_server_sdk_flutter. This is it ?

Or would they be completely independent? Remembering what I said about the reminder to link between one and the other.

**Comment by mbfakourii** [comment]
I increased the Flutter version
@RodrigoSMarques 
But isn't it better to use [```any```](https://dart.dev/tools/pub/dependencies#traditional-syntax) for the [Dart version](https://github.com/parse-community/Parse-SDK-Flutter/blob/cd6b544310c477f6994dff28233c23cd423e49f0/packages/flutter/pubspec.yaml#L13) in Flutter?

**Comment by mtrezza** [comment]
Thanks for the discussion.

> However, the constant update of the parse_server_sdk (Published 19 hours ago) encourages the community to use the Parse Serve solution on Dart/Flutter.

Could you explain?

> And the lack of an update on parse_server_sdk_flutter (Published 5 months ago) somewhat bothers some users.

Why?

> I noticed that some improvements were made available in the SDK and classified in the changelog as a bugfix e not a feature.

True, I didn't always consider to check whether the version number increment is according to the commit type. That's a manual step we need to do only for the Parse Flutter SDK, all our other SDKs already use auto release. Once we have auto-release here, this issue won't occur anymore as version increment and change log entry will be automated.

**Comment by catalunha** [comment]
@mtrezza 
Not that you need to be updating all the time.

But once a colleague commented that packages without updates for more than 3 or 6 months is not a good thing. But it is not necessarily a rule.

I can learn from you new concepts about this. You can correct me if necessary.

**Comment by catalunha** [comment]
Thanks @mtrezza 
I just commented in an attempt to help or raise other important points to keep the product in line.
Let's walk...
we can close

**Comment by mtrezza** [comment]
> But once a colleague commented that packages without updates for more than 3 or 6 months is not a good thing.

That's a weak and possibly misleading indicator. There are packages in the ecosystem that have matured over years and are so stable that they don't require many updates. A better indicator for package maintenance is how long there are reported issues without a fix and how many issues there are.

**Comment by catalunha** [comment]
I fully agree. It's a glass half full or half empty.

**Comment by RodrigoSMarques** [comment]
> Important alert @RodrigoSMarques Considering what is available at https://semver.org/ Here are some observations under your careful analysis. Accessing: https://pub.dev/packages/parse_server_sdk/changelog
> 
> current changelog	recommended changelog	Comments
> [3.1.5](https://pub.dev/packages/parse_server_sdk/changelog#315httpsgithubcomparse-communityparse-sdk-fluttercomparedart-314dart-315-2022-12-16)	3.2.0	A feature. Add upload / download cancel and progress callback for ParseFile
> [3.1.6](https://pub.dev/packages/parse_server_sdk/changelog#316httpsgithubcomparse-communityparse-sdk-fluttercomparedart-315dart-316-2022-12-21)	3.3.0	A feature. Add and, nor operators in QueryBuilder
> [3.1.7](https://pub.dev/packages/parse_server_sdk/changelog#317httpsgithubcomparse-communityparse-sdk-fluttercomparedart-316dart-317-2022-12-22)	3.4.0	A feature. Add include option to getObject and fetch
> [3.1.8](https://pub.dev/packages/parse_server_sdk/changelog#318httpsgithubcomparse-communityparse-sdk-fluttercomparedart-317dart-318-2022-12-23)	3.4.1	It was a fix. The ParseObject.toJson() already existed but it is not working.
> [3.1.9](https://pub.dev/packages/parse_server_sdk/changelog#319httpsgithubcomparse-communityparse-sdk-fluttercomparedart-318dart-319-2022-12-25)	3.4.2	It was a fix. The include option to getObject feature has been released but is not working.
> Your last sentence: "If there is a version increase in the minor of parse_server_sdk, remember that you have to update the version in parse_server_sdk_flutter."
> 
> Refers to a minor update of parse_server_sdk will also reflect a minor update to parse_server_sdk_flutter. This is it ?
> 
> Or would they be completely independent? Remembering what I said about the reminder to link between one and the other.

Yes. If there is a change in the minor of the parse_server_sdk, the parse_server_sdk_flutter must be updated to use the new minor.

This way, any new minor from parse_server_sdk will also generate a new minor from parse_server_sdk_fluter.

If this is not done, parse_server_sdk enhancements will not be available in parse_server_sdk_flutter

**Comment by RodrigoSMarques** [comment]
> I bumped the Flutter version
> @RodrigoSMarques
> But isn't it better to use [`any`](https://dart.dev/tools/pub/dependencies#traditional-syntax) for the [Dart version](https://github.com/parse-community/Parse-SDK-Flutter/blob/cd6b544310c477f6994dff28233c23cd423e49f0/packages/flutter/pubspec.yaml#L13) in Flutter?

Using `any` is not [recommended](https://dart.dev/tools/pub/dependencies#traditional-syntax).

An ideal solution would look like this.

```dart
parse_server_sdk: '>=3.1.0 <4.0.0'
```
That way parse_server_sdk_flutter will always use the latest version parse_server_sdk available.

**Comment by mtrezza** [comment]
We are currently using the [caret](https://dart.dev/tools/pub/dependencies#caret-syntax) to specify the version.

> parse_server_sdk: ^3.1.2

is the same as:

> parse_server_sdk: '>=3.1.2 <4.0.0'

**Comment by RodrigoSMarques** [comment]
> We are currently using the [caret](https://dart.dev/tools/pub/dependencies#caret-syntax) to specify the version.
> 
> > parse_server_sdk: ^3.1.2
> 
> is the same as:
> 
> > parse_server_sdk: '>=3.1.2 <4.0.0'

Truth. I made a mess.

**Comment by mtrezza** [comment]
No worries, all these different wildcard syntaxes can be hard to track sometimes.
