### ISSUE TITLE
`ParseUser.save` fails when user is logged in

### ISSUE THREAD

**Issue by gorillatapstudio** [parse-community/Parse-SDK-Flutter#819]
### New Issue Checklist

- [X ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [X ] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [ X] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [ X] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description

When using the 3.1.12, as long as the user is signed in, user.save() results in save failed error. null is not an int.
When switched back to 3.1.11, the error is gone.
I have switched back and force twice to validate the issue.
### Steps to reproduce

upgrade the sdk to 3.1.12, user log in, use debug mode
### Environment

Parse Flutter SDK
- SDK version: 3.7.0
- Operating system version: `FILL_THIS_OUT`

Server
- Parse Server version: `FILL_THIS_OUT`

**Comment by mbfakourii** [comment]
I checked, there is no problem. This error occurs when you timeout. Please check if there is access to the server.

my parse response

```dart
╭-- Parse Request
curl -X POST -H 'X-Parse-Revocable-Session: 1' -H 'X-Parse-Installation-Id: ---' -H 'user-agent: Flutter Parse SDK 3.1.12' -H 'X-Parse-Application-Id: ----' -H 'X-Parse-Client-Key: ----' https://parseapi.back4app.com/classes/_User

 https://parseapi.back4app.com/classes/_User
╰--
╭-- Parse Response
Class: _User
Function: ParseApiRQ.signUp
Status Code: 201
Payload: {"className":"_User","objectId":"I49l5SKBPX","createdAt":"2023-02-03T15:15:11.860Z","username":"te424s24453t22","email":"asdas4qq342dmb2@asd.ccc","sessionToken":"r:b68e8ae664e802189f2931c3917bb5c3"}
╰-- 
```

As you can see in my response, I am using the ```Flutter Parse SDK 3.1.12``` version

**Comment by gorillatapstudio** [comment]
Thanks for the quick reply! My user object has several child objects which are probably causing the failure.
I verified this issue using several of my apps with different parse instances. Additionally, I never had this failure until the upgrade to 3.1.12.
I am wondering if the 3.1.12 handles the nullable field of the object differently than before.
If you need more info, I can do more debug when i have a chance.

**Comment by mbfakourii** [comment]
> Thanks for the quick reply! My user object has several child objects which are probably causing the failure. I verified this issue using several of my apps with different parse instances. Additionally, I never had this failure until the upgrade to 3.1.12. I am wondering if the 3.1.12 handles the nullable field of the object differently than before. If you need more info, I can do more debug when i have a chance.

Yes, I would appreciate it if you could send a sample code

**Comment by gorillatapstudio** [comment]
when calling user.save() exception in parse_response_builder.dart / _handleSuccess.
The user object has many children in it as follows. 
<img width="1055" alt="Screenshot 2023-02-03 at 4 11 32 PM" src="https://user-images.githubusercontent.com/5588910/216711740-5072ec38-8eec-49d3-a5eb-625e1d41bb90.png">

The result list has some successful and some as failure
<img width="440" alt="Screenshot 2023-02-03 at 4 12 16 PM" src="https://user-images.githubusercontent.com/5588910/216711743-3eb6bd23-1f47-4a88-a9f1-4bf9ffc1063a.png">

Line 75 catches the exception: final ParseError error = ParseError(
                code: objectResult[keyCode],
                message: objectResult[keyError].toString());

type 'Null' is not a subtype of type 'int'

**Comment by mbfakourii** [comment]
I made several attempts to generate this error but could not simulate the error.
It is possible to send a sample code that has this problem.

**Comment by hgandhi67** [comment]
Same error for me it is happening here  

Unhandled Exception: type 'Null' is not a subtype of type 'int'
![Screenshot at Feb 08 11-59-19](https://user-images.githubusercontent.com/24764076/217451997-1c0e0769-1a4c-4119-b7b3-e6b3e608d6ef.png)

![Screenshot at Feb 08 11-58-57](https://user-images.githubusercontent.com/24764076/217451983-d9edbec4-e551-4de5-b6c4-47b579fca4ca.png)

**Comment by mbfakourii** [comment]
> Same error for me it is happening here
> 
> Unhandled Exception: type 'Null' is not a subtype of type 'int' ![Screenshot at Feb 08 11-59-19](https://user-images.githubusercontent.com/24764076/217451997-1c0e0769-1a4c-4119-b7b3-e6b3e608d6ef.png)
> 
> ![Screenshot at Feb 08 11-58-57](https://user-images.githubusercontent.com/24764076/217451983-d9edbec4-e551-4de5-b6c4-47b579fca4ca.png)

It is possible to send a sample code that has this problem

**Comment by mbfakourii** [comment]
@hgandhi67 @gorillatapstudio
It is possible to test the library in the following way and announce the result
 
```yaml
  parse_server_sdk:
    git:
      url: https://github.com/mbfakourii/Parse-SDK-Flutter
      path: packages/dart
      ref: e33522ce08d72b9f807e760c20dc27a3ebe620ea
```

**Comment by gorillatapstudio** [comment]
I tried

`parse_server_sdk_flutter:
  #3.1.12 has the user.save() error
  parse_server_sdk:
    git:
      url: https://github.com/mbfakourii/Parse-SDK-Flutter
      path: packages/dart
      ref: 889bdd878485a4f7c4228cf8f8247043a118ce29`

and get

`Because parse_server_sdk_flutter <3.0.0 depends on dio ^3.0.10 and parse_server_sdk_flutter >=3.0.0 <3.1.0 depends on parse_server_sdk ^3.0.0, parse_server_sdk_flutter <3.1.0 requires dio ^3.0.10 or parse_server_sdk ^3.0.0.
And because parse_server_sdk_flutter >=3.1.0 <3.1.2 depends on parse_server_sdk ^3.1.0 and parse_server_sdk_flutter >=3.1.2 <3.1.3 depends on parse_server_sdk ^3.1.1, parse_server_sdk_flutter <3.1.3 requires dio ^3.0.10 or parse_server_sdk from hosted.
And because every version of parse_server_sdk from git depends on dio ^4.0.6 and parse_server_sdk_flutter >=3.1.3 depends on parse_server_sdk from hosted, parse_server_sdk from git is incompatible with parse_server_sdk_flutter.
So, because gts depends on both parse_server_sdk_flutter any and parse_server_sdk from git, version solving failed.
pub finished with exit code 1`

**Comment by gorillatapstudio** [comment]
in the 3.1.12 PR, 
it changes _getObjectData()[key] = parseDecode(value);
to        _unsavedChanges[key] = _getObjectData()[key];
seems to be a big change to original purpose of the code. i noticed many of my objects becomes having unsavedChanges but they shouldn't be.

**Comment by mbfakourii** [comment]
> @hgandhi67 @gorillatapstudio It is possible to test the library as follows
> 
> ```yaml
> dependency_overrides:
>   parse_server_sdk:
>     git:
>       url: https://github.com/mbfakourii/Parse-SDK-Flutter
>       path: packages/dart
>       ref: 889bdd878485a4f7c4228cf8f8247043a118ce29
> ```

In this way, I went back to ```3.1.11```

**Comment by erikas-taroza** [comment]
> ```yaml
> dependency_overrides:
>   parse_server_sdk:
>     git:
>       url: https://github.com/mbfakourii/Parse-SDK-Flutter
>       path: packages/dart
>       ref: 889bdd878485a4f7c4228cf8f8247043a118ce29
> ```

I ran into this issue today and this override fixed it for me. This issue didn't happen in my release build from a couple weeks ago which is weird (I didn't change anything related to Parse).
