### ISSUE TITLE
Upgrade dependency package_info_plus

### ISSUE THREAD

**Issue by sgehrman** [parse-community/Parse-SDK-Flutter#821]
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [ x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [ x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description

parse_server_sdk_flutter >=3.1.3 depends on `package_info_plus: ^1.4.2`.
The dependency should be upgraded as version `3.0.3` is already available.

**Comment by mtrezza** [comment]
Could you give more details about the issue?

**Comment by sgehrman** [comment]
weird response, I'm just asking for you to update packages.  Is this difficult to understand?

**Comment by mtrezza** [comment]
Thanks, I will rephrase the issue for you, so you can see the difference. I will clean your post from comments like "lame", "stupid", etc. - could you clarify what you mean by that? Is there another issue what you would like to express in addition to the update?

**Comment by tungcyfeer** [comment]
Hi. I have the same issue, because I use `package_info_plus` with version 3.x in my own package. I just checked your lib, it has ^1.4.2 in yaml, so I got version solving failed. So I think you can consider upgrade `package_info_plus` to the latest version when upgrade version of this lib. Thanks!

**Comment by sgehrman** [comment]
still a problem in October.  This is the worst maintained package on Flutter!!
