### ISSUE TITLE
ParseQuery fails when query contains + character

### ISSUE THREAD

**Issue by chadpav** [parse-community/Parse-SDK-Flutter#841]
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
ParseQuery fails when a query contains the `+` character

### Steps to reproduce
1. Add/update a Parse User so that the email contains a plus character (e.g. fake+01@gmail.com)
1. Write a ParseQuery over the User collection and pass in the `+` character (e.g., email == 'fake+01@gmail.com')
`var queryBuilder = QueryBuilder<ParseUser>(ParseUser.forQuery())..whereEqualTo('email', 'fake+01@gmail.com');`

### Actual Outcome
The query returns 0 results when I use the Flutter SDK. I also reproduced this using the Dart SDK.

NOTE: I verified that the native iOS SDK would execute this query and return the expected result. I have a native Android app, and I've never noticed this bug, so I'm pretty sure it works there too. This app has been in production since before Facebook bought Parse!

### Expected Outcome
One result should be returned from the query. The SDKs should be consistent too.

### Environment
Parse Server 5.2 + Mongo DB
Parse Flutter SDK

#### Parse Flutter SDK
- Flutter SDK version: `3.1.3` or Dart SDK version `3.1.15`
- Operating system version: `Android 13.0`

#### Server
- Parse Server version: `5.2`

**Comment by Nidal-Bakir** [comment]
Looks like the SDK is not using the [Escape Codes](https://docs.microfocus.com/OMi/10.62/Content/OMi/ExtGuide/ExtApps/URL_encoding.htm) when encoding the request.

Character | URL Escape Codes | String Literal Escape Code
-- | -- | --
\+  | %2B | $2B

I will investigate more in this.


```dart
// this will work 

  final url = Uri.parse(
                  'https://parseapi.back4app.com/classes/_User?where={"email": "gg%2Br@g.com"}');
              final res = await http.get(url, headers: {
                'X-Parse-Application-Id': '',
                'X-Parse-Session-Token': '',
                'X-Parse-Client-Key': '',
                'X-Parse-Master-Key': ''
              });
 print(res.body);
 print(res.statusCode);

//--------------------------------------------
// this will not work 

  final url = Uri.parse(
                  'https://parseapi.back4app.com/classes/_User?where={"email": "gg+r@g.com"}');
              final res = await http.get(url, headers: {
                'X-Parse-Application-Id': '',
                'X-Parse-Session-Token': ' ',
                'X-Parse-Client-Key': '',
                'X-Parse-Master-Key': ''
              });
 print(res.body);
 print(res.statusCode);
```

**Comment by chadpav** [comment]
Thanks for the quick response and workaround. I'll implement the workaround now and test out an update when it's available.

**Comment by mtrezza** [comment]
@chadpav would you want to open a pull request since you are already working on a workaround?

**Comment by chadpav** [comment]
I could take a shot at it, maybe next week. I'm not too familiar with the SDK code base, but I could probably figure it out.

**Comment by mtrezza** [comment]
Sure, go for it, if you need any guidance we have two experts here with @mbfakourii and @Nidal-Bakir who are here to help.
