### ISSUE TITLE
Losing currentUser session after hot restart or hot reload in debug mode for flutter web

### ISSUE THREAD

**Issue by jeffpontocom** [parse-community/Parse-SDK-Flutter#851]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description

Can't mantain the current user session on flutter web applications.

### Steps to reproduce

1. On main() initialize Parse => Parse().initialize(...), then get current user => ParseUser.currentUser();
2. Start main widget and do login;
3. Execute a hot restart/reload

### Actual Outcome

After every hot restart/reload we need to login again

### Expected Outcome

Maintain the current user session

### Environment

Parse Flutter SDK
- SDK version: flutter 3.7.5
- Operating system version: Windows 10/Chrome 110.0.5481.180 64 bits

Server
- Parse Server version: parse_server_sdk 4.0.0

### Logs

No logs

**Comment by Nidal-Bakir** [comment]
I'm unable to reproduce the error on my end can you provide a simple code when this problem occurs?

With the following code on Flutter Web using `parse_server_sdk_flutter: ^4.0.0`:

``` dart 
import 'package:flutter/material.dart';
import 'package:parse_server_sdk_flutter/parse_server_sdk_flutter.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await initParse();

  runApp(const MyApp());
}

Future<void> initParse() async {
  await Parse().initialize(
    '***',
    'ParseURL',
    clientKey: '****',
    autoSendSessionId: true,
    debug: true,
    coreStore: await CoreStoreSharedPrefsImp.getInstance(),
  );

  final user = await ParseUser.currentUser();
  print('***************************************************************');
  print(user);
  print('***************************************************************');
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Column(
        children: [
          FutureBuilder(
            future: ParseUser.currentUser(),
            builder: (context, snapshot) {
              if (snapshot.hasData) {
                return Text((snapshot.data as ParseUser).username.toString());
              }
              return const Text('noData');
            },
          ),
          ElevatedButton(
            onPressed: () {
              ParseUser('nidal', '123456789', 'nidal@g.com').signUp();
            },
            child: const Text('signUp'),
          ),
          ElevatedButton(
            onPressed: () {
              ParseUser('nidal', '123456789', 'nidal@g.com').login();
            },
            child: const Text('login'),
          ),
        ],
      ),
    );
  }
}



```

**Comment by mbfakourii** [comment]
@jeffpontocom 

This bug is from Flutter's side, then every hot restart clears all caches, and Flutter Web does not support hot reload.
I suggest that you implement the process of your application with the Windows Flutter version and run it on the web for the final test.

**Comment by catalunha** [comment]
This is what I do (but on linux). hotReload greatly speeds up development. I do all the UI and State part and then I correct it in the Web.
