### ISSUE TITLE
The SDK will try to save object even if its child object not saved

### ISSUE THREAD

**Issue by Nidal-Bakir** [parse-community/Parse-SDK-Flutter#854]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Steps to reproduce
This will not reproduce the error. I do not know how to force the parse server to fail to save an object so the error will appear.
I catch this error while writing tests for the `save()` function.

1. create ParseObject `planObject`
3. create ParseObject `dietPlansObject`
4. set the `planObject` object as a child object for `dietPlansObject` object
5. call `save()` on the container object `dietPlansObject`

``` dart 
 final planObject = ParseObject('Plans')
          ..set('PlanName', 'plan 1'); // creating this object somehow should fail, then the error will appear.

 final dietPlansObject = ParseObject("Diet_Plans");

 dietPlansObject.set('Plan1', planObject);

 await dietPlansObject.save();

```

### Actual Outcome
The SDK will try to Serialize the `dietPlansObject` to save it online but it can not because the child object is not saved. so an error will be thrown while trying to Serialize the Object.

### Expected Outcome
The `save()` function fails to save the object and returns `ParseError`

### Environment

Parse Flutter SDK
- SDK version: `4.0.0`
- Operating system version: `any`

Server
- Parse Server version: `any`

### Logs

> package:parse_server_sdk/src/objects/parse_base.dart 269:76       ParseBase.toPointer
> package:parse_server_sdk/src/utils/parse_encoder.dart 49:20       parseEncode
> package:parse_server_sdk/src/objects/parse_base.dart 98:20        ParseBase.toJson.<fn>
> dart:collection                                                   _LinkedHashMapMixin.forEach
> package:parse_server_sdk/src/objects/parse_base.dart 96:12        ParseBase.toJson
> package:parse_server_sdk/src/objects/parse_object.dart 73:39      ParseObject.create
> package:parse_server_sdk/src/objects/parse_object.dart 116:26     ParseObject.save
> ===== asynchronous gap ===========================
> test/src/objects/parse_object/parse_object_save_test.dart 404:26  main.<fn>.<fn>
> 
> Null check operator used on a null value
> 
> 
> Process finished with exit code 1

**Comment by Nidal-Bakir** [comment]
@mtrezza @mbfakourii 

For all the issues that I have created and assigned myself to fix them.
I have fixed them and I have written the test for all of them.

I will open new PRs to fix all of them once we are done with the transition to one package. #852

**Comment by mtrezza** [comment]
Reading this I understand now why you assigned yourself to issues. We don't use the assignment feature because it may deter others from picking up an issue that is assigned.

**Comment by mtrezza** [comment]
@Nidal-Bakir Reading this I understand now why you assigned yourself to issues. We don't use the assignment feature because it may deter others from picking up an issue that is assigned.

**Comment by Nidal-Bakir** [comment]
Got it, thanks
