### ISSUE TITLE
No named parameter with the name 'vsync'.

### ISSUE THREAD

**Issue by xfqwdsj** [parse-community/Parse-SDK-Flutter#861]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description

When I built my app, I got an error: parse_server_sdk_flutter-4.0.0/lib/src/utils/parse_live_list.dart(276,9): error GC6690633: No named parameter with the name 'vsync'.

### Steps to reproduce

Building Windows app.

### Actual Outcome

The build fails with the error `No named parameter with the name 'vsync'`.

### Expected Outcome

The build was successful.

### Environment

Parse Flutter SDK
- SDK version: `4.0.0`
- Operating system version: `Windows 11 Build 22621.1413`

Server
- Parse Server version: `6.0.0`

### Logs

```
parse_server_sdk_flutter-4.0.0/lib/src/utils/parse_live_list.dart(276,9): error GC6690633: No named parameter with the name 'vsync'.
```

### Additional content

My Flutter version is `Channel flutter-3.9-candidate.15, 3.9.0-15.0.pre`, in this version, `vsync` parameter seems to be removed, I can manually delete the property specification of `vsync` in the downloaded SDK to fix this problem. This means that the solution to this problem can be as simple as removing a few lines of code from the SDK.

**Comment by xfqwdsj** [comment]
> Can you test this on the Flutter stable channel? it seems that the bug is related to the Flutter framework, not the SDK

In the [documentation for Flutter's AnimatedSize Class](https://api.flutter.dev/flutter/widgets/AnimatedSize-class.html), the vsync property no longer exists, so this is an API change. I guess the SDK should no longer provide that property to AnimatedSize.

**Comment by mtrezza** [comment]
What is the compatibility range of this SDK with Flutter?

**Comment by xfqwdsj** [comment]
> What is the range of Flutter SDK versions that the Parse Flutter SDK currently supports?

Sorry, I admit I was a little presumptuous and impatient. But this property was indeed removed from Flutter - or will be. I also noticed that there is a comment in the code for ignoring deprecation warnings that there are indications that this property will be removed. Anyway, I think removing it now would be useful, even if it's too early.

**Comment by mtrezza** [comment]
Usually how this works is that certain features are only made available based on the underlying framework version. Not sure if that is possible in Flutter?

Could we detect the Flutter SDK version inside our code and just remove the property if the version doesn't fit?

**Comment by Nidal-Bakir** [comment]
No need to do anything about this property removal it was deprecated since Flutter 2.2.xx `Apr 15 21 `
and we are now the latest stable release of Flutter is  3.7.8 ` Mar 22 23`

More than 2 years of deprecation, plus no one uses Flutter `2.x.x` the whole community migrated to Flutter `>=3.x.x`

From the source code of flutter:

>   @Deprecated(
>       'This field is now ignored. '
>       'This feature was deprecated after v2.2.0-10.1.pre.'
>     )

**Comment by mtrezza** [comment]
> So, the only affected users are those who are still using Flutter versions <2.2.0, which is not common in the Flutter community and is discouraged. 

If it is technically possible that there is an app out there that uses Flutter <2.2.0 and the `vsync` property via the Parse Flutter SDK, then we need to consider the removal of the property a breaking change.

> If we need to constraint the Flutter version we need to add a constraint entry like this

I think it makes sense to add this constraint. Adding the constraint is a breaking change in itself. With that we'll release Flutter 5.x.

**Comment by Nidal-Bakir** [comment]
> I think it makes sense to add this constraint. Adding the constraint is a breaking change in itself. With that we'll release Flutter 5.x.

Sure, we can do that

here is what we need to add:

``` yml
environment:
  sdk: ">=2.17.0 <3.0.0" # any Dart versions greater than or equal to 2.17.0 and less than 3.0.0
  flutter: ">=3.0.0"  # any Flutter version greater than or equal to 3.0.0
```
These are the recommended constraints from the flutter tame. these constraints are used by default when creating a Flutter package. When we add these constraints the SDK will not be compatible with Flutter `<3.0.0`

**Comment by mtrezza** [comment]
Current values:

https://github.com/parse-community/Parse-SDK-Flutter/blob/d7339cd3abc6455898228f9bd6fccc078012cd60/packages/dart/pubspec.yaml#L6-L7

https://github.com/parse-community/Parse-SDK-Flutter/blob/d7339cd3abc6455898228f9bd6fccc078012cd60/packages/flutter/pubspec.yaml#L6-L7

If we change the dart range we'll also have to release dart 5.0.  What is the reason for bumping the lower bound of the range from `>=2.12.0` to `>=2.17.0` - is that required?

**Comment by Nidal-Bakir** [comment]
> What is the reason for bumping the lower bound of the range from >=2.12.0 to >=2.17.0?


The main reason for raising the minimum required version of the language is to make new language features available. For example, suppose feature X was introduced in Dart version 2.17.0. Even if our code's version constraints are wide, such as '>=2.12.0 <3.0.0', we cannot use feature X because what if the code runs on a Dart version earlier than 2.17.0? This is because the Dart compiler cannot know which Dart versions the code will run on. Therefore, if our minimum Dart version is lower than 2.17.0, the compiler will NOT allow us to use a feature added in 2.17.0. And this thing applies to the Flutter constraints.

> Does the Dart SDK / Flutter SDK have release cycles? Do they plan when to deprecate older versions, or how does that work?

Yes, there is. see [releases](https://docs.flutter.dev/development/tools/sdk/releases?tab=linux)
but you see there is no release cycle for bug fixes for example those have a special release cycle maybe every two weeks or mouth something like that.

**Comment by sgehrman** [comment]
what's taking so long?? I'll have to fork

**Comment by mtrezza** [comment]
#872 is currently blocking the release. Feel free to join the discussion.

**Comment by funjay** [comment]
hi Guys

May 12th and this error still exists 
No named parameter with the name 'vsync'

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on Fedora Linux 38 (Workstation Edition) 6.2.14-300.fc38.x86_64, locale en_IE.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web

flutter totally dropped that parameter, 
I guess we should remove it and create a patch release for those with newer flutter ie > 3.0 and for older flutter users they can use older version of parse. 

I needed this flutter version and i cannot downgrade

anyone with a fork and fix?

thanks

**Comment by xfqwdsj** [comment]
@funjay For a temporary fix, you can manually modify the local pub cache and remove the specified property.

**Comment by Nidal-Bakir** [comment]
@funjay @xfqwdsj

We're almost done, and we'll probably release version 5.0.0 of the Dart and Flutter SDKs tomorrow. Hopefully, we won't encounter similar issues in the future.
