### ISSUE TITLE
remove print() line: 393 in parse_live_query.dart _handleMessage

### ISSUE THREAD

**Issue by sgehrman** [parse-community/Parse-SDK-Flutter#870]
Parse-SDK-Flutter/packages/dart/lib/src/network/parse_live_query.dart

```
  void _handleMessage(String message) {
    if (_debug) {
      print('$_printConstLiveQuery: Listen: $message');
    }

    final Map<String, dynamic> actionData = jsonDecode(message);

    Subscription? subscription;
    if (actionData.containsKey('op') && actionData['op'] == 'connected') {
      print('Re subscription:$_requestSubscription'); <<========================WHY?
```

**Comment by mbfakourii** [comment]
@sgehrman 
hi, if possible, edit the issues according to the templates

**Comment by mtrezza** [comment]
I'm closing this as it does not use the issue template provided when creating an issue and therefore lacks essential information required to investigate the issue. Please edit your initial post using the issue template and we can re-open this issue.

**Comment by sgehrman** [comment]
wow, what a bunch of jerks.  Fix your buggy code.
