### ISSUE TITLE
Flutter 5 package not published

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Flutter#881]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description

It seems that publishing the Parse Flutter SDK 5.0.0 fails to publish to pub.dev:

> Validating package...
> Connection closed before full header was received

It may have something to do with changes made to the package that make the validation fail on pub dev side, because validation works for publishing the Parse Dart SDK, so it seems not a network issue. Or it could be a bug in the GitHub Action plugin `k-paxian/dart-package-publisher@v1.5.1`.

### Steps to reproduce

See
- https://github.com/parse-community/Parse-SDK-Flutter/actions/runs/4969882335/jobs/8893394233
- https://github.com/parse-community/Parse-SDK-Flutter/actions/runs/4969712540/jobs/8893091664

**Comment by mbfakourii** [comment]
Probably the request timed out. I tested it and didn't get an error. Is it possible to run it again?

Also, some commands have been deprecated
```dart
The "format" command is deprecated. Please use the "dart format" sub-command instead, which has the same command-line usage as "flutter format".
```

**Comment by Nidal-Bakir** [comment]
I will do more research when I come home.

If I understand correctly if the problem is a pub validation then the package will be published and pub dev will show an 'analysis issue' label and will tell us what went wrong. We can see the validation/analysis errors in the points/score section in the package page.

**Comment by mbfakourii** [comment]
> I will do more research when I come home.
> 
> If I understand correctly if the problem is a pub validation then the package will be published and pub dev will show an 'analysis issue' label and will tell us what went wrong. We can see the validation/analysis errors in the points/score section on the package page. So I do think it's a validation error. I have seen this problem before it always means a connection error.
> 
> Can try to rerun the CI job?
> 
> Can you try to publish it manually from your PC?

i run ```dart pub publish --dry-run ```
There was no problem

**Comment by mtrezza** [comment]
Ran it 4 times with the same error. If it works locally for you then it may be an issue with the publish plugin we're using in GH Actions.

**Comment by mbfakourii** [comment]
> Ran it 4 times with the same error. If it works locally for you then it may be an issue with the publish plugin we're using in GH Actions. I already upgraded to the latest version yesterday.
> 
> When you run dry run locally, do you see the same output as we see in GH Actions? I'm trying to understand whether this "Validating packages..." is from `dart publish` or from the plugin we're using.

No. My output is as follows
```dart
dart pub publish --dry-run
Resolving dependencies... 
  collection 1.17.1 (1.17.2 available)
  connectivity_plus 3.0.6 (4.0.0 available)
  matcher 0.12.15 (0.12.16 available)
  material_color_utilities 0.2.0 (0.5.0 available)
  package_info_plus 3.1.2 (4.0.0 available)
  source_span 1.9.1 (1.10.0 available)
  test_api 0.5.1 (0.5.2 available)
|           |-- parse_live_grid.dart (5 KB)
|           '-- parse_live_list.dart (8 KB)
|-- pubspec.yaml (<1 KB)
'-- test
    |-- parse_client_configuration_test.dart (1 KB)
    '-- src
        '-- storage
            '-- core_store_directory_io_test.dart (7 KB)
Validating package... (4.5s)
Package has 0 warnings.
The server may enforce additional checks.

```

**Comment by mtrezza** [comment]
It may be a plug-in issue then.

Maybe we should try to use [firehose](https://github.com/dart-lang/ecosystem/tree/main/pkgs/firehose), which seems to be a dart tool for the same purpose?

**Comment by Nidal-Bakir** [comment]
It's probably a plugin issue.

We should use the recommended solution by the Flutter team [publishing packages using github actions](https://dart.dev/tools/pub/automated-publishing#publishing-packages-using-github-actions)

@mtrezza Are you available at the moment? I'm going to open a pull request that requires your involvement because you are the admin/author of the packages

**Comment by mtrezza** [comment]
Release workflow fails with 

> [Invalid workflow file: .github/workflows/release-manual.yml#L25](https://github.com/parse-community/Parse-SDK-Flutter/actions/runs/4986159487/workflow)
The workflow is not valid. .github/workflows/release-manual.yml (Line: 25, Col: 11): Unexpected symbol: 'and'. Located at position 42 within expression: github.event.inputs.package == 'flutter' and 'packages/flutter' or 'packages/dart'

**Comment by mtrezza** [comment]
Release workflow fails with:


> Run dart pub get --directory packages/flutter

> Resolving dependencies in packages/flutter...
> Because parse_server_sdk_flutter depends on flutter_test from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.
> 
> Flutter users should run `flutter pub get` instead of `dart pub get`.

**Comment by Nidal-Bakir** [comment]
We need to install Flutter when publishing the Flutter SDK.

**Comment by mtrezza** [comment]
Flutter 5.0.0 has been published, the manual release workflow had to removed becase it's not working anymore with the new release method, which requires a tag to be published. That means to manually publish a release, any existing tag of the same needs to be deleted and a new tag need to be pushed in order to trigger the release.
