### ISSUE TITLE
Document improvement

### ISSUE THREAD

**Issue by mbfakourii** [parse-community/Parse-SDK-Flutter#885]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Current Limitation
Long document

### Feature / Enhancement Description
In my opinion, it is better to merge two documents that are almost 80% similar and transfer them to the [parseplatform](https://parseplatform.org/) site. Then just link to README.md

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by mbfakourii** [comment]
I merged the two documents and set the categories as below

Getting Started
Cloud Code
---- Cloud Functions
Config
Files
Objects
---- Custom Objects
---- Add New Values to Objects
---- Save Objects using Pins
---- Increment Counter Values
---- Array Operator in Objects
---- Security for Objects - ParseACL
Queries
---- Complex Queries
---- Relational queries
---- Counting objects
---- LiveQuery
---- ParseLiveList
---- Relation
Storage
Users
---- Facebook, OAuth and 3rd Party Login/User
Other Features

Please take a look [here](https://github.com/parse-community/docs/pull/928)

**Comment by mtrezza** [comment]
Nice! That's something we had on the radar for quite some time already.

**Comment by Nidal-Bakir** [comment]
So, does this mean that if someone needs to update the documentation, they will have to make changes in two different places, requiring two different pull requests?

**Comment by Nidal-Bakir** [comment]
Got it, thanks
