### ISSUE TITLE
No named parameter with the name 'vsync'.

### ISSUE THREAD

**Issue by catalunha** [parse-community/Parse-SDK-Flutter#887]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
While updating a widgets part of my app I came across this output when compiling my project.

### Steps to reproduce
Start debugging a Flutter project with
```
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  parse_server_sdk_flutter: ^4.0.0


```
### Actual Outcome
does not execute

### Expected Outcome
Run my project as days ago

### Environment

Parse Flutter SDK
- SDK version: `parse_server_sdk_flutter: ^4.0.0`
- Flutter version: `3.10`
- Dart version: `3`
- Operating system version: `PopOS`

Server
- Parse Server version: `Back4app 5.2.3`

### Logs
```
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
: Error: No named parameter with the name 'vsync'.
        vsync: this,
        ^^^^^
: Context: Found this candidate, but the arguments don't match.
  const AnimatedSize({
        ^^^^^^^^^^^^

Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script '/home/catalunha/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/catalunha/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 20s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by catalunha** [comment]
There is this other closed issue with this same problem.
https://github.com/parse-community/Parse-SDK-Flutter/issues/861
But he persists in my project. Even updating to parse_server_sdk_flutter: ^4.0.0

Can you help me. I have this project on hold. :-((

**Comment by Nidal-Bakir** [comment]
The issue has been solved in the Parse Flutter SDK 5.0.0 but the package did not get uploaded to pub for some reason. See #881

As a temp solution get the package directly from git  

```yml 

parse_server_sdk_flutter:
    git:
      url: https://github.com/parse-community/Parse-SDK-Flutter.git
      ref: master
      path: packages/flutter/

```

**Comment by catalunha** [comment]
Thanks for the immediate response. You saved my life.
TESTING HERE...
Then I close the issue

**Comment by Nidal-Bakir** [comment]
Closing as completed via #861.

Feel free to reopen the issue or to report a new one.
