### ISSUE TITLE
Publishing Dart SDK 5.1.1 failed

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Flutter#905]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description

Analyzer failed with:
> info - example/main.dart:1:8 - Can't use a relative path to import a library in 'lib'. Try fixing the relative path or changing the import to a 'package:' import. - avoid_relative_lib_imports

The question is also why this was not already detected in the CI of the PR - maybe there is room for improvement?

### Logs

https://github.com/parse-community/Parse-SDK-Flutter/actions/runs/5007534966

### Important

This issue blocks the commit pipeline.

**Comment by Nidal-Bakir** [comment]
How this passed the Ci tests?

Our current CI setup should catch such a thing.

**Comment by mtrezza** [comment]
Maybe it runs on a different dart version?

**Comment by Nidal-Bakir** [comment]
No, see #906
