### ISSUE TITLE
update the package awesome_notifications

### ISSUE THREAD

**Issue by sgehrman** [parse-community/Parse-SDK-Flutter#931]
awesome_notifications >=0.6.20 <0.7.5-dev.1 depends on intl ^0.17.0

**Comment by mbfakourii** [comment]
This problem is solved in awesome_notifications version 0.7.5-dev.2+1, it is still in prerelease stage!

https://github.com/rafaelsetragni/awesome_notifications/pull/786#issuecomment-1567579374

**Comment by mbfakourii** [comment]
This package has been removed, you can use the latest version of Parse Flutter
