### ISSUE TITLE
  connectivity_plus: ^3.0.6 is old

### ISSUE THREAD

**Issue by sgehrman** [parse-community/Parse-SDK-Flutter#945]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
 
Update to connectivity_plus: ^4.0.1

**Comment by mtrezza** [comment]
@sgehrman I refer you to our [Code of Conduct](https://github.com/parse-community/.github/blob/main/CODE_OF_CONDUCT.md) regarding the use of proper language in this forum.

**Comment by mtrezza** [comment]
@sgehrman Your comment has been revised. I refer you to our [Code of Conduct](https://github.com/parse-community/.github/blob/main/CODE_OF_CONDUCT.md) regarding the use of proper language in this forum.

**Comment by mbfakourii** [comment]
According to the [support policy](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/flutter#compatibility), I think it is better to close this PR.
