### ISSUE TITLE
Building Web application failed

### ISSUE THREAD

**Issue by xfqwdsj** [parse-community/Parse-SDK-Flutter#947]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description

Building Web application failed.

### Steps to reproduce

1. Updating SDK to the latest `5.1.1`
2. Updating `CoreStoreSembastImp` to `CoreStoreSembast` (API changes not included in the changelog)
3. Building Web app

### Actual Outcome

Building succeeded.

### Expected Outcome

Building failed.

In `5.0.1`, the build can be successful.

### Environment

Parse Flutter SDK
- SDK version: `5.1.1`
- Flutter version: `3.10.5`
- Dart version: `3.0.5`
- Operating system version: `Microsoft Windows [Version 10.0.22621.1848]` (Building using `ubuntu-latest` from Github Actions)

### Logs

```
Error: The method 'dbDirectory' isn't defined for the class 'CoreStoreDirectory'.
 - 'CoreStoreDirectory' is from 'package:parse_server_sdk_flutter/src/storage/core_store_directory_web.dart' ('/opt/hostedtoolcache/flutter/stable-3.10.5-x64/.pub-cache/hosted/pub.dev/parse_server_sdk_flutter-5.1.1/lib/src/storage/core_store_directory_web.dart').
        await CoreStoreDirectory().dbDirectory(),
                                   ^^^^^^^^^^^
Error: Compilation failed.
```

**Comment by keanallen** [comment]
Hi, any updates on this?
I'm having the same issue when running my app into chrome browser.
My app will support 3 platforms: `Web`, `android`, `iOS`
