### ISSUE TITLE
Version 5.1.2 compile problems

### ISSUE THREAD

**Issue by hello96** [parse-community/Parse-SDK-Flutter#958]
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [ x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
It's not possible to build a project when the SDK is installed. I think it should be something related to latest Dart versions, but I'm not sure.

### Steps to reproduce
1. Create an empty flutter application;
2. Import latest parse sdk version (currently 5.1.2);
3. Call Parse().initialize()

### Actual Outcome
![image](https://github.com/parse-community/Parse-SDK-Flutter/assets/31999705/f55039ab-28e1-41b5-8806-79f74f9e7a31)

### Expected Outcome
To work :)

### Environment
Parse Flutter SDK
- SDK version: `5.1.2`
- Flutter version: `3.10.5`
- Dart version: `3.0.5`
- Operating system version: `Windows 11 and MacOS M1`

Server
- Parse Server version: `4.5.0`

### Logs
![image](https://github.com/parse-community/Parse-SDK-Flutter/assets/31999705/f55039ab-28e1-41b5-8806-79f74f9e7a31)

**Comment by GIovaB6** [comment]
Yeah, i've the same problem

**Comment by codakkk** [comment]
I'm encountering the same issue, right now

**Comment by mbfakourii** [comment]
It seems to be from `Dio`, I will check

**Comment by Piyush-e7** [comment]
Yeah, I have the same problem

**Comment by mbfakourii** [comment]
The problem has been solved on the [dio side](https://github.com/cfug/dio/pull/1916). I am waiting for the new version of dio. Please use the old versions until the new version thanks

**Comment by mbfakourii** [comment]
@hello96 @GIovaB6 @codakkk @Piyush-e7 

Has the problem been solved?

**Comment by mbfakourii** [comment]
Bug Fixed
