### ISSUE TITLE
ParseInstallation timeZone missing

### ISSUE THREAD

**Issue by IonAgorria** [parse-community/Parse-SDK-Flutter#96]
As explained in https://github.com/phillwiggins/flutter_parse_sdk/pull/95 currently there is no a proper way to get time zone as Parse Server expects in Flutter, one solution would be using platform specific code.

**Comment by rodrigosmarques** [comment]
Hi @IonAgorria 
I checked the Parse SDK code on Android and it gets the TimeZone from the device and not from the server.

This lib here can help: https://pub.dartlang.org/packages/flutter_native_timezone
`
    // Android documentation states that getID may return one of many forms: America/LosAngeles,
    // GMT-<offset>, or code. We only accept the first on the server, so for now we will not upload
    // time zones from devices reporting other formats.
    private void updateTimezone() {
        String zone = TimeZone.getDefault().getID();
        if ((zone.indexOf('/') > 0 || zone.equals("GMT")) && !zone.equals(get(KEY_TIME_ZONE))) {
            performPut(KEY_TIME_ZONE, zone);
        }
    }

`

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
