### ISSUE TITLE
Update Dependencies of parse sdk to 5.1.3

### ISSUE THREAD

**Issue by funjay** [parse-community/Parse-SDK-Flutter#966]
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [ x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [ x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description

Pub get fails 
Because no versions of parse_server_sdk_flutter match >6.0.0 <7.0.0 and parse_server_sdk_flutter 6.0.0 depends on parse_server_sdk ^5.1.2, parse_server_sdk_flutter ^6.0.0 requires parse_server_sdk ^5.1.2.
And because parse_server_sdk >=4.0.0 depends on http ^0.13.5, parse_server_sdk_flutter ^6.0.0 requires http ^0.13.5

Parse_server_sdk is now 5.1.3 can we update the sdk_flutter to depend on the latest?

### Steps to reproduce

Add  parse_server_sdk_flutter: ^6.0.0
and any other package that depends on http: > 1.0.0

### Actual Outcome

Fails with error above

### Expected Outcome

Pub get should succeed without errors

### Environment

Parse Flutter SDK
- SDK version: `6.0.0`
- Flutter version: `3.10.6`
- Dart version: `3.0.6`
- Operating system version: `Fedora`

Server
- Parse Server version: `not required`

**Comment by funjay** [comment]
invalid

**Comment by mbfakourii** [comment]
> invalid

I am looking into this possibility, unfortunately, in my last check, we had many conflict with other packages

**Comment by mbfakourii** [comment]
@funjay 

According to [our support policy](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/dart#compatibility), we currently cannot cancel our support for versions below 3 darts(Until May 2024).

My suggestion is to use [dependency_overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides).
like this
```dart
dependency_overrides:
  http: ^1.1.0
```
