### ISSUE TITLE
Update your packages

### ISSUE THREAD

**Issue by sgehrman** [parse-community/Parse-SDK-Flutter#972]
I've reported this numerous times.  Why do you do this?  This is by far the most difficult package to use on pub.dev.

Because parse_server_sdk_flutter >=5.1.1 depends on connectivity_plus ^3.0.6 and bonsoir_platform_interface >=3.0.0 depends on connectivity_plus >=4.0.0 <4.1.0, parse_server_sdk_flutter >=5.1.1 is incompatible with
  bonsoir_platform_interface >=3.0.0.

**Comment by mtrezza** [comment]
@sgehrman You are free to open a pull request any time. Keep in mind that this is a community project. I remind you once again to mind our [Code of Conduct](https://github.com/parse-community/.github/blob/main/CODE_OF_CONDUCT.md).
