### ISSUE TITLE
`installationId` in LiveQuery `connect`

### ISSUE THREAD

**Issue by mbfakourii** [parse-community/Parse-SDK-Flutter#975]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
`LiveQuery` does not send `installationId` when connect.

### Steps to reproduce
n/a

### Actual Outcome
n/a

### Expected Outcome
n/a

### Environment

Parse Flutter SDK
- SDK version: `7.0.0`
- Flutter version: `3.13.9`
- Dart version: `3.1.5`
- Operating system version: `Ubuntu`

Server
- Parse Server version: `5.6.0`

### Logs
n/a

**Comment by mtrezza** [comment]
This is balled as `bug` but the PR is a `feat` - which of the 2 is it?

**Comment by mbfakourii** [comment]
> This is balled as `bug` but the PR is a `feat` - which of the 2 is it?

This issues is `feat`.
`installationId` was not sent in `LiveQuery` before.
