### ISSUE TITLE
Request to update dependency paackages

### ISSUE THREAD

**Issue by valerycolong** [parse-community/Parse-SDK-Flutter#977]
Kindly update dependency packages to their latest versions where applicable. 

Old package versions like that of connectivity_plus is stopping installation of other packages with newer versions of related packages.

I'll be grateful if you respond to this request promptly.

**Comment by mbfakourii** [comment]
@valerycolong 

According to [our support policy](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/dart#compatibility), we currently cannot cancel our support for versions below 3 darts (Until May 2024).

My suggestion is to use [dependency_overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides).
like this
```dart
dependency_overrides:
  connectivity_plus: ^5.0.2
```
