### ISSUE TITLE
parse_server_sdk_flutter won't work with google_fonts 

### ISSUE THREAD

**Issue by kwasu123** [parse-community/Parse-SDK-Flutter#982]
### New Issue Checklist

- [ x ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [ x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [ x ] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [ x ] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
Package parse_server_sdk_flutter won't work with latest google_fonts package. 

### Steps to reproduce
Add latest google_fonts package form pub.dev
Add latest parse_server_sdk_flutter package from  pub.dev

### Actual Outcome
Resolving dependencies...
Because parse_server_sdk_flutter >=7.0.0 depends on parse_server_sdk ^5.1.3 which depends on http ^0.13.5, parse_server_sdk_flutter >=7.0.0 requires http ^0.13.5.
And because every version of myFlutterApp from git depends on google_fonts ^5.0.0 which depends on http ^1.0.0, parse_server_sdk_flutter >=7.0.0 is incompatible with myFlutterApp from git.
So, because myFlutterApp depends on both myFlutterApp from git and parse_server_sdk_flutter 7.0.0, version solving failed.
exit code 1

### Expected Outcome

- parse_server_sdk_flutter package  works with google_fonts package.
- parse_server_sdk_flutter support latest http package
- exit code 0

### Environment
parse_server_sdk_flutter 7.0.0

Parse Flutter SDK
- SDK version: `>=3.0.3 <4.0.0"`
- Flutter version: `Flutter 3.16.4 • channel stable`
- Dart version: `Dart 3.2.3`
- Operating system version: `macOS arm64`

Server
- Parse Server version: 7.0.0

**Comment by mbfakourii** [comment]
According to [our support policy](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/dart#compatibility), we currently cannot cancel our support for versions below 3 darts (Until May 2024).

My suggestion is to use [dependency_overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides).
like this
```dart
dependency_overrides:
  http: ^1.1.2
```

**Comment by kwasu123** [comment]
dependency_overrides temporary solve issue.
Thanks!
