### ISSUE TITLE
depends on parse_server_sdk_flutter ^7.0.0 which depends on package_info_plus ^4.0.2

### ISSUE THREAD

**Issue by sgehrman** [parse-community/Parse-SDK-Flutter#984]
The never ending issue I've reported for years now. 

UPDATE YOUR PACKAGES!!

Are you purposely trying to kill parse?

**Comment by mbfakourii** [comment]
According to [our support policy](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/dart#compatibility), we currently cannot cancel our support for versions below 3 darts (Until May 2024).

My suggestion is to use [dependency_overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides).
like this
```dart
dependency_overrides:
  package_info_plus: ^5.0.1
```
