### ISSUE TITLE
connectivity_plus plugin latest versions are not supported

### ISSUE THREAD

**Issue by ikarelin** [parse-community/Parse-SDK-Flutter#986]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
/Users/ikarelin/Developer/flutter/bin/flutter --no-color pub get
Resolving dependencies...
Because parse_server_sdk_flutter 7.0.0 depends on connectivity_plus ^3.0.6 and no versions of parse_server_sdk_flutter match >7.0.0 <8.0.0, parse_server_sdk_flutter ^7.0.0 requires connectivity_plus ^3.0.6.
So, because easy_renty depends on both connectivity_plus ^5.0.2 and parse_server_sdk_flutter ^7.0.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on connectivity_plus: flutter pub add connectivity_plus:^3.0.6

### Environment

Parse Flutter SDK
- SDK version: parse_server_sdk_flutter: ^7.0.0
- Flutter version:  3.16.5 
- Dart version: Dart 3.2.3
- Operating system version: Mac OS Sonoma

Server
- Parse Server version: 5.5.4

**Comment by mbfakourii** [comment]
According to [our support policy](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/dart#compatibility), we currently cannot cancel our support for versions below 3 darts (Until May 2024).

My suggestion is to use [dependency_overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides).
like this
```dart
dependency_overrides:
  connectivity_plus: ^5.0.2
```

**Comment by PiotrMitkowski** [comment]
@mbfakourii it seems, that version 5.0.2 of the `connectivity_plus` requires Dart 2.18 as the minimum version, so it should be fine with your support policy. Even for the Flutter package, `connectivity_plus` requires Flutter 3.3.0, which also matches your constraints.

**Comment by mbfakourii** [comment]
> @mbfakourii it seems, that version 5.0.2 of the `connectivity_plus` requires Dart 2.18 as the minimum version, so it should be fine with your support policy. Even for the Flutter package, `connectivity_plus` requires Flutter 3.3.0, which also matches your constraints.

I will check, thanks for the information
