### ISSUE TITLE
Update parse_server_sdk http version from ^0.13.5 to last version(http: ^1.2.1)

### ISSUE THREAD

**Issue by Kora3** [parse-community/Parse-SDK-Flutter#988]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Current Limitation

Version 0.13.5 of flutter http is more than a year old, because of this it is impossible to install other packages using a newer version of http, like for example pro_image_editor cannot install because parse_server_sdk_flutter uses an old version of http, and we cannot install recent versions of flutter_map, google_fonts, flutter_native_splash because of the same reason.

### Feature / Enhancement Description

Update parse_server_sdk_flutter http to last (http: ^1.2.1)

**Comment by mbfakourii** [comment]
According to [our support policy](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/dart#compatibility), we currently cannot cancel our support for versions below 3 darts (Until May 2024).

My suggestion is to use [dependency_overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides).
like this

```dart
dependency_overrides:
  http: ^1.2.1
```

**Comment by Kora3** [comment]
Oki thanks

**Comment by Kora3** [comment]
I tried and it's work👍
