### ISSUE TITLE
Support `XFile`

### ISSUE THREAD

**Issue by mbfakourii** [parse-community/Parse-SDK-Flutter#989]
### New Feature / Enhancement Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Current Limitation
When we want to use the file both on the web and the normal file in the project, we face problems in Parse projects.
For this reason, I suggest to merge `ParseWebFile` and `ParseFile` together.

### Feature / Enhancement Description
I suggest using `XFile` to solve this problem. With this function, we support both normal `File` and `Uint8List`.

### Example Use Case
n/a

### Alternatives / Workarounds
There is no use of both types of files in Parse when we register the file.

**Comment by mtrezza** [comment]
Does this SDK already have a ParseFile class like other Parse SDKs, and if yes, will it be replaced by ParseXFile?

**Comment by mbfakourii** [comment]
> Does this SDK already have a ParseFile class like other Parse SDKs, and if yes, will it be replaced by ParseXFile?

In Parse-SDK-Flutter, we use two types of ParseWebFile to support Flutter Web and ParseFile for other platforms.

In large projects that require the output of all platforms from Flutter, including the web, it is necessary to use both ParseWebFile and ParseFile. This is where I run into conflict problems. XFile is a type of file created by the Flutter team and tries to Solve the file problem in platforms and web. Therefore, I suggest that this item be added to Parse Flutter.

Your suggestion for replaced with ParseFile is also very good, but it is better for ParseXFile to be tested and evaluated more and in the future to be integrated with ParseFile with a breaking change.

**Comment by mtrezza** [comment]
So there will be a `ParseFile`, `ParseWebFile`, `ParseXFile` for now, and in the future `ParseWebFile` and `ParseXFile` will be merged into `ParseFile`? Sounds like a good plan.

**Comment by mbfakourii** [comment]
> So there will be a `ParseFile`, `ParseWebFile`, `ParseXFile` for now, and in the future `ParseWebFile` and `ParseXFile` will be merged into `ParseFile`? Sounds like a good plan.

Yes, this is the best way
