### ISSUE TITLE
Why do you refuse to update your packages?

### ISSUE THREAD

**Issue by sgehrman** [parse-community/Parse-SDK-Flutter#997]
It's not that difficult.  Update your packages.  Why do you make this difficult for everyone?

**Comment by mbfakourii** [comment]
> It's not that difficult. Update your packages. Why do you make this difficult for everyone?

We have a support policy, please check [this](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/flutter#compatibility) section

**Comment by mtrezza** [comment]
@sgehrman You are repeatedly asking the same question and you repeatedly received the same answer to it. If you continue to open the same issues then we have to consider this spam and take appropriate action.

**Comment by mtrezza** [comment]
@sgehrman You have repeatedly asked the same question and you repeatedly received the same answer. Also please remember that this is a community project and most contributors here are maintaining these repositories on a voluntary basis in their free time. The tone in your comments is not appropriate and we have tried to bring this to your attention in the past.
